import json

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

words = data['words']
word_map = {w['id']: w for w in words}

new_examples = {
    1: [  # abeyance
        {"situation": "특허 분쟁 보류", "en": "The patent infringement case was held in abeyance pending the outcome of inter partes review proceedings before the patent office.", "ko": "특허 사무소의 당사자 간 재심 절차 결과가 나올 때까지 특허 침해 소송은 보류 상태로 유지되었다."},
        {"situation": "환경 규제 유예", "en": "Implementation of the new emissions standards was placed in abeyance following industry lobbying that cited inadequate transition timelines.", "ko": "불충분한 전환 일정을 이유로 한 업계 로비 활동에 따라 새로운 배출 기준의 시행이 유예 상태에 놓였다."},
        {"situation": "외교 협상 중단", "en": "The bilateral disarmament talks remained in abeyance for nearly a decade as both nations pursued parallel unilateral military expansion.", "ko": "양국이 병행하여 일방적 군사 확장을 추진하는 동안 양자 군비 축소 회담은 거의 10년간 중단 상태로 남아 있었다."},
        {"situation": "기업 인수 결정 연기", "en": "The board held the acquisition decision in abeyance until independent auditors completed a forensic examination of the target company's liabilities.", "ko": "이사회는 독립 감사인들이 인수 대상 회사의 부채에 대한 법의학적 검토를 완료할 때까지 인수 결정을 보류 상태로 유지했다."},
        {"situation": "학술 출판 보류", "en": "The journal editors placed the manuscript in abeyance while awaiting peer review reports that would determine its suitability for publication.", "ko": "학술지 편집자들은 출판 적합성을 판단할 동료 심사 보고서를 기다리는 동안 원고를 보류 상태로 두었다."},
    ],
    2: [  # abrogation
        {"situation": "관습법 폐지 논쟁", "en": "The legislative abrogation of centuries-old customary land rights sparked fierce resistance from indigenous communities and international human rights organizations.", "ko": "수 세기에 걸친 관습적 토지 권리에 대한 입법적 폐지는 원주민 공동체와 국제 인권 단체들의 격렬한 저항을 불러일으켰다."},
        {"situation": "학문적 자유 침해", "en": "Scholars condemned the policy as tantamount to an abrogation of academic freedom, arguing that it effectively silenced dissenting intellectual voices.", "ko": "학자들은 그 정책을 학문적 자유의 폐지에 상당하는 것으로 비판하며, 사실상 반대 지식인의 목소리를 침묵시킨다고 주장했다."},
        {"situation": "복지 시스템 해체", "en": "Economists warned that the proposed fiscal reforms constituted a de facto abrogation of the state's obligation to provide universal social welfare.", "ko": "경제학자들은 제안된 재정 개혁이 사실상 보편적 사회 복지를 제공해야 할 국가 의무의 폐지에 해당한다고 경고했다."},
        {"situation": "기후 협약 탈퇴", "en": "The administration's abrogation of its commitments under the multilateral climate accord drew sharp criticism from both domestic and international environmental advocates.", "ko": "다자간 기후 협약에 따른 약속을 폐기한 행정부의 행위는 국내외 환경 옹호자들의 날카로운 비판을 받았다."},
        {"situation": "노동권 보호 철폐", "en": "Labor unions argued that the emergency legislation represented nothing less than a systematic abrogation of workers' constitutionally guaranteed collective bargaining rights.", "ko": "노동조합은 긴급 법률이 헌법으로 보장된 근로자의 단체 교섭권에 대한 체계적 폐지에 다름없다고 주장했다."},
    ],
    4: [  # acquiescence
        {"situation": "권위주의적 통치 묵인", "en": "The electorate's acquiescence to increasingly authoritarian governance has been attributed by political theorists to a combination of economic anxiety and media capture.", "ko": "점점 더 권위주의적으로 변해가는 통치에 대한 유권자들의 묵인은 정치 이론가들에 의해 경제적 불안과 언론 장악의 복합적 결과로 분석되었다."},
        {"situation": "불평등 구조 수용", "en": "Sociologists have long debated whether the working class's apparent acquiescence to structural inequality reflects false consciousness or pragmatic resignation.", "ko": "사회학자들은 오랫동안 구조적 불평등에 대한 노동 계급의 외견상 묵인이 허위 의식을 반영하는 것인지 아니면 실용적 체념인지를 논쟁해왔다."},
        {"situation": "조직 내 부당 관행 수용", "en": "The committee's tacit acquiescence to the unethical practices of senior management ultimately rendered it complicit in the resulting corporate scandal.", "ko": "고위 경영진의 비윤리적 관행에 대한 위원회의 암묵적 묵인은 결국 위원회를 그로 인한 기업 스캔들의 공모자로 만들었다."},
        {"situation": "국제법 위반 묵과", "en": "Critics argued that the Security Council's acquiescence to repeated violations of international humanitarian law would fundamentally undermine the rules-based global order.", "ko": "비평가들은 국제인도법의 반복적 위반에 대한 안보리의 묵인이 규칙 기반 세계 질서를 근본적으로 훼손할 것이라고 주장했다."},
        {"situation": "정보 감시 동의", "en": "User acquiescence to invasive data collection practices, often secured through deliberately obfuscated terms of service, raises profound questions about the nature of informed consent.", "ko": "의도적으로 모호하게 만든 서비스 약관을 통해 확보되는 경우가 많은 침습적 데이터 수집 관행에 대한 사용자의 묵인은 정보에 입각한 동의의 본질에 대한 심오한 질문을 제기한다."},
    ],
    5: [  # actuary
        {"situation": "기후 위험 보험 설계", "en": "The actuary developed a sophisticated risk model that incorporated long-term climate projections to recalibrate premium structures for coastal property insurance.", "ko": "보험계리사는 해안 부동산 보험의 보험료 구조를 재조정하기 위해 장기 기후 예측을 통합한 정교한 위험 모델을 개발했다."},
        {"situation": "연금 기금 지속 가능성 분석", "en": "The actuary's assessment revealed that the public pension fund faced a long-term solvency crisis unless contribution rates were substantially increased within a five-year window.", "ko": "보험계리사의 평가에 따르면, 공적 연금 기금은 5년 이내에 기여율이 상당히 인상되지 않는 한 장기적 지급 불능 위기에 직면할 것으로 나타났다."},
        {"situation": "의료보험 상품 개발", "en": "Senior actuaries at the firm were tasked with modeling the financial implications of covering previously excluded pre-existing conditions under the new insurance mandate.", "ko": "회사의 수석 보험계리사들은 새로운 보험 의무 규정 하에 이전에 제외되었던 기존 질환을 보장하는 것의 재정적 함의를 모델링하는 임무를 받았다."},
        {"situation": "재난 준비금 산정", "en": "The actuary calculated that catastrophic reserve requirements should be increased by forty percent to adequately buffer against the rising frequency of extreme weather events.", "ko": "보험계리사는 극단적 기상 현상의 증가하는 빈도에 충분히 대비하기 위해 재난 준비금 요건을 40% 높여야 한다고 산정했다."},
        {"situation": "수명 연장에 따른 재정 계획", "en": "As life expectancy continues to rise, actuaries must fundamentally revise the mortality tables underpinning retirement benefit calculations across both public and private sectors.", "ko": "기대 수명이 계속 증가함에 따라, 보험계리사들은 공공 및 민간 부문 전반에 걸쳐 퇴직 급여 계산을 뒷받침하는 사망률 표를 근본적으로 수정해야 한다."},
    ],
    6: [  # acumen
        {"situation": "벤처 투자 성공", "en": "Her extraordinary financial acumen allowed her to identify undervalued startups in emerging sectors long before institutional investors recognized their transformative potential.", "ko": "그녀의 탁월한 재무적 통찰력은 기관 투자자들이 변혁적 잠재력을 인식하기 훨씬 전에 신흥 분야의 저평가된 스타트업을 발굴할 수 있게 해주었다."},
        {"situation": "위기 협상 전략", "en": "The negotiator's acute political acumen enabled him to discern which concessions would be strategically tolerable to each faction without triggering a collapse of the fragile coalition.", "ko": "협상가의 예리한 정치적 통찰력은 취약한 연립을 붕괴시키지 않으면서 각 파벌에 전략적으로 허용 가능한 양보가 무엇인지 간파할 수 있게 해주었다."},
        {"situation": "기업 경쟁력 분석", "en": "The analyst attributed the company's sustained competitive advantage primarily to its founding CEO's exceptional strategic acumen, which had repeatedly anticipated industry disruptions.", "ko": "분석가는 회사의 지속적인 경쟁 우위를 주로 창업 CEO의 뛰어난 전략적 통찰력 덕분으로 평가했으며, 이는 반복적으로 산업 혼란을 예견했다."},
        {"situation": "외교 정책 수립", "en": "Diplomatic acumen of the highest order is required to navigate the complex web of bilateral interests without triggering unintended escalation in an already volatile geopolitical environment.", "ko": "이미 불안정한 지정학적 환경에서 의도치 않은 긴장 고조를 유발하지 않으면서 복잡하게 얽힌 양자 이익을 헤쳐나가기 위해서는 최고 수준의 외교적 통찰력이 필요하다."},
        {"situation": "학술 연구 기획", "en": "The dean's administrative acumen was evident in her ability to secure substantial external funding while simultaneously maintaining the faculty's trust and intellectual autonomy.", "ko": "학장의 행정적 통찰력은 교수진의 신뢰와 지적 자율성을 유지하면서 상당한 외부 자금을 확보하는 능력에서 뚜렷이 나타났다."},
    ],
    7: [  # addendum
        {"situation": "연구 윤리 승인 추가", "en": "The principal investigator filed an addendum to the original ethics application to account for the expanded scope of participant recruitment necessitated by interim results.", "ko": "수석 연구원은 중간 결과로 인해 필요해진 연구 참여자 모집 범위 확대를 반영하기 위해 원래 윤리 신청서에 추가 조항을 제출했다."},
        {"situation": "계약 조건 수정", "en": "Both parties executed a binding addendum to the service agreement that specifically addressed liability limitations arising from force majeure events not covered in the original contract.", "ko": "양측은 원래 계약에서 다루지 않은 불가항력 사건으로 인한 책임 제한을 구체적으로 다루는 구속력 있는 추가 조항을 서비스 계약에 추가로 체결했다."},
        {"situation": "의학 가이드라인 개정", "en": "The clinical guidelines committee issued an urgent addendum following the publication of a landmark randomized controlled trial that contradicted several of the original treatment recommendations.", "ko": "임상 가이드라인 위원회는 원래 치료 권고사항 중 일부에 반하는 획기적인 무작위 대조 시험 결과가 발표된 후 긴급 추가 지침을 발행했다."},
        {"situation": "환경 영향 평가 보완", "en": "The environmental impact assessment required a substantial addendum after new geological surveys revealed previously undetected fault lines beneath the proposed construction site.", "ko": "새로운 지질 조사에서 제안된 건설 부지 아래에 이전에 발견되지 않은 단층선이 밝혀진 후 환경 영향 평가에는 상당한 추가 보완이 필요했다."},
        {"situation": "학위논문 수정", "en": "The doctoral committee required the candidate to submit an addendum addressing three methodological concerns raised during the oral defense before the dissertation could receive final approval.", "ko": "박사 위원회는 논문이 최종 승인을 받기 전에 구술 심사 중 제기된 세 가지 방법론적 우려 사항을 다루는 추가 보완 자료를 제출할 것을 응시자에게 요구했다."},
    ],
    9: [  # abatement
        {"situation": "세금 감면 협상", "en": "The municipality granted a ten-year tax abatement to the pharmaceutical company in exchange for commitments to create five hundred skilled manufacturing jobs within the region.", "ko": "지방자치단체는 해당 지역 내에 500개의 숙련 제조업 일자리를 창출하겠다는 약속의 대가로 제약 회사에 10년간 세금 감면을 부여했다."},
        {"situation": "소음 공해 규제", "en": "The local ordinance mandated progressive noise abatement measures for all commercial aircraft operations between the hours of eleven at night and six in the morning.", "ko": "지역 조례는 오후 11시에서 오전 6시 사이의 모든 상업 항공기 운항에 대해 단계적 소음 저감 조치를 의무화했다."},
        {"situation": "납 오염 제거 정책", "en": "Federal funding for lead abatement in pre-war housing stock was dramatically expanded following epidemiological evidence linking childhood lead exposure to long-term cognitive impairment.", "ko": "아동기 납 노출과 장기적 인지 장애의 연관성을 보여주는 역학적 증거가 나온 후, 전전(戰前) 주택의 납 제거에 대한 연방 자금 지원이 대폭 확대되었다."},
        {"situation": "질소산화물 배출 저감", "en": "The emissions abatement program required industrial facilities to install selective catalytic reduction systems to achieve a forty percent reduction in nitrogen oxide output by the following year.", "ko": "배출 저감 프로그램은 산업 시설이 이듬해까지 질소산화물 배출량을 40% 줄이기 위해 선택적 촉매 환원 시스템을 설치하도록 요구했다."},
        {"situation": "법적 소송 완화", "en": "In lieu of litigation, the parties agreed to a structured abatement plan under which the respondent would remediate contaminated soil in phased installments over thirty-six months.", "ko": "소송 대신 당사자들은 피신청인이 36개월에 걸쳐 단계적으로 오염된 토양을 정화하는 구조화된 저감 계획에 합의했다."},
    ],
    11: [  # affidavit
        {"situation": "제보자 보호 신청", "en": "The attorney filed a sworn affidavit on behalf of the whistleblower, attesting to the veracity of the disclosed documents and seeking protective measures from the court.", "ko": "변호사는 공개된 문서의 진실성을 증언하고 법원으로부터 보호 조치를 구하기 위해 제보자를 대신하여 선서 진술서를 제출했다."},
        {"situation": "자산 동결 신청 지원", "en": "The investigative team submitted a detailed affidavit to the magistrate outlining probable cause for issuing a restraining order to freeze the suspect's overseas financial assets.", "ko": "수사팀은 용의자의 해외 금융 자산 동결을 위한 접근금지명령 발부에 필요한 상당한 이유를 개요로 담은 상세한 진술서를 치안판사에게 제출했다."},
        {"situation": "입양 절차 법적 확인", "en": "The prospective adoptive parents were required to submit a joint affidavit confirming their financial stability, psychological fitness, and commitment to the child's educational welfare.", "ko": "예비 양부모는 재정적 안정성, 심리적 건강, 그리고 아동의 교육적 복지에 대한 헌신을 확인하는 공동 진술서를 제출해야 했다."},
        {"situation": "선거 부정 주장 법적 제출", "en": "The campaign's legal team submitted hundreds of affidavits from poll workers alleging procedural irregularities, though courts found the evidence insufficient to support the fraud allegations.", "ko": "선거 운동 법무팀은 절차적 불규칙성을 주장하는 투표소 직원들의 수백 건의 진술서를 제출했지만, 법원은 사기 혐의를 뒷받침하기에 증거가 불충분하다고 판단했다."},
        {"situation": "학문적 표절 조사 증언", "en": "The original author submitted an affidavit documenting the timeline of her research publication to support the university's investigation into the alleged plagiarism by a colleague.", "ko": "원저자는 동료의 표절 의혹에 대한 대학의 조사를 지원하기 위해 자신의 연구 발표 타임라인을 기록한 진술서를 제출했다."},
    ],
    12: [  # aggregate
        {"situation": "도시 계획 데이터 분석", "en": "Urban planners aggregated mobility data from multiple transit networks to identify underserved communities requiring prioritized infrastructure investment.", "ko": "도시 계획가들은 우선적 인프라 투자가 필요한 서비스 소외 지역을 파악하기 위해 여러 교통 네트워크의 이동성 데이터를 집계했다."},
        {"situation": "역학 조사 데이터 통합", "en": "The epidemiological study aggregated patient records across seventeen hospital systems to achieve a sample size sufficient for statistically meaningful subgroup analyses.", "ko": "역학 연구는 통계적으로 의미 있는 하위집단 분석에 충분한 표본 크기를 달성하기 위해 17개 병원 시스템의 환자 기록을 통합했다."},
        {"situation": "환경 오염 수준 측정", "en": "Regulators cautioned that while aggregate pollution levels met national standards, localized concentrations in residential areas near industrial zones exceeded safe thresholds.", "ko": "규제 당국은 전체 오염 수준은 국가 기준을 충족하지만, 산업 지역 인근 주거 지역의 국지적 농도는 안전 기준치를 초과한다고 경고했다."},
        {"situation": "경제 성장 지표 분석", "en": "Economists noted that the impressive aggregate GDP growth figures obscured widening disparities in household income distribution across different demographic cohorts.", "ko": "경제학자들은 인상적인 총 GDP 성장 수치가 서로 다른 인구 집단 간 가계 소득 분배의 심화되는 불평등을 가리고 있다고 지적했다."},
        {"situation": "글로벌 탄소 배출 평가", "en": "Climate scientists argued that aggregate carbon emissions data, while informative at the macro level, must be disaggregated by sector and nation to enable effective policy interventions.", "ko": "기후 과학자들은 총 탄소 배출 데이터가 거시적 수준에서는 유익하지만, 효과적인 정책 개입을 위해서는 부문별, 국가별로 세분화되어야 한다고 주장했다."},
    ],
    13: [  # allegation
        {"situation": "연구 데이터 조작 의혹", "en": "The university launched a formal inquiry following allegations that a senior professor had systematically falsified experimental data in multiple published studies over a decade.", "ko": "대학은 한 수석 교수가 10년에 걸쳐 여러 발표된 연구에서 실험 데이터를 체계적으로 조작했다는 의혹이 제기되자 공식 조사를 시작했다."},
        {"situation": "기업 담합 혐의", "en": "The antitrust authority investigated allegations that the three dominant players in the telecommunications sector had engaged in coordinated pricing strategies to suppress market competition.", "ko": "반독점 당국은 통신 부문의 3대 지배적 사업자들이 시장 경쟁을 억제하기 위해 조율된 가격 전략에 관여했다는 혐의를 조사했다."},
        {"situation": "선거 개입 의혹", "en": "Parliamentary hearings were convened to examine allegations of foreign interference in the electoral process, with particular scrutiny directed at social media manipulation campaigns.", "ko": "선거 과정에서의 외국 개입 의혹, 특히 소셜 미디어 조작 캠페인에 대한 면밀한 검토를 위해 의회 청문회가 소집되었다."},
        {"situation": "인권 침해 보고", "en": "International monitors documented serious allegations of forced labor practices in the supply chains of several multinational corporations operating in the region.", "ko": "국제 감시단은 해당 지역에서 운영되는 여러 다국적 기업의 공급망에서 강제 노동 관행에 관한 심각한 의혹을 기록했다."},
        {"situation": "내부 고발 제도 검토", "en": "The commission found that a systemic culture of institutional suppression had discouraged employees from formally raising allegations of financial irregularity through official channels.", "ko": "위원회는 체계적인 기관 억압 문화가 직원들로 하여금 공식 채널을 통해 재정 불규칙에 관한 의혹을 공식적으로 제기하지 못하도록 했다는 것을 발견했다."},
    ],
    15: [  # amortization
        {"situation": "부동산 대출 상환 구조", "en": "The thirty-year amortization schedule was structured to front-load interest payments, meaning that equity accumulation in the early years of the mortgage was negligible.", "ko": "30년 상환 일정은 이자 지불을 앞에 집중하도록 설계되어, 모기지 초기 몇 년간은 자기 자본 축적이 미미했다."},
        {"situation": "무형자산 가치 하락 처리", "en": "Under current accounting standards, the amortization of acquired patents must reflect both the remaining legal protection period and the asset's projected economic utility.", "ko": "현행 회계 기준에 따르면, 취득한 특허의 상각은 남은 법적 보호 기간과 해당 자산의 예상 경제적 효용을 모두 반영해야 한다."},
        {"situation": "인프라 재정 계획", "en": "Municipal authorities structured a forty-year bond with a graduated amortization schedule to ensure that debt servicing obligations aligned with the projected revenue stream from the toll road.", "ko": "지방 당국은 부채 상환 의무가 유료 도로의 예상 수익 흐름과 일치하도록 단계적 상각 일정을 갖춘 40년 만기 채권을 설계했다."},
        {"situation": "스타트업 소프트웨어 개발 비용", "en": "The startup's accountants debated whether the internally developed software qualified for capitalization and systematic amortization over its estimated five-year useful life.", "ko": "스타트업의 회계사들은 내부 개발 소프트웨어가 자본화 자격을 갖추며 예상 5년 내용연수에 걸쳐 체계적으로 상각될 수 있는지 논쟁했다."},
        {"situation": "국가 부채 관리 전략", "en": "The sovereign debt restructuring plan proposed extending the amortization period for existing obligations to reduce near-term fiscal pressure while preserving the country's credit standing.", "ko": "국가 채무 재조정 계획은 단기 재정 압박을 줄이면서 국가 신용도를 보전하기 위해 기존 채무의 상각 기간을 연장하는 방안을 제안했다."},
    ],
    18: [  # annuity
        {"situation": "퇴직 소득 보장 계획", "en": "Financial planners often recommend converting a portion of retirement savings into a guaranteed annuity to provide a predictable income stream that cannot be outlived.", "ko": "재무 설계사들은 퇴직 저축의 일부를 보장형 연금으로 전환하여 수명이 다할 때까지 예측 가능한 소득 흐름을 제공하도록 권고하는 경우가 많다."},
        {"situation": "정부 보상 프로그램 설계", "en": "Rather than issuing a lump-sum settlement, the government structured compensation for expropriated property owners as a thirty-year annuity indexed to inflation.", "ko": "정부는 일시금 지급 대신, 수용된 재산 소유자에 대한 보상을 인플레이션에 연동된 30년 연금으로 구조화했다."},
        {"situation": "보험 계리 모델 설계", "en": "Actuaries were tasked with pricing a longevity annuity product that would begin payments at age eighty-five to address the financial risks associated with extreme old age.", "ko": "보험계리사들은 극노령기와 관련된 재정적 위험에 대처하기 위해 85세부터 지급이 시작되는 장수 연금 상품의 가격을 산정하는 임무를 받았다."},
        {"situation": "법원 합의 구조화", "en": "The structured settlement was arranged as an annuity providing monthly payments over twenty-five years, ensuring the plaintiff received adequate long-term compensation for her medical expenses.", "ko": "구조화 합의는 25년에 걸쳐 월별 지급을 제공하는 연금으로 마련되어, 원고가 의료비에 대한 충분한 장기 보상을 받도록 보장했다."},
        {"situation": "대학 기부금 관리", "en": "The university's endowment committee structured the charitable bequest as a charitable remainder annuity, providing income to the donor during her lifetime while preserving the principal for the institution.", "ko": "대학 기부금 위원회는 자선 기부금을 자선 잔여 연금으로 구조화하여, 기증자에게 생전에 소득을 제공하는 동시에 기관을 위해 원금을 보존했다."},
    ],
    20: [  # antecedent
        {"situation": "법적 판례 분석", "en": "The court meticulously reviewed the antecedents of the doctrine to determine whether the current case presented sufficiently novel facts to justify departing from established precedent.", "ko": "법원은 현재 사건이 확립된 판례에서 벗어나는 것을 정당화하기에 충분히 새로운 사실을 제시하는지 판단하기 위해 해당 원칙의 선례를 면밀히 검토했다."},
        {"situation": "사회 운동 역사 분석", "en": "Historians tracing the antecedents of the civil rights movement emphasize the foundational role played by labor organizing and anti-colonial struggles in the preceding decades.", "ko": "민권 운동의 선행 사건들을 추적하는 역사학자들은 앞선 수십 년간 노동 조직화와 반식민지 투쟁이 수행한 근본적 역할을 강조한다."},
        {"situation": "심리적 행동 패턴 이해", "en": "Cognitive behavioral therapy proceeds by identifying the antecedents, behaviors, and consequences that sustain dysfunctional patterns of thought and action in the patient.", "ko": "인지행동치료는 환자의 역기능적 사고 및 행동 패턴을 지속시키는 선행 요인, 행동, 결과를 파악하는 방식으로 진행된다."},
        {"situation": "기술 발전 계보 연구", "en": "The intellectual antecedents of contemporary machine learning can be traced to mid-twentieth century developments in cybernetics, information theory, and mathematical logic.", "ko": "현대 기계 학습의 지적 선행 요인은 20세기 중반의 사이버네틱스, 정보 이론, 수리 논리학의 발전에서 추적할 수 있다."},
        {"situation": "정책 실패 원인 규명", "en": "The audit commission examined the institutional antecedents of the regulatory failure, identifying a decade-long pattern of underfunding and political interference in the oversight body.", "ko": "감사 위원회는 규제 실패의 제도적 선행 요인을 검토하여, 감독 기관에 대한 10년간의 자금 부족과 정치적 간섭 패턴을 파악했다."},
    ],
    22: [  # apportionment
        {"situation": "다국적 기업 세금 배분", "en": "The apportionment of taxable income among jurisdictions in which the multinational operated required complex formulary calculations based on sales, payroll, and property factors.", "ko": "다국적 기업이 운영하는 관할 구역 간 과세 소득의 배분은 매출, 급여, 자산 요소에 기반한 복잡한 공식 계산을 필요로 했다."},
        {"situation": "선거구 획정 논쟁", "en": "The apportionment of congressional seats following the decennial census became deeply contentious as demographic shifts threatened to redraw the political map in favor of urban districts.", "ko": "10년 주기 인구 조사 이후 연방 의회 의석의 배분은 인구통계학적 변화가 도시 지역에 유리하게 정치 지형을 재편할 것으로 예상되면서 깊은 논쟁거리가 되었다."},
        {"situation": "환경 피해 책임 분담", "en": "The court's equitable apportionment of cleanup liability among the seventeen defendants was based on each party's relative contribution to the hazardous waste contamination.", "ko": "법원의 17명의 피고 간 정화 책임의 형평적 배분은 각 당사자의 유해 폐기물 오염에 대한 상대적 기여도에 근거했다."},
        {"situation": "국제 원조 배분 기준", "en": "The development agency's apportionment of humanitarian aid was guided by standardized needs assessments rather than geopolitical considerations, ensuring that resources reached the most vulnerable populations.", "ko": "개발 기관의 인도적 지원 배분은 지정학적 고려 사항보다는 표준화된 필요 평가에 의해 결정되어, 자원이 가장 취약한 집단에게 도달하도록 보장했다."},
        {"situation": "지식재산권 수익 분배", "en": "The licensing agreement specified a precise apportionment of royalty revenues between the original inventor, the commercializing firm, and the university that had hosted the foundational research.", "ko": "라이선스 계약은 원래 발명가, 상업화 기업, 그리고 기초 연구를 유치한 대학 간의 로열티 수익의 정확한 배분을 명시했다."},
    ],
    23: [  # arbitrage
        {"situation": "국제 세금 최적화 전략", "en": "Multinational corporations engaged in regulatory arbitrage by strategically locating intellectual property holdings in jurisdictions offering the most favorable tax treatment.", "ko": "다국적 기업들은 가장 유리한 세금 혜택을 제공하는 관할 구역에 지식재산권 보유를 전략적으로 배치함으로써 규제 차익 거래에 관여했다."},
        {"situation": "환율 차이 이용 거래", "en": "High-frequency trading algorithms exploit transient currency arbitrage opportunities that may persist for only milliseconds before market efficiency eliminates the pricing discrepancy.", "ko": "고빈도 거래 알고리즘은 시장 효율성이 가격 불일치를 해소하기 전에 불과 밀리초 동안만 지속될 수 있는 일시적인 환율 차익 거래 기회를 활용한다."},
        {"situation": "국제 노동 비용 차이 활용", "en": "Critics of globalization argue that corporate labor arbitrage, exploiting wage differentials between developed and developing nations, depresses domestic employment and undermines workers' bargaining power.", "ko": "세계화 비판론자들은 선진국과 개발도상국 간의 임금 격차를 활용하는 기업의 노동 차익 거래가 국내 고용을 억제하고 근로자의 협상력을 약화시킨다고 주장한다."},
        {"situation": "규제 격차 활용 금융 전략", "en": "The investment bank's structured finance division engineered products specifically designed to exploit regulatory arbitrage between banking and insurance accounting frameworks.", "ko": "투자 은행의 구조화 금융 부서는 은행 및 보험 회계 체계 간의 규제 차익 거래를 활용하기 위해 특별히 설계된 상품을 만들어냈다."},
        {"situation": "학술 게재 전략", "en": "Some researchers engage in a form of publication arbitrage, submitting work with contested findings to journals in disciplines where methodological scrutiny standards are comparatively lenient.", "ko": "일부 연구자들은 일종의 출판 차익 거래에 관여하여, 방법론적 심사 기준이 비교적 관대한 분야의 학술지에 논쟁적 결과물을 담은 연구를 제출한다."},
    ],
    27: [  # attrition
        {"situation": "장기 소송 전략", "en": "Legal scholars criticize litigation strategies based on attrition, whereby well-resourced defendants drag out proceedings to exhaust plaintiffs of limited financial means.", "ko": "법학자들은 자원이 풍부한 피고가 재정 수단이 제한된 원고를 지치게 만들기 위해 소송 절차를 질질 끄는, 소모전에 기반한 소송 전략을 비판한다."},
        {"situation": "기업 인력 관리 문제", "en": "The consulting firm's unsustainably high attrition rate among junior analysts was attributed to a toxic performance culture that prioritized billable hours over professional development.", "ko": "컨설팅 회사 주니어 애널리스트들의 지속 불가능할 정도로 높은 이직률은 전문성 개발보다 청구 가능 시간을 우선시하는 독성 성과 문화에 기인한 것으로 분석되었다."},
        {"situation": "지지자 동원 유지 문제", "en": "Campaign strategists warned that activist attrition between election cycles posed a structural threat to the progressive coalition's long-term organizational capacity.", "ko": "선거 전략가들은 선거 주기 사이의 활동가 이탈이 진보 연합의 장기적 조직 역량에 구조적 위협을 제기한다고 경고했다."},
        {"situation": "전쟁 소모전 분석", "en": "Military historians note that the First World War's Western Front became defined by a strategy of attrition that prioritized the depletion of enemy manpower over territorial conquest.", "ko": "군사 역사학자들은 제1차 세계대전의 서부 전선이 영토 정복보다 적 병력의 소모를 우선시하는 소모전 전략으로 특징지어지게 되었다고 지적한다."},
        {"situation": "언어 소멸 위기 분석", "en": "Linguists documented the gradual attrition of endangered languages, noting that intergenerational transmission had ceased in communities where fewer than a hundred fluent speakers remained.", "ko": "언어학자들은 유창한 화자가 100명 미만으로 남은 공동체에서 세대 간 전달이 중단되었다는 점을 주목하며 위기 언어의 점진적 소멸을 기록했다."},
    ],
    29: [  # austerity
        {"situation": "국가 채무 위기 대응", "en": "The IMF-mandated austerity program required the debtor nation to implement sweeping cuts to public services that disproportionately affected low-income households and the chronically ill.", "ko": "IMF가 의무화한 긴축 프로그램은 채무국이 저소득 가구와 만성 질환자에게 불균형적으로 영향을 미치는 대규모 공공 서비스 삭감을 시행하도록 요구했다."},
        {"situation": "공공 교육 예산 삭감", "en": "Education scholars documented how a decade of fiscal austerity had hollowed out the professional development infrastructure for teachers, with measurable consequences for student achievement.", "ko": "교육 학자들은 10년간의 재정 긴축이 교사의 전문성 개발 인프라를 어떻게 공동화시켰는지, 그리고 이것이 학생 학업 성취에 미치는 측정 가능한 결과를 기록했다."},
        {"situation": "사회적 불평등 심화 연구", "en": "Comparative research across European economies found that countries implementing more stringent austerity measures consistently exhibited greater increases in income inequality and social stratification.", "ko": "유럽 경제들에 대한 비교 연구에서 더 엄격한 긴축 조치를 시행한 국가들이 일관되게 소득 불평등과 사회적 계층화의 더 큰 증가를 보였다는 것이 밝혀졌다."},
        {"situation": "긴축 철학적 비판", "en": "Post-Keynesian economists challenged the theoretical foundations of austerity, arguing that fiscal contraction during periods of economic weakness is self-defeating and empirically refuted by historical evidence.", "ko": "포스트 케인스주의 경제학자들은 긴축의 이론적 토대에 이의를 제기하며, 경제적 취약기의 재정 긴축은 자멸적이며 역사적 증거에 의해 경험적으로 반박된다고 주장했다."},
        {"situation": "지방 정부 예산 제약", "en": "Municipal leaders argued that central government austerity had fundamentally compromised their capacity to maintain public infrastructure while simultaneously managing rising demand for social services.", "ko": "지방 정부 지도자들은 중앙 정부의 긴축이 증가하는 사회 서비스 수요를 관리하면서 동시에 공공 인프라를 유지하는 역량을 근본적으로 훼손했다고 주장했다."},
    ],
    30: [  # autonomy
        {"situation": "의료 윤리 자기 결정권", "en": "Bioethicists emphasize patient autonomy as a foundational principle, requiring clinicians to respect treatment refusals even when medical judgment suggests the decision is contrary to the patient's best interests.", "ko": "생명윤리학자들은 환자 자율성을 근본 원칙으로 강조하며, 의학적 판단에서 그 결정이 환자 최선의 이익에 반하는 경우에도 임상의들이 치료 거부를 존중하도록 요구한다."},
        {"situation": "지역 분권화 정책 논쟁", "en": "Proponents of fiscal decentralization argued that granting regions greater budgetary autonomy would enhance policy responsiveness to local conditions and democratic accountability.", "ko": "재정 분권화 지지자들은 지역에 더 큰 예산 자율성을 부여하면 지역 여건에 대한 정책 반응성과 민주적 책임이 강화될 것이라고 주장했다."},
        {"situation": "AI 자율 시스템 윤리", "en": "The philosophy of autonomous weapons systems raises profound ethical dilemmas about the delegation of lethal decision-making authority to algorithms lacking genuine moral agency.", "ko": "자율 무기 체계의 철학은 진정한 도덕적 행위 능력이 없는 알고리즘에 치명적 의사결정 권한을 위임하는 것에 대한 심오한 윤리적 딜레마를 제기한다."},
        {"situation": "학술 기관 독립성", "en": "The erosion of institutional autonomy in universities, as governments increasingly tie funding to prescribed research agendas, threatens the conditions necessary for genuine intellectual inquiry.", "ko": "정부가 점점 더 자금 지원을 규정된 연구 의제와 연결함에 따라 대학의 제도적 자율성이 침식되고 있으며, 이는 진정한 지적 탐구에 필요한 조건을 위협한다."},
        {"situation": "식민지 탈식민지화 운동", "en": "The demand for political autonomy in colonial territories was articulated not merely as a matter of self-governance but as a prerequisite for cultural survival and economic self-determination.", "ko": "식민지 영토에서의 정치적 자율성 요구는 단순히 자치의 문제로만 표명된 것이 아니라, 문화적 생존과 경제적 자기 결정의 전제 조건으로 표명되었다."},
    ],
    34: [  # candor
        {"situation": "기업 이사회 소통", "en": "The incoming CFO's candor about the company's deteriorating cash position, though initially unsettling, enabled the board to make informed strategic decisions before the liquidity crisis became irreversible.", "ko": "신임 CFO의 회사 현금 상황 악화에 대한 솔직함은 처음에는 불안을 야기했지만, 이사회가 유동성 위기가 돌이킬 수 없게 되기 전에 정보에 입각한 전략적 결정을 내릴 수 있게 해주었다."},
        {"situation": "과학적 불확실성 공개", "en": "Scientific integrity demands candor about the limitations of current evidence, including forthright acknowledgment of methodological weaknesses that may affect the reliability of published findings.", "ko": "과학적 청렴성은 발표된 연구 결과의 신뢰성에 영향을 줄 수 있는 방법론적 약점에 대한 솔직한 인정을 포함하여, 현재 증거의 한계에 대한 솔직함을 요구한다."},
        {"situation": "정치적 실패 인정", "en": "The minister's public candor in acknowledging the policy's unintended consequences, rather than deflecting blame, was widely praised as an exemplar of principled political accountability.", "ko": "책임을 회피하는 대신 정책의 의도치 않은 결과를 인정한 장관의 공개적 솔직함은 원칙 있는 정치적 책임감의 모범으로 널리 칭찬받았다."},
        {"situation": "의료 진단 전달", "en": "Palliative care specialists are trained to communicate terminal diagnoses with candor and compassion, recognizing that patients generally benefit from accurate information about their prognosis.", "ko": "완화 의료 전문가들은 환자들이 일반적으로 예후에 관한 정확한 정보로부터 이익을 얻는다는 것을 인식하며, 말기 진단을 솔직함과 연민으로 전달하도록 훈련받는다."},
        {"situation": "협상 중 신뢰 구축", "en": "In high-stakes diplomatic negotiations, strategic candor—disclosing genuine constraints while withholding tactical information—can paradoxically accelerate agreement by establishing mutual credibility.", "ko": "고위험 외교 협상에서 전술적 정보를 보류하면서 진짜 제약 조건을 공개하는 전략적 솔직함은 역설적으로 상호 신뢰성을 확립함으로써 합의를 가속화할 수 있다."},
    ],
    35: [  # caveat
        {"situation": "투자 위험 고지", "en": "The prospectus included a caveat that past performance of the fund was not indicative of future returns, particularly given the unprecedented volatility of emerging market conditions.", "ko": "투자 설명서에는 특히 신흥 시장 상황의 전례 없는 변동성을 고려할 때, 펀드의 과거 성과가 미래 수익을 나타내는 것은 아니라는 경고가 포함되어 있었다."},
        {"situation": "역학 연구 해석 주의", "en": "The researchers appended a significant caveat to their findings, noting that the observational study design precluded any causal inference from the observed associations.", "ko": "연구자들은 관찰 연구 설계가 관찰된 연관성으로부터 어떠한 인과적 추론도 배제한다고 언급하며, 연구 결과에 중요한 경고 사항을 추가했다."},
        {"situation": "국제 협약 예외 조항", "en": "The treaty's blanket environmental protections were qualified by an important caveat allowing signatory nations to invoke national security exceptions in cases of critical infrastructure development.", "ko": "조약의 포괄적 환경 보호 조항은 서명국들이 중요 인프라 개발의 경우에 국가 안보 예외를 발동할 수 있도록 허용하는 중요한 단서 조항으로 제한되었다."},
        {"situation": "기술 효능 평가 제한", "en": "The meta-analysis endorsed the intervention's effectiveness while including a critical caveat that most supporting trials had been conducted in high-income country contexts that may not generalize globally.", "ko": "메타 분석은 개입의 효과성을 지지했지만, 뒷받침하는 대부분의 임상 시험이 전 세계적으로 일반화되지 않을 수 있는 고소득 국가 맥락에서 수행되었다는 중요한 경고를 포함했다."},
        {"situation": "인공지능 권고 사항 조건", "en": "Engineers attached a formal caveat to the AI system's deployment documentation, specifying conditions under which its recommendations should be overridden by human judgment.", "ko": "엔지니어들은 AI 시스템의 배포 문서에 공식적인 경고 조항을 첨부하여, 인간의 판단이 시스템의 권고 사항을 무시해야 하는 조건을 명시했다."},
    ],
    36: [  # charter
        {"situation": "유엔 설립 원칙", "en": "The United Nations Charter establishes the foundational norms governing relations between sovereign states, including the prohibition on the use of force except in self-defense or pursuant to Security Council authorization.", "ko": "유엔 헌장은 자위 또는 안전보장이사회의 수권에 따른 경우를 제외한 무력 사용 금지를 포함하여 주권 국가 간의 관계를 규율하는 근본 규범을 확립한다."},
        {"situation": "대학 설립 허가", "en": "The institution's royal charter, granted in the seventeenth century, conferred the authority to award degrees and established the constitutional framework that continues to govern its operations.", "ko": "17세기에 부여된 기관의 왕실 특허장은 학위 수여 권한을 부여하고 현재까지 운영을 규율하는 헌법적 체계를 확립했다."},
        {"situation": "인권 지역 협약", "en": "The African Charter on Human and Peoples' Rights is distinctive in its recognition of both individual civil liberties and collective rights of peoples, reflecting the continent's unique historical and political context.", "ko": "아프리카 인권 및 인민권 헌장은 대륙의 독특한 역사적, 정치적 맥락을 반영하여 개인의 시민적 자유와 인민의 집단적 권리를 모두 인정한다는 점에서 독특하다."},
        {"situation": "비영리 단체 설립 목적", "en": "The organization's founding charter prohibited it from engaging in any activities that might be construed as partisan advocacy, thereby preserving its charitable tax status and cross-partisan credibility.", "ko": "조직의 설립 헌장은 편당적 지지 활동으로 해석될 수 있는 어떠한 활동도 금지하여, 자선 세제 혜택과 초당파적 신뢰성을 보전했다."},
        {"situation": "의회 위원회 권한 범위", "en": "The parliamentary select committee's charter defined its investigative remit precisely enough to establish constitutional legitimacy while broad enough to encompass the full scope of the government's alleged misconduct.", "ko": "의회 특별 위원회의 권한 규정은 헌법적 정당성을 확립할 만큼 정확하면서도 정부의 의혹 비위 행위의 전체 범위를 포괄할 만큼 광범위하게 조사 권한을 규정했다."},
    ],
    38: [  # clawback
        {"situation": "부당 이득 회수 정책", "en": "Following the accounting restatement, the board invoked its clawback provision to recover three years of performance bonuses paid to executives based on what proved to be fictitious earnings.", "ko": "회계 재수정 이후, 이사회는 허구로 밝혀진 수익에 기반하여 임원들에게 지급된 3년간의 성과 보너스를 회수하기 위해 환수 조항을 발동했다."},
        {"situation": "정부 보조금 조건 위반", "en": "The federal grant agreement contained an aggressive clawback mechanism requiring recipients to repay all disbursed funds should they fail to maintain the contractually specified employment levels.", "ko": "연방 보조금 계약에는 수령자가 계약에 명시된 고용 수준을 유지하지 못할 경우 지급된 모든 자금을 반환하도록 요구하는 강력한 환수 메커니즘이 포함되어 있었다."},
        {"situation": "세금 혜택 회수", "en": "Tax authorities exercised their clawback powers to recover enterprise zone incentives from a company that had relocated its manufacturing operations offshore within the prohibited five-year window.", "ko": "세무 당국은 금지된 5년 기간 내에 제조 운영을 해외로 이전한 회사로부터 기업 구역 인센티브를 회수하기 위해 환수 권한을 행사했다."},
        {"situation": "구제금융 지원금 조건", "en": "The bailout package incorporated a structured clawback arrangement under which the rescued institution was obligated to return government capital as profitability was restored over a ten-year horizon.", "ko": "구제금융 패키지에는 구제된 기관이 10년 기간에 걸쳐 수익성이 회복됨에 따라 정부 자본을 반환해야 하는 구조화된 환수 약정이 포함되었다."},
        {"situation": "인수합병 후 성과 조항", "en": "The acquisition agreement included an earnout clawback clause allowing the buyer to recover a portion of the consideration if the acquired company's revenues fell below negotiated benchmarks.", "ko": "인수 계약에는 인수한 회사의 수익이 협상된 기준치 아래로 떨어질 경우 매수인이 대금의 일부를 회수할 수 있는 성과 연동 환수 조항이 포함되었다."},
    ],
    42: [  # collateral
        {"situation": "신용 대출 담보 요건", "en": "The bank's credit committee required borrowers to pledge unencumbered real property as collateral before approving the expansion loan, citing elevated counterparty risk in the prevailing market environment.", "ko": "은행의 신용 위원회는 현재 시장 환경에서의 높은 거래 상대방 위험을 이유로 확장 대출을 승인하기 전에 차입자들이 담보권이 없는 부동산을 담보로 제공하도록 요구했다."},
        {"situation": "군사 작전 부수적 피해", "en": "The tribunal examined whether the military planners had adequately weighed the anticipated collateral damage to civilian infrastructure against the legitimate military objectives of the operation.", "ko": "법정은 군사 계획가들이 작전의 정당한 군사적 목표에 비추어 민간 인프라에 대한 예상되는 부수적 피해를 충분히 고려했는지를 검토했다."},
        {"situation": "레포 거래 담보 관리", "en": "Under the repo agreement, government securities served as collateral that could be rehypothecated by the counterparty, creating layers of interconnected credit exposure across the financial system.", "ko": "환매조건부 계약 하에서, 국채는 거래 상대방이 재담보로 설정할 수 있는 담보로 기능하여 금융 시스템 전반에 걸쳐 상호 연결된 신용 노출의 여러 층위를 만들어냈다."},
        {"situation": "파산 절차 자산 회수", "en": "Secured creditors' superior claim to collateral assets in bankruptcy proceedings means they are substantially insulated from losses that can devastate the recovery prospects of unsecured creditors.", "ko": "파산 절차에서 담보 자산에 대한 담보 채권자의 우선적 청구권은 무담보 채권자의 회수 전망을 황폐화시킬 수 있는 손실로부터 그들을 상당히 보호한다는 것을 의미한다."},
        {"situation": "중앙은행 통화 정책 수단", "en": "The central bank expanded the range of eligible collateral for its emergency lending facilities to include corporate bonds, thereby extending liquidity support to a broader segment of the financial sector.", "ko": "중앙은행은 비상 대출 제도의 적격 담보 범위를 회사채를 포함하도록 확대하여, 금융 부문의 더 넓은 부분에 유동성 지원을 확장했다."},
    ],
    43: [  # commencement
        {"situation": "인프라 공사 착공", "en": "The commencement of construction on the high-speed rail corridor was delayed by eighteen months due to unresolved disputes over land acquisition and environmental compliance requirements.", "ko": "고속철도 노선 건설의 착공은 토지 취득과 환경 규정 준수 요건을 둘러싼 미해결 분쟁으로 인해 18개월 지연되었다."},
        {"situation": "법적 소멸 시효 기산점", "en": "The court was asked to determine the precise commencement date of the limitation period, as different interpretations would determine whether the plaintiff's claim was time-barred.", "ko": "원고의 청구가 시효로 인해 차단되는지를 결정하는 데 서로 다른 해석이 영향을 주기 때문에, 법원은 소멸 시효 기산 일자를 정확히 결정해 달라는 요청을 받았다."},
        {"situation": "국제 조약 발효 시기", "en": "The treaty specified that its provisions would enter into force only upon commencement of the ratification process by two-thirds of the signatory states, a threshold not reached for nearly a decade.", "ko": "조약은 서명국의 3분의 2가 비준 절차를 개시해야만 조약 규정이 발효된다고 명시했으며, 이 기준은 거의 10년이 지나서야 달성되었다."},
        {"situation": "파산 절차 개시", "en": "Upon commencement of the insolvency proceedings, an automatic stay took effect, preventing creditors from pursuing individual collection actions against the debtor's estate outside the formal process.", "ko": "파산 절차가 개시되자 자동 정지가 효력을 발휘하여, 채권자들이 공식 절차 외에서 채무자의 재산에 대해 개별 추심 행위를 추진하지 못하도록 했다."},
        {"situation": "임상 시험 시작 요건", "en": "Regulatory approval for commencement of Phase III clinical trials was contingent upon a satisfactory review of the safety data generated in the preceding Phase II studies.", "ko": "3상 임상 시험 착수에 대한 규제 승인은 앞선 2상 연구에서 생성된 안전성 데이터의 만족스러운 검토를 조건으로 했다."},
    ],
    45: [  # commingling
        {"situation": "신탁 자산 혼합 금지", "en": "The trustee was found liable for breach of fiduciary duty after the deliberate commingling of trust assets with personal funds rendered an accurate accounting of beneficiaries' entitlements impossible.", "ko": "수탁자는 신탁 자산과 개인 자금의 의도적 혼합으로 인해 수익자의 권리에 대한 정확한 회계가 불가능해진 후 수탁 의무 위반으로 책임을 인정받았다."},
        {"situation": "변호사 예탁금 분리 의무", "en": "Bar association regulations strictly prohibit the commingling of client trust funds with attorneys' operating accounts, a rule designed to safeguard client assets from exposure to the firm's commercial liabilities.", "ko": "변호사 협회 규정은 의뢰인 신탁 자금과 변호사의 운영 계좌의 혼합을 엄격히 금지하고 있으며, 이 규정은 의뢰인 자산을 사무소의 상업적 부채에 대한 노출로부터 보호하기 위해 설계되었다."},
        {"situation": "투자 회사 자산 분리", "en": "The fund manager's unauthorized commingling of institutional and retail investor assets created an undisclosed conflict of interest that the regulator deemed a fundamental violation of the firm's segregation obligations.", "ko": "펀드 매니저의 무단 기관 투자자 및 개인 투자자 자산 혼합은 미공개 이해 충돌을 야기했으며, 규제 당국은 이를 회사의 자산 분리 의무에 대한 근본적 위반으로 판단했다."},
        {"situation": "법인 자금 사용 규정", "en": "The court's piercing of the corporate veil was justified by evidence of systematic commingling of personal and corporate funds, demonstrating that the shareholder had treated the entity as an alter ego.", "ko": "법원의 법인격 부인은 개인 자금과 법인 자금의 체계적 혼합에 대한 증거에 의해 정당화되었으며, 이는 주주가 법인을 자신의 분신으로 취급했음을 입증했다."},
        {"situation": "국제 자금 세탁 방지", "en": "Anti-money laundering frameworks specifically target the commingling of illicit funds with legitimate revenue streams, as this technique obscures the criminal origin of assets moving through the financial system.", "ko": "자금세탁방지 체계는 이 기법이 금융 시스템을 통해 이동하는 자산의 범죄적 출처를 불분명하게 만들기 때문에, 불법 자금과 합법적 수익 흐름의 혼합을 특별히 표적으로 삼는다."},
    ],
    49: [  # concession
        {"situation": "무역 협상 양보", "en": "The negotiating team was authorized to offer targeted tariff concessions in sensitive agricultural sectors in exchange for expanded market access for domestically produced high-technology goods.", "ko": "협상팀은 국내 생산 첨단 기술 제품에 대한 확대된 시장 접근의 대가로 민감한 농업 부문에서 표적화된 관세 양보를 제공할 권한을 부여받았다."},
        {"situation": "공공 인프라 민간 운영권", "en": "The government awarded a thirty-year concession to a private consortium to finance, build, and operate the international airport under a build-operate-transfer arrangement.", "ko": "정부는 건설-운영-이전 방식으로 국제 공항을 자금 조달, 건설 및 운영하기 위해 민간 컨소시엄에 30년 운영권을 부여했다."},
        {"situation": "노사 협상 타협", "en": "Management's reluctant concession on the issue of flexible working arrangements ultimately proved instrumental in unlocking a comprehensive collective bargaining agreement after months of deadlock.", "ko": "유연 근무 제도 문제에 대한 경영진의 마지못한 양보는 수개월간의 교착 상태 끝에 포괄적인 단체 협약을 이끌어내는 데 결정적으로 기여했다."},
        {"situation": "경쟁법 승인 조건", "en": "Merger clearance was granted subject to structural concessions requiring the combined entity to divest overlapping business units in three regional markets to preserve competitive conditions.", "ko": "합병 승인은 경쟁 조건을 보전하기 위해 합병 법인이 세 개 지역 시장에서 중복 사업 부문을 매각하도록 요구하는 구조적 양보를 조건으로 승인되었다."},
        {"situation": "식민지 독립 협상", "en": "Historical analysis reveals that colonial powers' territorial concessions were frequently strategic calculations designed to preserve economic dominance while satisfying the form, if not the substance, of independence demands.", "ko": "역사적 분석에 따르면 식민 세력의 영토 양보는 독립 요구의 실질이 아닌 형식을 충족시키면서 경제적 지배력을 유지하기 위해 고안된 전략적 계산인 경우가 많았다."},
    ],
    50: [  # conciliation
        {"situation": "노동 분쟁 조정", "en": "The labor ministry appointed an experienced conciliation officer to facilitate structured dialogue between the striking workers and management, with a view to resolving the dispute without recourse to arbitration.", "ko": "노동부는 중재에 호소하지 않고 분쟁을 해결하기 위해 파업 근로자와 경영진 사이의 구조화된 대화를 촉진하기 위해 경험 있는 조정관을 임명했다."},
        {"situation": "국제 인권 분쟁 해결", "en": "The regional human rights commission offered its conciliation services to facilitate a negotiated remedy between the affected community and the state, thereby avoiding protracted adjudication.", "ko": "지역 인권 위원회는 장기간의 재판을 피하기 위해 피해 공동체와 국가 간의 협상된 구제책을 촉진하기 위한 조정 서비스를 제공했다."},
        {"situation": "이혼 및 가족 분쟁", "en": "Family courts increasingly mandate pre-litigation conciliation for custody disputes, recognizing that negotiated agreements tend to produce better long-term outcomes for children than adversarial proceedings.", "ko": "가정 법원은 양육권 분쟁에 대한 소송 전 조정을 점점 더 의무화하고 있으며, 이는 협상된 합의가 대립적 소송보다 아동에게 더 나은 장기적 결과를 낳는 경향이 있다는 것을 인식한 것이다."},
        {"situation": "상업 계약 조기 분쟁 해결", "en": "The parties' voluntary resort to conciliation before initiating formal arbitral proceedings resulted in a settlement that preserved the commercial relationship and avoided years of costly litigation.", "ko": "당사자들이 공식 중재 절차를 시작하기 전에 자발적으로 조정을 활용한 결과, 상업적 관계를 보전하고 수년간의 비용이 많이 드는 소송을 피하는 합의에 이르렀다."},
        {"situation": "다자간 환경 분쟁", "en": "International environmental law provides for conciliation as a mechanism for resolving treaty disputes, offering states a less confrontational alternative to binding adjudication before international tribunals.", "ko": "국제 환경법은 조약 분쟁 해결 메커니즘으로 조정을 규정하고 있으며, 이는 국가들에게 국제 법원에서의 구속력 있는 재판보다 덜 대립적인 대안을 제공한다."},
    ],
}

for word_id, new_exs in new_examples.items():
    if word_id in word_map:
        word_map[word_id]['examples'].extend(new_exs)

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Batch 1 done.")
with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    d2 = json.load(f)
wm2 = {w['id']: w for w in d2['words']}
for wid in sorted(new_examples.keys()):
    print(f"  id={wid} {wm2[wid]['word']}: {len(wm2[wid]['examples'])} examples")
