import json

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

words = data['words']
word_map = {w['id']: w for w in words}

new_examples = {
    51: [  # conglomerate
        {"situation": "반독점 규제 심사", "en": "Antitrust regulators expressed concern that the proposed merger would create a conglomerate with sufficient market power across multiple sectors to engage in anti-competitive cross-subsidization.", "ko": "반독점 규제 당국은 제안된 합병이 여러 부문에 걸쳐 반경쟁적 교차 보조를 수행하기에 충분한 시장 지배력을 갖춘 복합기업을 만들 것이라는 우려를 표명했다."},
        {"situation": "기업 지배구조 비효율성", "en": "Corporate governance scholars have long argued that the conglomerate structure creates principal-agent problems that undermine shareholder value through managerial empire-building and resource misallocation.", "ko": "기업 지배구조 학자들은 오랫동안 복합기업 구조가 경영자의 제국 건설과 자원 오배분을 통해 주주 가치를 훼손하는 주인-대리인 문제를 야기한다고 주장해왔다."},
        {"situation": "신흥 시장 기업 성장", "en": "In many developing economies, conglomerates have historically substituted for absent institutional infrastructure, functioning as internal capital markets in environments where external finance is scarce.", "ko": "많은 개발도상국 경제에서 복합기업들은 역사적으로 부재한 제도적 인프라를 대체하며, 외부 금융이 희소한 환경에서 내부 자본 시장으로 기능해왔다."},
        {"situation": "사모펀드 구조조정", "en": "Private equity firms frequently acquire conglomerates with the explicit intention of breaking them up and divesting non-core units whose value is obscured by the complexity of the combined organization.", "ko": "사모펀드 기업들은 복합 조직의 복잡성으로 가치가 가려진 비핵심 사업부를 분리하고 매각하겠다는 명시적 의도로 복합기업들을 인수하는 경우가 많다."},
        {"situation": "국가 경제 모델 분석", "en": "The South Korean chaebol model demonstrates how state-directed conglomerates can accelerate industrial development under certain institutional conditions while simultaneously creating systemic financial vulnerabilities.", "ko": "한국의 재벌 모델은 국가 주도 복합기업들이 특정 제도적 조건 하에서 어떻게 산업 발전을 가속화하면서 동시에 체계적 금융 취약성을 만들어낼 수 있는지를 보여준다."},
    ],
    55: [  # conveyance
        {"situation": "부동산 권리 이전 절차", "en": "The solicitor prepared a deed of conveyance transferring the registered freehold title from the vendor to the purchaser, subject to the discharge of all existing mortgage obligations.", "ko": "법무사는 기존 모든 모기지 의무의 해제를 조건으로 등록된 단독 소유권을 매도인에서 매수인으로 이전하는 양도 증서를 작성했다."},
        {"situation": "상업 물류 법적 책임", "en": "The bill of lading served as documentary evidence of the conveyance contract, establishing the carrier's liability for the cargo from the port of loading to the final destination.", "ko": "선하증권은 선적항에서 최종 목적지까지 화물에 대한 운송인의 책임을 확립하는 운송 계약의 문서적 증거로 기능했다."},
        {"situation": "신탁 자산 이전", "en": "The conveyance of assets into the discretionary trust required careful legal drafting to ensure that the transfer was irrevocable and insulated from future claims by the settlor's creditors.", "ko": "재량 신탁으로의 자산 양도는 이전이 취소 불가능하며 신탁 설정자의 미래 채권자들의 청구로부터 차단되도록 보장하기 위해 신중한 법적 문서 작성이 필요했다."},
        {"situation": "공공 토지 수용 보상", "en": "The compulsory conveyance of private land for public infrastructure purposes required fair compensation to be determined through an independent valuation process overseen by the land tribunal.", "ko": "공공 인프라 목적을 위한 민간 토지의 강제 양도에는 토지 심판소가 감독하는 독립적 평가 과정을 통해 결정된 공정한 보상이 요구되었다."},
        {"situation": "전자 데이터 권리 이전", "en": "Legal scholars have debated whether the conveyance of digital assets, including cryptocurrency holdings, requires entirely new legislative frameworks or can be accommodated within existing property transfer laws.", "ko": "법학자들은 암호화폐 보유를 포함한 디지털 자산의 양도가 완전히 새로운 입법 체계를 필요로 하는지, 아니면 기존 재산 이전법 내에서 수용될 수 있는지를 논의해왔다."},
    ],
    57: [  # counterpart
        {"situation": "외교 고위급 회담", "en": "The foreign secretary met with her Chinese counterpart to discuss the framework for resuming bilateral trade negotiations suspended during the previous diplomatic dispute.", "ko": "외무장관은 이전 외교 분쟁 중 중단된 양자 무역 협상 재개를 위한 체계를 논의하기 위해 중국 측 상대방을 만났다."},
        {"situation": "비교 법학 연구", "en": "The legal doctrine finds its closest counterpart in civil law jurisdictions' concept of abuse of right, though the two traditions reach analogous outcomes through distinct theoretical pathways.", "ko": "이 법적 원칙은 대륙법계 관할권의 권리 남용 개념에서 가장 유사한 상대를 찾을 수 있지만, 두 전통은 서로 다른 이론적 경로를 통해 유사한 결과에 도달한다."},
        {"situation": "국제 규제 조화", "en": "Regulatory harmonization efforts were complicated by the fact that the EU's data protection authority had no direct institutional counterpart in the United States with comparable statutory powers.", "ko": "EU의 데이터 보호 당국이 미국에 비슷한 법적 권한을 가진 직접적인 기관상 상대방이 없다는 사실로 인해 규제 조화 노력이 복잡해졌다."},
        {"situation": "학제간 방법론 비교", "en": "Ethnographic methods in sociology find their closest counterpart in qualitative fieldwork traditions in anthropology, yet the disciplinary assumptions shaping each approach differ in consequential ways.", "ko": "사회학의 민족지학적 방법은 인류학의 질적 현장 연구 전통에서 가장 유사한 상대를 찾을 수 있지만, 각 접근법을 형성하는 학문적 가정은 중요한 방식에서 차이가 있다."},
        {"situation": "계약서 서명 사본", "en": "Each party retained a signed counterpart of the agreement, both copies being equally authentic and legally binding upon their respective organizations from the date of execution.", "ko": "각 당사자는 계약서의 서명된 사본 하나씩을 보유했으며, 두 사본 모두 체결일로부터 해당 기관에 동등하게 정본이자 법적 구속력을 갖는다."},
    ],
    58: [  # creditor
        {"situation": "파산 우선순위 결정", "en": "In the distribution of the insolvent estate, secured creditors holding registered charges over specific assets received preferential treatment over both preferential and unsecured creditors.", "ko": "지급 불능 재산의 분배에서, 특정 자산에 대해 등록된 담보권을 보유한 담보 채권자들은 우선 채권자와 무담보 채권자 모두보다 우선적 대우를 받았다."},
        {"situation": "국가 부채 재조정 협상", "en": "Sovereign debt restructuring negotiations require achieving sufficient creditor participation to prevent holdout creditors from disrupting the terms agreed upon by the majority.", "ko": "국가 채무 재조정 협상은 소수 채권자들이 다수가 합의한 조건을 방해하지 못하도록 충분한 채권자 참여를 달성해야 한다."},
        {"situation": "기업 구조조정 채무 조정", "en": "The court-supervised restructuring plan required creditors holding subordinated debt to accept significant haircuts as a condition for the enterprise's continued viability.", "ko": "법원이 감독하는 구조조정 계획은 후순위 채무를 보유한 채권자들이 기업의 지속적인 생존 가능성의 조건으로 상당한 원금 삭감을 수용하도록 요구했다."},
        {"situation": "소비자 금융 보호", "en": "Consumer protection legislation increasingly restricts creditors' ability to engage in predatory collection practices that disproportionately harm financially vulnerable debtors.", "ko": "소비자 보호 법률은 재정적으로 취약한 채무자에게 불균형적으로 해를 끼치는 약탈적 추심 관행에 관여하는 채권자의 능력을 점점 더 제한하고 있다."},
        {"situation": "신용 시장 정보 비대칭", "en": "Creditors in imperfect information environments rely heavily on credit scoring models and collateral requirements to mitigate the adverse selection problems inherent in lending markets.", "ko": "불완전한 정보 환경의 채권자들은 대출 시장에 내재된 역선택 문제를 완화하기 위해 신용 평가 모델과 담보 요건에 크게 의존한다."},
    ],
    61: [  # custodian
        {"situation": "박물관 문화재 관리", "en": "The museum's role as custodian of indigenous cultural artifacts has come under sustained scrutiny, with originating communities demanding repatriation of objects acquired during the colonial period.", "ko": "박물관의 원주민 문화 유물 관리자 역할은 지속적인 검토를 받아왔으며, 원산지 공동체들은 식민지 시기에 취득된 물건들의 반환을 요구하고 있다."},
        {"situation": "환경 보전 국제 책임", "en": "International environmental law frames nation-states as custodians of natural resources within their territories, imposing obligations not merely to sovereign proprietors but to global ecological stewardship.", "ko": "국제 환경법은 국민국가들을 자국 영토 내 천연자원의 관리자로 규정하며, 주권적 소유자뿐만 아니라 전 지구적 생태적 청지기 의무를 부과한다."},
        {"situation": "아동 보호 책임", "en": "The state assumes the role of custodian for children removed from parental care, bearing corresponding obligations to provide appropriate welfare, education, and psychological support.", "ko": "국가는 부모의 보호에서 분리된 아동의 관리자 역할을 맡으며, 적절한 복지, 교육 및 심리적 지원을 제공해야 할 해당 의무를 진다."},
        {"situation": "금융 자산 수탁 관리", "en": "The investment manager's fiduciary duties as custodian of pension assets require it to prioritize beneficiaries' long-term financial interests above all other commercial considerations.", "ko": "연금 자산의 수탁자로서 투자 매니저의 수탁 의무는 다른 모든 상업적 고려 사항보다 수익자의 장기적 재정 이익을 우선시하도록 요구한다."},
        {"situation": "디지털 데이터 보관 책임", "en": "Archival institutions acting as custodians of digital heritage face unprecedented challenges in preserving the long-term accessibility and authenticity of born-digital materials.", "ko": "디지털 유산의 관리자로서 행동하는 기록 기관들은 디지털 기반 자료의 장기적 접근성과 진본성을 보전하는 데 있어 전례 없는 도전에 직면해 있다."},
    ],
    62: [  # damages
        {"situation": "지적재산권 침해 소송", "en": "The court awarded punitive damages that substantially exceeded the plaintiff's actual losses, sending a clear deterrent message to the industry regarding the deliberate infringement of registered trademarks.", "ko": "법원은 원고의 실제 손실을 상당히 초과하는 징벌적 손해배상을 판결하여, 등록 상표의 의도적 침해에 관해 업계에 명확한 억제 메시지를 보냈다."},
        {"situation": "기후 변화 소송 책임", "en": "Climate litigation has increasingly sought to establish a causal nexus between a defendant corporation's historical emissions and quantifiable damages suffered by communities exposed to intensified natural disasters.", "ko": "기후 소송은 피고 기업의 역사적 배출량과 강화된 자연재해에 노출된 공동체가 입은 정량화 가능한 손해 사이의 인과 관계를 확립하려는 시도를 점점 더 늘리고 있다."},
        {"situation": "의료 과실 보상", "en": "Courts calculating damages in medical malpractice cases must account not only for past economic losses but also for projected future earnings foregone as a result of the negligent treatment.", "ko": "의료 과실 사건에서 손해배상을 산정하는 법원은 과거 경제적 손실뿐만 아니라 부주의한 치료의 결과로 포기된 예상 미래 수익도 고려해야 한다."},
        {"situation": "계약 위반 보상 원칙", "en": "The fundamental principle of compensatory damages in contract law aims to place the innocent party in the position it would have occupied had the breaching party performed its obligations.", "ko": "계약법에서 보상적 손해배상의 기본 원칙은 위반 당사자가 의무를 이행했다면 무고한 당사자가 처해 있었을 지위에 그 당사자를 놓으려는 것을 목표로 한다."},
        {"situation": "환경 복원 비용 청구", "en": "Environmental damages awarded against the mining company encompassed not only remediation costs but also compensation for the permanent loss of ecosystem services that the polluted watershed had previously provided.", "ko": "광업 회사에 부과된 환경 손해배상은 복원 비용뿐만 아니라 오염된 유역이 이전에 제공했던 생태계 서비스의 영구적 손실에 대한 보상도 포함했다."},
    ],
    63: [  # deadlock
        {"situation": "의회 예산 협상 교착", "en": "The budget deadlock between the executive and legislature precipitated a partial government shutdown, suspending non-essential federal services and disrupting thousands of public sector workers.", "ko": "행정부와 입법부 간의 예산 교착은 부분적인 정부 폐쇄를 초래하여 비필수 연방 서비스가 중단되고 수천 명의 공공 부문 근로자들이 혼란을 겪었다."},
        {"situation": "이사회 결의 무효", "en": "The board's articles of association included a casting vote mechanism specifically designed to resolve deadlock situations where the shareholders were equally divided on a fundamental corporate decision.", "ko": "이사회의 정관에는 주주들이 기본적인 기업 결정에 대해 동등하게 분열된 교착 상황을 해결하기 위해 특별히 고안된 결정투표 메커니즘이 포함되어 있었다."},
        {"situation": "국제 기후 협약 협상", "en": "The negotiating deadlock at the climate summit was broken only when the developed nations agreed to establish a new financial mechanism to compensate developing countries for loss and damage.", "ko": "기후 정상회담의 협상 교착은 선진국들이 개발도상국에 손실과 피해를 보상하기 위한 새로운 금융 메커니즘 설립에 동의하고 나서야 타개되었다."},
        {"situation": "노사 단체교섭 결렬", "en": "The industrial deadlock persisted despite three rounds of mediation, ultimately forcing the arbitration board to impose a binding settlement on both parties under emergency labor legislation.", "ko": "세 차례의 조정에도 불구하고 노사 교착 상태가 지속되어, 결국 중재 위원회가 긴급 노동 법률에 따라 양 당사자에게 구속력 있는 합의를 강제하게 되었다."},
        {"situation": "연립 정부 구성 실패", "en": "Constitutional scholars warned that the persistent coalition deadlock, if unresolved within the prescribed timeframe, would trigger mandatory fresh elections under the parliamentary system's failsafe provisions.", "ko": "헌법 학자들은 지속적인 연립 정부 구성 교착 상태가 규정된 기간 내에 해결되지 않을 경우 의원 내각제의 안전 조항에 따라 새 선거를 강제할 것이라고 경고했다."},
    ],
    64: [  # debenture
        {"situation": "기업 장기 자금 조달", "en": "The corporation issued unsecured debentures carrying a fixed coupon rate to institutional investors seeking predictable income streams within a diversified fixed-income portfolio.", "ko": "해당 기업은 다양화된 채권 포트폴리오 내에서 예측 가능한 소득 흐름을 추구하는 기관 투자자들을 대상으로 고정 이표율의 무담보 사채를 발행했다."},
        {"situation": "담보부 사채 우선권", "en": "Debenture holders secured by a floating charge over the company's assets had priority over ordinary unsecured creditors but ranked below fixed charge holders in the event of insolvency.", "ko": "회사 자산에 대한 유동 담보로 확보된 사채 보유자들은 일반 무담보 채권자들보다 우선권을 가졌지만, 지급 불능 시에는 고정 담보 보유자들보다 후순위였다."},
        {"situation": "전환 사채 발행", "en": "The startup issued convertible debentures that could be converted into equity at the holder's discretion upon the occurrence of a qualifying financing round above a specified valuation threshold.", "ko": "스타트업은 지정된 기업 가치 기준치를 초과하는 적격 자금 조달 라운드 발생 시 보유자의 재량으로 주식으로 전환할 수 있는 전환 사채를 발행했다."},
        {"situation": "정부 인프라 채권 발행", "en": "Municipal authorities relied on revenue debentures backed by projected toll collections rather than general tax revenues to finance the construction of the new bridge without encumbering the city's broader fiscal position.", "ko": "지방 당국은 도시의 광범위한 재정 상황을 부담하지 않고 새 교량 건설 자금을 조달하기 위해 일반 세수 대신 예상 통행료 수입을 담보로 한 수익 사채에 의존했다."},
        {"situation": "채권 시장 신용 평가", "en": "Rating agencies downgraded the company's outstanding debentures to below investment grade following the disclosure of undisclosed contingent liabilities that materially altered the perceived risk profile.", "ko": "신용 평가 기관들은 인지된 위험 프로파일을 실질적으로 변경한 미공개 우발 부채의 공개에 따라 회사의 미상환 사채를 투자 등급 이하로 강등했다."},
    ],
    65: [  # declaration
        {"situation": "주권 독립 선언", "en": "The declaration of independence not only announced the colony's separation from imperial rule but articulated a novel theory of legitimate governance grounded in popular sovereignty and natural rights.", "ko": "독립 선언문은 식민지의 제국 통치로부터의 분리를 공표했을 뿐만 아니라, 민주적 주권과 자연권에 근거한 새로운 정당한 통치 이론을 표명했다."},
        {"situation": "국제 인권 선언", "en": "Although lacking binding legal force, the Universal Declaration of Human Rights has achieved normative authority as a foundational reference point for subsequent international human rights instruments.", "ko": "세계 인권 선언은 구속력 있는 법적 효력은 없지만, 후속 국제 인권 문서들의 근본적 참조점으로서 규범적 권위를 획득했다."},
        {"situation": "세관 신고 의무", "en": "Failure to make an accurate customs declaration regarding the value and origin of imported goods constitutes a criminal offence subject to substantial fines and potential forfeiture of the goods.", "ko": "수입 물품의 가치와 원산지에 관한 정확한 세관 신고를 하지 않는 것은 상당한 벌금과 잠재적 물품 몰수의 대상이 되는 형사 범죄를 구성한다."},
        {"situation": "환경 위기 선언", "en": "Parliamentary declaration of a climate emergency, while primarily symbolic, created political momentum for accelerated legislative action on emissions reduction targets and renewable energy transition.", "ko": "의회의 기후 비상 선언은 주로 상징적이었지만, 배출 감소 목표와 재생 에너지 전환에 관한 입법 행동을 가속화하는 정치적 추진력을 만들었다."},
        {"situation": "법원 확인 판결", "en": "The claimant sought a declaration from the court that the impugned clause in the standard form contract was unfair and therefore unenforceable under consumer protection legislation.", "ko": "청구인은 표준 형식 계약의 문제가 된 조항이 불공정하여 소비자 보호 법률에 따라 집행 불가능하다는 확인 판결을 법원에 구했다."},
    ],
    66: [  # defeasance
        {"situation": "채권 조기 상환 구조", "en": "The borrower structured a legal defeasance by placing government securities in escrow sufficient to service all future debt obligations, effectively removing the loan from the balance sheet.", "ko": "차입자는 미래의 모든 채무 의무를 이행하기에 충분한 국채를 에스크로에 예치하는 법적 채무 소멸 구조를 설계하여, 사실상 대출을 대차대조표에서 제거했다."},
        {"situation": "모기지 담보 해제", "en": "Upon full repayment of the mortgage, the lender executed a deed of defeasance that formally discharged the security interest and restored unencumbered title to the property owner.", "ko": "모기지 완전 상환 시, 대출자는 담보권을 공식적으로 해제하고 재산 소유자에게 담보권 없는 소유권을 회복시키는 채무 소멸 증서를 작성했다."},
        {"situation": "공공 채권 만기 전 소멸", "en": "The municipality utilized a cash defeasance to retire outstanding general obligation bonds before their scheduled maturity, taking advantage of the prevailing low interest rate environment to reduce long-term debt costs.", "ko": "지방자치단체는 장기 부채 비용을 줄이기 위해 지배적인 저금리 환경을 활용하여, 예정된 만기 전에 미상환 일반 의무 채권을 상환하기 위한 현금 채무 소멸을 활용했다."},
        {"situation": "조건부 소유권 이전", "en": "Historically, fee simple defeasible estates allowed landowners to transfer property while retaining the right of re-entry should the grantee violate specified conditions attached to the conveyance.", "ko": "역사적으로 조건부 단순 소유권 부동산은 토지 소유자가 양수인이 양도에 첨부된 특정 조건을 위반할 경우 재진입권을 유보하면서 재산을 이전할 수 있게 해주었다."},
        {"situation": "파생상품 계약 소멸 조항", "en": "The swap agreement incorporated a defeasance clause that terminated all outstanding obligations between the parties in the event that either counterparty experienced a credit rating downgrade below investment grade.", "ko": "스왑 계약에는 어느 한 거래 상대방이 투자 등급 미만으로 신용 등급 강등을 경험하는 경우 당사자 간의 모든 미결제 의무를 종료하는 채무 소멸 조항이 포함되어 있었다."},
    ],
    67: [  # deliberation
        {"situation": "배심원 평결 절차", "en": "The judge instructed the jury that its deliberations must be conducted in absolute secrecy, with each member approaching the evidence impartially and setting aside any pre-existing biases.", "ko": "판사는 배심원들에게 각 구성원이 증거에 공정하게 접근하고 기존의 편견을 배제하면서, 평의가 절대적인 비밀로 진행되어야 한다고 지시했다."},
        {"situation": "정책 입안 숙의 과정", "en": "Deliberative democracy theorists argue that the legitimacy of policy outcomes depends not merely on majority support but on the quality of the reasoning process through which decisions are reached.", "ko": "숙의 민주주의 이론가들은 정책 결과의 정당성이 단순히 다수결 지지에만 의존하는 것이 아니라 결정이 도달되는 추론 과정의 질에도 의존한다고 주장한다."},
        {"situation": "윤리 위원회 검토", "en": "The bioethics committee's deliberations on gene editing research spanned twelve months and involved extensive consultation with patient advocacy groups, scientists, and legal scholars before issuing its recommendations.", "ko": "유전자 편집 연구에 대한 생명윤리위원회의 숙의는 12개월에 걸쳐 진행되었으며, 권고안을 발표하기 전에 환자 옹호 단체, 과학자, 법학자들과의 광범위한 협의를 포함했다."},
        {"situation": "국제 재판소 판결", "en": "The International Court of Justice's extended deliberation in this landmark case reflected both the complexity of the contested jurisdictional issues and the Court's determination to produce a definitive legal analysis.", "ko": "이 획기적 사건에서 국제사법재판소의 장기간 심의는 다투어지는 관할권 문제의 복잡성과 확정적인 법적 분석을 생산하려는 법원의 결의를 모두 반영했다."},
        {"situation": "기업 전략 의사 결정", "en": "After months of careful deliberation, the board concluded that the strategic risks of entering the highly competitive Chinese market outweighed the potential long-term revenue gains.", "ko": "수개월간의 신중한 숙의 끝에, 이사회는 경쟁이 치열한 중국 시장에 진입하는 전략적 위험이 잠재적 장기 수익 이익을 능가한다는 결론을 내렸다."},
    ],
    69: [  # delinquency
        {"situation": "채권 포트폴리오 위험 관리", "en": "The bank's risk management division monitored delinquency rates across its mortgage portfolio as a leading indicator of potential credit losses that would require provisioning in the quarterly accounts.", "ko": "은행의 위험 관리 부서는 분기 결산에서 충당금 적립이 필요한 잠재적 신용 손실의 선행 지표로서 모기지 포트폴리오 전반의 연체율을 모니터링했다."},
        {"situation": "청소년 범죄 사회적 원인", "en": "Criminological research consistently demonstrates that juvenile delinquency is strongly correlated with structural factors including poverty, educational exclusion, and the absence of stable family environments.", "ko": "범죄학 연구는 청소년 비행이 빈곤, 교육적 배제, 안정적인 가정 환경의 부재를 포함한 구조적 요인들과 강하게 상관관계가 있음을 일관되게 보여준다."},
        {"situation": "세금 체납 징수 정책", "en": "The revenue authority's targeted enforcement campaign against serial tax delinquency resulted in the collection of billions in previously uncollected obligations from high-net-worth non-compliant individuals.", "ko": "상습적 세금 체납에 대한 세무 당국의 표적 집행 캠페인은 고자산 비준수 개인들로부터 이전에 징수되지 않은 수십억의 의무액을 징수하는 결과를 낳았다."},
        {"situation": "사회 안전망 부재와 체납", "en": "Social policy researchers found that mortgage delinquency rates spiked dramatically among lower-income homeowners following the withdrawal of pandemic-era forbearance programs without adequate replacement support mechanisms.", "ko": "사회 정책 연구자들은 적절한 대체 지원 메커니즘 없이 팬데믹 시기 상환 유예 프로그램이 철회된 후 저소득 주택 소유자들 사이에서 모기지 연체율이 급격히 증가했다는 것을 발견했다."},
        {"situation": "공공 기관 서비스 요금 체납", "en": "The utility regulator mandated that service providers establish structured repayment programs for residential customers in arrears rather than resorting to immediate disconnection, recognizing the social consequences of delinquency-driven service interruption.", "ko": "공익 서비스 규제 당국은 연체 유발 서비스 중단의 사회적 결과를 인식하며, 서비스 제공자들이 즉각적인 연결 해제에 의존하는 대신 연체 중인 주거용 고객을 위한 구조화된 상환 프로그램을 수립하도록 의무화했다."},
    ],
    70: [  # demise
        {"situation": "전통 산업의 쇠락", "en": "Economic historians trace the demise of the British textile industry to a confluence of factors including technological lag, inadequate capital reinvestment, and the competitive emergence of low-cost producers in Asia.", "ko": "경제 역사학자들은 영국 섬유 산업의 쇠락을 기술적 지체, 불충분한 자본 재투자, 그리고 아시아 저비용 생산자들의 경쟁적 부상을 포함한 복합적 요인들의 결합에서 추적한다."},
        {"situation": "정치 체제 붕괴 분석", "en": "Political scientists attribute the demise of the Weimar Republic not solely to economic crisis but to structural deficiencies in constitutional design that prevented effective governmental formation.", "ko": "정치학자들은 바이마르 공화국의 붕괴를 단순히 경제 위기 때문만이 아니라 효과적인 정부 구성을 가로막은 헌법 설계의 구조적 결함 때문이기도 하다고 분석한다."},
        {"situation": "저널리즘 위기 연구", "en": "Media scholars have extensively documented the demise of local investigative journalism, identifying the collapse of print advertising revenue as the proximate cause of newsroom closures across the country.", "ko": "미디어 학자들은 지역 탐사 저널리즘의 쇠락을 광범위하게 기록하며, 전국 뉴스룸 폐쇄의 근본 원인으로 인쇄 광고 수입의 붕괴를 지목했다."},
        {"situation": "임차권 종료 법적 해석", "en": "The law of landlord and tenant distinguishes between the natural demise of a tenancy at the expiry of a fixed term and its premature termination through forfeiture or surrender.", "ko": "집주인-세입자 법은 고정 기간 만료 시 임차권의 자연적 종료와 몰수 또는 포기를 통한 조기 종료를 구별한다."},
        {"situation": "철학적 죽음 개념 분석", "en": "Philosophers in the Epicurean tradition argue that the demise of the self presents no rational ground for fear, as the experience of non-existence is by definition unavailable to the subject who has ceased to be.", "ko": "에피쿠로스 전통의 철학자들은 자아의 소멸이 두려움의 합리적 근거를 제시하지 않는다고 주장하는데, 이는 비존재의 경험이 정의상 존재하기를 멈춘 주체에게는 가용하지 않기 때문이다."},
    ],
    71: [  # demurrage
        {"situation": "선적 지연 비용 청구", "en": "The charterer incurred substantial demurrage charges after labor disputes at the loading port delayed the vessel's departure by eleven days beyond the agreed laytime.", "ko": "용선자는 선적항의 노동 분쟁으로 인해 선박의 출항이 합의된 정박 허용 기간을 11일 초과하여 지연된 후 상당한 체박료 청구를 받았다."},
        {"situation": "탱크 용량 초과 보관료", "en": "The oil trader faced demurrage claims from the tanker owner after crude oil deliveries were halted at the refinery due to a storage tank overflow that prevented the vessel from discharging its cargo.", "ko": "저장 탱크 초과 용량으로 인해 선박이 화물을 하역할 수 없어 정유소에서 원유 인도가 중단된 후, 석유 거래상은 탱커 소유자로부터 체박료 청구를 받았다."},
        {"situation": "컨테이너 반환 지연", "en": "Port congestion resulted in widespread demurrage and detention charges as importers were unable to collect and return empty containers within the carrier's free time allowances.", "ko": "항만 혼잡으로 인해 수입업자들이 운송사의 무료 기간 내에 빈 컨테이너를 수거하고 반환할 수 없게 되어 광범위한 체박료 및 억류료가 발생했다."},
        {"situation": "철도 화차 반환 지연", "en": "The shipper disputed the railroad's demurrage calculations, arguing that delays in returning freight cars were attributable to the carrier's own yard congestion rather than any failure on the shipper's part.", "ko": "화주는 화차 반환 지연이 화주 측의 어떠한 과실이 아니라 운송사 자체의 조차장 혼잡에 기인한다고 주장하며 철도의 체박료 계산에 이의를 제기했다."},
        {"situation": "국제 해운 계약 분쟁", "en": "The arbitral tribunal apportioned demurrage liability between the parties after determining that both the vessel's mechanical defect and the charterer's late nomination of the loading berth had contributed to the overall delay.", "ko": "중재 법원은 선박의 기계적 결함과 용선자의 선적 선석 지연 지정이 모두 전반적 지연에 기여했다고 판단한 후, 당사자들 간의 체박료 책임을 배분했다."},
    ],
    72: [  # depository
        {"situation": "중앙 증권 예탁 기관", "en": "Central securities depositories serve as the backbone of modern financial infrastructure, maintaining electronic records of securities ownership and facilitating the settlement of transactions with systemic reliability.", "ko": "중앙 증권 예탁 기관은 현대 금융 인프라의 근간으로, 증권 소유권의 전자 기록을 유지하고 시스템적 신뢰성으로 거래 결제를 촉진한다."},
        {"situation": "은행 예금 보호 시스템", "en": "The nation's depository insurance framework guarantees eligible customer deposits up to a specified threshold, providing systemic confidence in the banking sector while limiting moral hazard.", "ko": "국가의 예금 보험 체계는 도덕적 해이를 제한하면서 은행 부문에 대한 체계적 신뢰를 제공하기 위해 적격 고객 예금을 특정 기준치까지 보장한다."},
        {"situation": "고문서 디지털 보존", "en": "The national archive functions as a depository for government records of permanent historical value, ensuring their preservation, authentication, and systematic accessibility to researchers.", "ko": "국가 기록원은 영구적 역사적 가치를 지닌 정부 기록의 보관 기관으로 기능하여, 연구자들에게 그것들의 보존, 진본 확인, 체계적 접근성을 보장한다."},
        {"situation": "핵물질 국제 관리", "en": "The proposal for an international depository for spent nuclear fuel sought to address proliferation risks by centralizing storage under multilateral oversight rather than leaving the material in multiple national facilities.", "ko": "사용 후 핵연료를 위한 국제 저장소 제안은 핵물질을 여러 국가 시설에 두는 대신 다자간 감독 하에 집중 보관함으로써 확산 위험을 해결하고자 했다."},
        {"situation": "공증 문서 보관 체계", "en": "Legal depositories for notarized documents provide a trusted third-party custodial infrastructure that ensures the authenticity and retrievability of executed instruments decades after their creation.", "ko": "공증 문서를 위한 법적 보관소는 작성 수십 년 후에도 실행된 문서의 진본성과 검색 가능성을 보장하는 신뢰할 수 있는 제3자 수탁 인프라를 제공한다."},
    ],
    74: [  # depreciation
        {"situation": "세금 공제 자산 상각", "en": "Accelerated depreciation allowances provided under the tax code incentivized capital investment by enabling companies to deduct the cost of qualifying assets more rapidly than their actual economic wear.", "ko": "세법에서 제공하는 가속 감가상각 공제는 기업들이 적격 자산의 비용을 실제 경제적 마모보다 더 빠르게 공제할 수 있게 함으로써 자본 투자를 장려했다."},
        {"situation": "회계 기준 자산 평가", "en": "The straight-line method of depreciation distributes the cost of a tangible asset evenly across its estimated useful life, providing a consistent expense recognition pattern for financial reporting purposes.", "ko": "정액법 감가상각 방식은 유형 자산의 비용을 추정 내용연수에 걸쳐 균등하게 배분하여, 재무 보고 목적을 위한 일관된 비용 인식 패턴을 제공한다."},
        {"situation": "통화 가치 하락 분석", "en": "The sharp depreciation of the domestic currency following the central bank's unexpected rate cut exacerbated inflationary pressures by increasing the cost of imported energy and raw materials.", "ko": "중앙은행의 예상치 못한 금리 인하에 따른 국내 통화의 급격한 가치 하락은 수입 에너지와 원자재 비용을 증가시켜 인플레이션 압박을 악화시켰다."},
        {"situation": "부동산 가치 평가 방법", "en": "Appraisers applying the cost approach to commercial property valuation must carefully estimate depreciation from all causes, including physical deterioration, functional obsolescence, and external economic factors.", "ko": "상업용 부동산 평가에 원가 접근법을 적용하는 감정사들은 물리적 노후화, 기능적 진부화, 외부 경제적 요인을 포함한 모든 원인으로부터의 감가상각을 신중하게 추정해야 한다."},
        {"situation": "지속 가능 경영 자산 전략", "en": "Sustainability-conscious investors challenge traditional depreciation schedules that fail to account for the stranded asset risks facing fossil fuel infrastructure as the energy transition accelerates.", "ko": "지속 가능성을 의식하는 투자자들은 에너지 전환이 가속화됨에 따라 화석 연료 인프라가 직면한 좌초 자산 위험을 반영하지 못하는 전통적 감가상각 일정에 이의를 제기한다."},
    ],
    75: [  # deregulation
        {"situation": "에너지 시장 자유화", "en": "The deregulation of electricity markets in the 1990s was premised on the theory that competition would lower prices for consumers, a prediction that proved accurate in some jurisdictions but catastrophically wrong in others.", "ko": "1990년대 전력 시장 규제 완화는 경쟁이 소비자 가격을 낮출 것이라는 이론에 근거했는데, 이 예측은 일부 관할권에서는 정확했지만 다른 곳에서는 치명적으로 틀렸다."},
        {"situation": "금융 규제 완화 위기", "en": "Post-crisis analyses converged on the conclusion that financial deregulation throughout the 1990s had systematically eroded the safeguards necessary to prevent the kind of systemic risk accumulation that precipitated the 2008 collapse.", "ko": "위기 후 분석들은 1990년대 내내 진행된 금융 규제 완화가 2008년 붕괴를 촉발한 종류의 체계적 위험 축적을 방지하는 데 필요한 안전장치를 체계적으로 침식했다는 결론으로 수렴했다."},
        {"situation": "항공 운송 경쟁 확대", "en": "Airline deregulation fundamentally restructured the aviation industry, enabling low-cost carriers to compete with legacy airlines and dramatically expanding access to air travel for middle-income populations.", "ko": "항공 규제 완화는 항공 산업을 근본적으로 재편하여 저가 항공사들이 기존 항공사들과 경쟁할 수 있게 하고 중소득층 인구의 항공 여행 접근성을 크게 확대했다."},
        {"situation": "노동 시장 유연화 정책", "en": "Labor market deregulation proponents contend that reducing employment protection legislation lowers structural unemployment by reducing firms' reluctance to hire workers they may subsequently find difficult to dismiss.", "ko": "노동 시장 규제 완화 지지자들은 고용 보호 법률을 줄이는 것이 기업들이 이후 해고하기 어렵다고 생각할 수 있는 근로자 채용을 꺼리는 것을 줄임으로써 구조적 실업을 낮춘다고 주장한다."},
        {"situation": "통신 시장 개방 효과", "en": "The deregulation of telecommunications markets broke up incumbent monopolies and catalyzed rapid infrastructure investment and innovation, though critics note that market concentration has subsequently re-emerged in many countries.", "ko": "통신 시장의 규제 완화는 기존 독점을 해체하고 급속한 인프라 투자와 혁신을 촉진했지만, 비평가들은 많은 국가에서 시장 집중이 이후 다시 나타났다고 지적한다."},
    ],
    76: [  # derivative
        {"situation": "위험 헤지 금융 상품", "en": "Airlines routinely use fuel price derivatives to hedge against oil price volatility, locking in future costs and providing greater certainty for long-term capital planning and fleet expansion decisions.", "ko": "항공사들은 일상적으로 연료 가격 파생상품을 사용하여 유가 변동성을 헤지하며, 미래 비용을 고정하고 장기 자본 계획 및 기단 확장 결정에 더 큰 확실성을 제공한다."},
        {"situation": "2008 금융 위기 원인", "en": "The opacity and complexity of derivative instruments linked to sub-prime mortgages played a central role in the propagation of the 2008 financial crisis across interconnected global banking systems.", "ko": "서브프라임 모기지와 연결된 파생상품의 불투명성과 복잡성은 2008년 금융 위기가 상호 연결된 글로벌 은행 시스템 전반에 전파되는 데 핵심적인 역할을 했다."},
        {"situation": "농산물 가격 안정화", "en": "Agricultural commodity derivatives allow farmers to lock in future selling prices and food processors to secure predictable input costs, thereby reducing the financial vulnerability of participants on both sides of the production chain.", "ko": "농산물 파생상품은 농부들이 미래 판매 가격을 고정하고 식품 가공업체들이 예측 가능한 투입 비용을 확보할 수 있게 하여, 생산 사슬 양쪽 참여자들의 재정적 취약성을 줄인다."},
        {"situation": "규제 감독 강화 논쟁", "en": "Policymakers debated whether to mandate central clearing of standardized derivatives through regulated exchanges, aiming to enhance market transparency and reduce counterparty credit risk.", "ko": "정책 입안자들은 시장 투명성을 향상시키고 거래 상대방 신용 위험을 줄이기 위해 규제된 거래소를 통해 표준화된 파생상품의 중앙 청산을 의무화할지를 논의했다."},
        {"situation": "철학적 파생 개념", "en": "Political theorists argue that positive rights are derivative of more fundamental negative rights, deriving their moral force from the prior obligation to respect individual autonomy.", "ko": "정치 이론가들은 적극적 권리가 더 근본적인 소극적 권리에서 파생된다고 주장하며, 개인의 자율성을 존중해야 할 선행 의무로부터 도덕적 힘을 이끌어낸다."},
    ],
    78: [  # diligence
        {"situation": "사전 실사 과정", "en": "The acquirer's legal and financial teams conducted intensive due diligence over sixty days, scrutinizing the target's regulatory compliance history, pending litigation, and the accuracy of the projected revenue forecasts.", "ko": "인수자의 법무 및 재무팀은 60일에 걸쳐 집중적인 실사를 수행하며, 피인수 기업의 규제 준수 이력, 계류 중인 소송, 그리고 예상 수익 예측의 정확성을 면밀히 검토했다."},
        {"situation": "학술 연구의 성실성", "en": "The committee commended the researcher's intellectual diligence in cross-referencing primary sources across three linguistic traditions, noting that this methodological rigor significantly strengthened the study's comparative claims.", "ko": "위원회는 세 가지 언어 전통에 걸쳐 일차 자료를 상호 참조한 연구자의 지적 성실성을 칭찬하며, 이 방법론적 엄격함이 연구의 비교 주장을 크게 강화했다고 언급했다."},
        {"situation": "법적 의무 이행 기준", "en": "The standard of diligence required of a professional is ordinarily measured against what a reasonably competent practitioner in the same field would have done under comparable circumstances.", "ko": "전문가에게 요구되는 성실 기준은 일반적으로 동일한 분야에서 합리적으로 유능한 실무자가 비슷한 상황에서 했을 것을 기준으로 측정된다."},
        {"situation": "규제 준수 모니터링", "en": "Anti-money laundering regulations impose ongoing diligence obligations on financial institutions, requiring continuous monitoring of customer transactions and periodic reassessment of risk profiles.", "ko": "자금세탁방지 규정은 금융 기관에 지속적인 성실 의무를 부과하며, 고객 거래의 지속적인 모니터링과 위험 프로파일의 주기적 재평가를 요구한다."},
        {"situation": "교육 성취와 노력의 관계", "en": "Longitudinal studies on academic achievement consistently find that the diligence with which students engage in deliberate practice is a stronger predictor of mastery than measured cognitive ability alone.", "ko": "학업 성취에 관한 종단 연구들은 학생들이 의도적 연습에 참여하는 성실함이 측정된 인지 능력만으로보다 숙달에 대한 더 강력한 예측 인자임을 일관되게 발견한다."},
    ],
    79: [  # dilution
        {"situation": "주식 발행 가치 희석", "en": "Existing shareholders raised concerns about earnings dilution following the company's announcement of a large secondary equity offering priced at a significant discount to the prevailing market rate.", "ko": "기존 주주들은 회사가 현재 시장 가격 대비 상당한 할인가로 책정된 대규모 추가 주식 발행을 발표한 후 수익 희석에 대한 우려를 제기했다."},
        {"situation": "브랜드 가치 희석 전략", "en": "Brand strategists cautioned that premature entry into the mass-market segment risked significant brand dilution, eroding the premium positioning that had taken decades to establish among high-income consumers.", "ko": "브랜드 전략가들은 매스 마켓 세그먼트에 대한 조기 진입이 고소득 소비자들 사이에서 수십 년에 걸쳐 확립된 프리미엄 포지셔닝을 침식하는 상당한 브랜드 희석 위험이 있다고 경고했다."},
        {"situation": "투표권 희석 선거 제도", "en": "Constitutional scholars challenged the electoral district boundaries on the grounds that the configuration resulted in systematic vote dilution for minority communities in violation of voting rights legislation.", "ko": "헌법 학자들은 그 구성이 투표권 법률에 위반하여 소수 공동체에 대한 체계적인 투표권 희석을 초래한다는 이유로 선거구 경계에 이의를 제기했다."},
        {"situation": "화학 물질 농도 조절", "en": "Laboratory protocols required the progressive dilution of the reagent through standardized serial titration to achieve concentrations suitable for the sensitivity range of the analytical instrument being used.", "ko": "실험실 프로토콜은 사용 중인 분석 기기의 감도 범위에 적합한 농도를 달성하기 위해 표준화된 연속 적정을 통한 시약의 점진적 희석을 요구했다."},
        {"situation": "권력 희석 정치 분석", "en": "Political analysts argued that the constitutional amendment diluted executive accountability by distributing decision-making authority across multiple agencies without establishing clear lines of democratic oversight.", "ko": "정치 분석가들은 헌법 개정이 명확한 민주적 감시 라인을 확립하지 않고 여러 기관에 의사결정 권한을 분산시킴으로써 행정부 책임을 희석시켰다고 주장했다."},
    ],
    82: [  # disclosure
        {"situation": "기업 재무 공시 의무", "en": "Securities regulations mandate timely disclosure of material information that could reasonably affect investors' decisions, with criminal penalties applicable to deliberate concealment or misrepresentation.", "ko": "증권 규정은 투자자의 결정에 합리적으로 영향을 미칠 수 있는 중요 정보의 적시 공시를 의무화하며, 의도적 은폐 또는 허위 표시에는 형사 처벌이 적용된다."},
        {"situation": "의료 정보 환자 동의", "en": "The doctrine of informed consent requires physicians to make full disclosure of material risks associated with proposed treatments, enabling patients to make autonomous and genuinely informed decisions.", "ko": "충분한 정보에 기반한 동의 원칙은 의사들이 제안된 치료와 관련된 중요한 위험 사항을 완전히 공개하여 환자들이 자율적이고 진정한 정보에 입각한 결정을 내릴 수 있도록 요구한다."},
        {"situation": "내부 고발 보호 법제", "en": "Whistleblower protection legislation shields employees who make qualifying disclosures of employer wrongdoing from retaliation, provided the disclosure is made in accordance with prescribed procedural requirements.", "ko": "내부 고발자 보호 법률은 규정된 절차적 요건에 따라 공개가 이루어진다는 조건으로, 고용주의 비위를 자격 있는 방식으로 공개한 직원들을 보복으로부터 보호한다."},
        {"situation": "환경 위험 정보 공개", "en": "The community right-to-know provisions required industrial facilities to disclose the quantities and types of hazardous chemicals stored on site, enabling local authorities to plan emergency responses accordingly.", "ko": "커뮤니티 알 권리 조항은 산업 시설이 현장에 보관된 유해 화학물질의 수량과 종류를 공개하도록 요구하여, 지방 당국이 그에 따라 비상 대응을 계획할 수 있게 했다."},
        {"situation": "이해 충돌 공개 의무", "en": "Academic journals now routinely require authors to complete comprehensive conflict of interest disclosure forms, acknowledging the potential for funding relationships to influence research design, analysis, and interpretation.", "ko": "학술지들은 현재 저자들에게 자금 관계가 연구 설계, 분석, 해석에 영향을 미칠 수 있는 잠재성을 인정하는 포괄적인 이해 충돌 공개 양식을 작성하도록 일상적으로 요구한다."},
    ],
    83: [  # discrepancy
        {"situation": "감사 재무 기록 불일치", "en": "The external auditors flagged a material discrepancy between the subsidiary's reported inventory levels and the independent stocktake results, triggering a forensic investigation into the company's warehouse management practices.", "ko": "외부 감사인들은 자회사의 보고된 재고 수준과 독립적 실사 결과 간의 중요한 불일치를 지적하여, 회사의 창고 관리 관행에 대한 법의학적 조사를 촉발시켰다."},
        {"situation": "역사 기록 해석 차이", "en": "Historians have long debated the discrepancy between official diplomatic records and personal diaries in their account of the treaty negotiations, with each source revealing a different understanding of the parties' true intentions.", "ko": "역사학자들은 조약 협상에 대한 공식 외교 기록과 개인 일기 사이의 불일치에 대해 오랫동안 논쟁해왔으며, 각 출처는 당사자들의 진정한 의도에 대한 다른 이해를 드러낸다."},
        {"situation": "임상 연구 재현 실패", "en": "The replication crisis in psychology reflects a fundamental discrepancy between initial published effect sizes and those found in independent replication studies, raising questions about publication bias and methodological standards.", "ko": "심리학의 재현 위기는 최초 발표된 효과 크기와 독립적 재현 연구에서 발견된 것들 사이의 근본적인 불일치를 반영하며, 출판 편향과 방법론적 기준에 대한 의문을 제기한다."},
        {"situation": "이민 기록 검토", "en": "Immigration authorities identified a discrepancy between the biographical details in the applicant's passport and those appearing in the corroborating documentation submitted in support of the asylum claim.", "ko": "이민 당국은 신청자의 여권에 기재된 개인 정보와 망명 신청을 지원하기 위해 제출된 확인 문서에 나타난 정보 사이의 불일치를 발견했다."},
        {"situation": "기후 모델 예측 검증", "en": "Climate scientists carefully examine any discrepancy between model predictions and observational data, recognizing that persistent divergences may indicate either measurement error or structural limitations in the underlying theoretical framework.", "ko": "기후 과학자들은 모델 예측과 관측 데이터 사이의 불일치를 주의 깊게 검토하며, 지속적인 차이가 측정 오류 또는 기초 이론 체계의 구조적 한계를 나타낼 수 있음을 인식한다."},
    ],
    85: [  # disparity
        {"situation": "의료 접근성 불평등", "en": "Epidemiological research has consistently documented pronounced racial disparities in cardiovascular disease outcomes that persist even after controlling for socioeconomic status, insurance coverage, and lifestyle factors.", "ko": "역학 연구는 사회경제적 지위, 보험 적용 범위, 생활 방식 요인을 통제한 후에도 지속되는 심혈관 질환 결과에서 두드러진 인종적 불평등을 일관되게 기록해왔다."},
        {"situation": "젠더 임금 격차 분석", "en": "Labor economists continue to debate the extent to which the gender pay disparity reflects overt discrimination versus the occupational sorting effects of persistent gender norms regarding caregiving responsibilities.", "ko": "노동 경제학자들은 성별 임금 격차가 공공연한 차별을 반영하는 정도 대 돌봄 책임에 관한 지속적인 성별 규범의 직업 분류 효과를 반영하는 정도에 대해 계속 논쟁하고 있다."},
        {"situation": "교육 기회 불평등 연구", "en": "Educational attainment disparities between socioeconomic groups are self-reinforcing across generations, as parental education levels strongly predict the quality of cognitive stimulation in early childhood environments.", "ko": "사회경제적 집단 간의 교육 성취 불평등은 세대를 거쳐 자기 강화되는데, 이는 부모의 교육 수준이 유아기 환경에서의 인지 자극의 질을 강하게 예측하기 때문이다."},
        {"situation": "글로벌 부의 분배", "en": "Economists note with alarm the growing disparity between the asset accumulation of the ultra-wealthy and the stagnant real incomes of median workers, arguing that this divergence undermines social cohesion and democratic legitimacy.", "ko": "경제학자들은 초부유층의 자산 축적과 중위 근로자들의 정체된 실질 소득 사이의 커지는 격차에 우려를 표명하며, 이 분열이 사회적 결속과 민주적 정당성을 훼손한다고 주장한다."},
        {"situation": "형사 사법 불평등", "en": "The sentencing disparity between offences involving crack cocaine and powder cocaine has been widely criticized as perpetuating racially discriminatory outcomes within the criminal justice system.", "ko": "크랙 코카인과 파우더 코카인과 관련된 범죄 간의 양형 격차는 형사 사법 시스템 내에서 인종적으로 차별적인 결과를 영속화한다는 이유로 널리 비판받아왔다."},
    ],
    86: [  # dissolution
        {"situation": "기업 청산 절차", "en": "Following the members' voluntary dissolution of the limited liability company, the liquidator distributed the remaining assets to creditors in strict accordance with the statutory order of priority.", "ko": "유한 책임 회사의 구성원 자발적 해산 이후, 청산인은 법정 우선순위에 따라 잔여 자산을 채권자들에게 엄격하게 배분했다."},
        {"situation": "의회 해산 헌법 절차", "en": "The monarch's constitutional power to dissolve parliament at the request of the prime minister serves as a crucial mechanism for resolving legislative deadlock through a fresh electoral mandate.", "ko": "총리의 요청에 따라 의회를 해산하는 군주의 헌법적 권한은 새로운 선거 위임을 통해 입법적 교착을 해결하는 중요한 메커니즘으로 기능한다."},
        {"situation": "국제 조직 해체", "en": "The dissolution of the Soviet Union in 1991 represented one of the most consequential geopolitical transformations of the twentieth century, redrawing the political map across Eurasia.", "ko": "1991년 소련의 해체는 20세기에서 가장 중대한 지정학적 변화 중 하나로, 유라시아 전역에 걸쳐 정치 지형을 재편했다."},
        {"situation": "파트너십 종료 법적 분쟁", "en": "The court-ordered dissolution of the partnership required an independent valuation of goodwill, intellectual property, and ongoing customer contracts before equitable division of assets could be effected.", "ko": "법원 명령에 의한 파트너십 해산은 자산의 형평적 분배가 이루어지기 전에 영업권, 지식재산권, 진행 중인 고객 계약에 대한 독립적인 평가를 요구했다."},
        {"situation": "혼합 물질 과학적 분리", "en": "The chemical dissolution of the rock matrix allowed geologists to extract and analyze trace mineral inclusions that would otherwise be inaccessible to conventional analytical techniques.", "ko": "암석 기질의 화학적 용해는 지질학자들이 기존의 분석 기법으로는 접근할 수 없는 미량 광물 포유물을 추출하고 분석할 수 있게 해주었다."},
    ],
    88: [  # deferral
        {"situation": "세금 납부 연기 전략", "en": "Tax deferral strategies using retirement accounts exploit the time value of money principle by postponing tax liability to future periods when the taxpayer may face a lower marginal rate.", "ko": "퇴직 계좌를 활용한 세금 납부 연기 전략은 납세자가 더 낮은 한계 세율에 직면할 수 있는 미래 기간으로 세금 부채를 연기함으로써 화폐의 시간적 가치 원칙을 활용한다."},
        {"situation": "임상 연구 수익 인식", "en": "Revenue recognition standards require pharmaceutical companies to defer recognition of milestone payments until the performance obligations associated with each contractual milestone have been substantially satisfied.", "ko": "수익 인식 기준은 제약 회사들이 각 계약 마일스톤과 관련된 이행 의무가 실질적으로 충족될 때까지 마일스톤 지급금의 인식을 연기하도록 요구한다."},
        {"situation": "재판 일정 연기 요청", "en": "Defense counsel sought deferral of the trial date on the grounds that newly discovered documentary evidence required additional time to authenticate and incorporate into the litigation strategy.", "ko": "피고 측 변호인은 새로 발견된 문서 증거를 진본 확인하고 소송 전략에 통합하는 데 추가 시간이 필요하다는 이유로 재판 일정의 연기를 신청했다."},
        {"situation": "인프라 투자 지연", "en": "Chronic deferral of maintenance expenditure on critical infrastructure has created a substantial infrastructure deficit that will require multi-generational investment programs to remediate effectively.", "ko": "중요 인프라에 대한 유지 관리 지출의 만성적 연기는 효과적으로 개선하기 위해 여러 세대에 걸친 투자 프로그램이 필요한 상당한 인프라 부족을 야기했다."},
        {"situation": "의사결정 심리학적 분석", "en": "Behavioral economists have demonstrated that the deferral of unpleasant decisions is a predictable manifestation of present bias, whereby individuals systematically overweight immediate costs relative to future consequences.", "ko": "행동 경제학자들은 불쾌한 결정의 연기가 현재 편향의 예측 가능한 표현임을 증명했는데, 이는 개인들이 체계적으로 미래 결과에 비해 즉각적인 비용을 과대평가하는 현상이다."},
    ],
    89: [  # domicile
        {"situation": "국제 조세 주소지 결정", "en": "The concept of fiscal domicile is central to international tax law, determining which jurisdiction has primary taxing rights over an individual's worldwide income and capital gains.", "ko": "재정적 주소지 개념은 국제 세법의 핵심으로, 개인의 전 세계 소득 및 자본 이득에 대한 주요 과세권을 어느 관할권이 가지는지를 결정한다."},
        {"situation": "상속 준거법 결정", "en": "Private international law traditionally determines the succession to movable property according to the law of the deceased's domicile at the time of death, while immovable property is governed by the lex situs.", "ko": "국제 사법은 전통적으로 동산의 상속을 사망 시 고인의 주소지 법에 따라 결정하며, 부동산은 소재지법(lex situs)에 의해 규율된다."},
        {"situation": "기업 등록 최적화", "en": "Many multinational corporations establish their formal domicile in low-tax jurisdictions such as the Cayman Islands or the British Virgin Islands, creating a structural disconnect between where economic activity occurs and where profits are taxed.", "ko": "많은 다국적 기업들은 케이맨 제도나 영국령 버진 아일랜드 같은 저세율 관할권에 공식 주소지를 설립하여, 경제 활동이 이루어지는 곳과 이익이 과세되는 곳 사이의 구조적 불일치를 만들어낸다."},
        {"situation": "난민 법적 지위 결정", "en": "The concept of habitual domicile has become increasingly significant in refugee law, as stateless persons may have no country of nationality to which they can be returned following the determination of their asylum claims.", "ko": "무국적자는 망명 신청 판정 이후 돌아갈 수 있는 국적 국가가 없을 수 있기 때문에, 상습적 주소지 개념은 난민법에서 점점 더 중요해지고 있다."},
        {"situation": "의회 의원 자격 요건", "en": "Electoral law in many jurisdictions requires candidates to demonstrate domicile within the constituency they seek to represent, a requirement designed to ensure some degree of accountability to local constituents.", "ko": "많은 관할권의 선거법은 후보자들이 대표하고자 하는 선거구 내에서의 거주지를 증명하도록 요구하는데, 이 요건은 지역 유권자들에 대한 어느 정도의 책임을 보장하기 위해 설계되었다."},
    ],
    91: [  # duress
        {"situation": "계약 강박 무효 주장", "en": "The court accepted the defendant's plea that the settlement agreement had been executed under duress, finding that the credible threat of criminal prosecution had vitiated the element of genuine consent.", "ko": "법원은 합의가 강박 하에 체결되었다는 피고의 주장을 받아들이며, 형사 기소에 대한 신빙성 있는 협박이 진정한 동의의 요소를 무효화했다고 판단했다."},
        {"situation": "취약 계층 착취 분석", "en": "Scholars of labor exploitation argue that employment relationships in low-wage sectors frequently replicate conditions of economic duress that constrain workers' effective freedom to refuse or renegotiate terms.", "ko": "노동 착취 학자들은 저임금 부문의 고용 관계가 근로자들의 조건을 거부하거나 재협상할 실질적 자유를 제한하는 경제적 강박의 조건을 자주 복제한다고 주장한다."},
        {"situation": "전쟁 포로 자백 증거", "en": "International humanitarian law categorically prohibits extracting confessions or intelligence from prisoners of war through physical or psychological duress, regardless of the operational urgency claimed by the detaining power.", "ko": "국제인도법은 억류 국가가 주장하는 작전상 긴박함과 관계없이, 신체적 또는 심리적 강박을 통해 전쟁 포로로부터 자백이나 정보를 추출하는 것을 명확히 금지한다."},
        {"situation": "인도적 지원 조건부 압박", "en": "Humanitarian organizations condemned the conditioning of food aid on political compliance as tantamount to placing vulnerable civilian populations under duress, exploiting survival needs to extract political acquiescence.", "ko": "인도주의 단체들은 식량 지원을 정치적 순응의 조건으로 삼는 것이 생존 필요를 이용하여 정치적 복종을 이끌어내는 취약한 민간인 집단에 대한 강박에 상당한다고 비난했다."},
        {"situation": "기업 인수 거부권 압박", "en": "Target company directors argued that the board's approval of the takeover bid had been obtained under duress, citing persistent public pressure campaigns and regulatory threats orchestrated by the acquirer.", "ko": "피인수 기업 이사들은 인수자가 조직한 지속적인 공개 압박 캠페인과 규제 위협을 이유로 들며, 이사회의 인수 입찰 승인이 강박 하에 이루어졌다고 주장했다."},
    ],
    92: [  # enforcement
        {"situation": "국제 제재 집행 메커니즘", "en": "The Security Council's enforcement mechanisms are fundamentally constrained by the veto powers of the five permanent members, which can prevent collective action even against clear violations of international law.", "ko": "안전보장이사회의 집행 메커니즘은 5개 상임이사국의 거부권에 의해 근본적으로 제한되어, 국제법의 명백한 위반에 대해서도 집단적 행동을 방해할 수 있다."},
        {"situation": "환경 규정 적용 격차", "en": "Environmental enforcement gaps in developing countries are frequently attributed to institutional capacity deficits, inadequate funding for inspection agencies, and the corrupting influence of powerful industrial interests.", "ko": "개발도상국의 환경 규정 집행 격차는 제도적 역량 부족, 감사 기관을 위한 불충분한 자금, 강력한 산업적 이해관계의 부패 영향으로 자주 귀인된다."},
        {"situation": "지식재산권 국경 집행", "en": "Border enforcement measures against counterfeit goods, while increasingly sophisticated technologically, remain hampered by the sheer volume of international trade and the adaptive ingenuity of organized intellectual property infringers.", "ko": "모조품에 대한 국경 집행 조치는 기술적으로 점점 정교해지고 있지만, 국제 무역의 방대한 규모와 조직화된 지식재산권 침해자들의 적응적 창의성으로 인해 여전히 방해를 받고 있다."},
        {"situation": "사법 판결 집행 국제 협력", "en": "Cross-border enforcement of foreign judgments requires the existence of bilateral recognition treaties or, absent such agreements, satisfaction of the domestic court that the foreign judgment meets specified fairness standards.", "ko": "외국 판결의 국경 간 집행은 양자 승인 조약의 존재나, 그러한 협약이 없는 경우 외국 판결이 특정 공정성 기준을 충족한다는 국내 법원의 확인을 필요로 한다."},
        {"situation": "데이터 보호 감독 기관", "en": "The enforcement powers granted to data protection authorities under comprehensive privacy legislation include the authority to impose substantial administrative fines as a percentage of global corporate turnover.", "ko": "포괄적인 개인정보 보호 법률에 따라 데이터 보호 당국에 부여된 집행 권한에는 전 세계 기업 매출액의 일정 비율에 해당하는 상당한 행정 과징금을 부과하는 권한이 포함된다."},
    ],
    94: [  # encroachment
        {"situation": "영토 주권 침해", "en": "The diplomatic protest formally objected to the construction of military installations on disputed atolls, characterizing the activity as unlawful encroachment upon the exclusive economic zone of the protesting state.", "ko": "외교적 항의는 분쟁 중인 환초에 군사 시설 건설에 공식적으로 이의를 제기하며, 그 활동을 항의하는 국가의 배타적 경제 수역에 대한 불법적 침범으로 규정했다."},
        {"situation": "시장 지배력 남용 분석", "en": "Antitrust regulators characterized the dominant firm's predatory pricing tactics as an encroachment on the competitive space that smaller rivals required to achieve viable scale economies.", "ko": "반독점 규제 당국은 지배적 기업의 약탈적 가격 책정 전술을 소규모 경쟁자들이 실행 가능한 규모의 경제를 달성하기 위해 필요한 경쟁 공간에 대한 침범으로 규정했다."},
        {"situation": "사생활 보호 디지털 감시", "en": "Civil liberties organizations litigated against the government's bulk surveillance program as an unconstitutional encroachment upon citizens' privacy rights under the fourth amendment's protections against unreasonable searches.", "ko": "시민 자유 단체들은 정부의 대규모 감시 프로그램이 불합리한 수색에 대한 수정헌법 제4조의 보호 하에 시민의 사생활권에 대한 위헌적 침범이라는 이유로 소송을 제기했다."},
        {"situation": "토지 무단 점유 소송", "en": "The property owner brought an action for encroachment after survey evidence revealed that the neighbor's fence had been erected entirely within the legal boundary of the plaintiff's registered title.", "ko": "측량 증거에서 이웃의 울타리가 원고의 등록된 소유권의 법적 경계 내에 완전히 세워진 것이 밝혀진 후, 재산 소유자는 침범에 대한 소송을 제기했다."},
        {"situation": "기업 인수 경쟁 영역 침범", "en": "The established software company viewed its cloud-based rival's expansion into enterprise data management as a direct encroachment on its core market, prompting an accelerated product development response.", "ko": "기성 소프트웨어 회사는 클라우드 기반 경쟁사의 기업 데이터 관리 분야 확장을 핵심 시장에 대한 직접적인 침범으로 보고 가속화된 제품 개발 대응을 촉구했다."},
    ],
    95: [  # encumbrance
        {"situation": "부동산 매매 권리 확인", "en": "The title search revealed a historic easement and an unregistered right of way that together constituted significant encumbrances on the property, materially affecting its market value and development potential.", "ko": "권리 조사에서 역사적 지역권과 미등록 통행권이 발견되었으며, 이것들은 함께 부동산에 중요한 부담을 구성하여 시장 가치와 개발 잠재력에 실질적으로 영향을 미쳤다."},
        {"situation": "기업 자산 부채 평가", "en": "The acquisition due diligence team catalogued all encumbrances on the target's fixed assets, including outstanding mortgages, equipment finance agreements, and undisclosed liens held by trade creditors.", "ko": "인수 실사팀은 미상환 모기지, 장비 금융 계약, 거래 채권자들이 보유한 미공개 유치권을 포함하여 피인수 기업의 고정 자산에 대한 모든 부담을 목록화했다."},
        {"situation": "공공 토지 이용 제한", "en": "Conservation encumbrances placed on the agricultural land in perpetuity prohibited future owners from converting it to residential or commercial use, preserving its ecological and scenic value for public benefit.", "ko": "농지에 영구적으로 부과된 보전 부담은 미래 소유자가 그것을 주거용 또는 상업용으로 전환하는 것을 금지하여, 공공 이익을 위해 그것의 생태적, 경관적 가치를 보전했다."},
        {"situation": "담보대출 신청 절차", "en": "Lenders typically require title insurance to protect against the risk that undisclosed encumbrances, such as unpaid property taxes or mechanics' liens, could cloud the borrower's title and impair the security.", "ko": "대출자들은 일반적으로 미납 재산세나 공사 유치권과 같은 미공개 부담이 차입자의 소유권을 흐리게 하고 담보를 손상시킬 수 있는 위험으로부터 보호하기 위해 권원 보험을 요구한다."},
        {"situation": "지식재산 라이선스 제한", "en": "The assignment of the patent portfolio was subject to existing licensing encumbrances, meaning that the acquirer was bound by the terms of pre-existing royalty agreements with third-party licensees.", "ko": "특허 포트폴리오의 양도는 기존 라이선스 부담의 적용을 받아, 인수자가 제3자 피라이선스인과의 기존 로열티 계약 조건에 구속된다는 것을 의미했다."},
    ],
    100: [  # escrow
        {"situation": "부동산 거래 중간 보관", "en": "The earnest money deposit was held in escrow by the title company pending satisfaction of the contractual contingencies, including the buyer's financing approval and the property inspection clearance.", "ko": "계약금 보증금은 매수인의 자금 조달 승인과 부동산 검사 통과를 포함한 계약상 조건들이 충족될 때까지 권원 회사에 의해 에스크로에 보관되었다."},
        {"situation": "소프트웨어 소스 코드 보호", "en": "The software licensing agreement required the vendor to deposit the source code in a third-party escrow, ensuring that the licensee could access the underlying code in the event of the vendor's insolvency.", "ko": "소프트웨어 라이선스 계약은 판매자가 판매자의 지급 불능 시 피라이선스인이 기초 코드에 접근할 수 있도록 소스 코드를 제3자 에스크로에 예치하도록 요구했다."},
        {"situation": "분쟁 자금 법원 관리", "en": "The court ordered the disputed funds to be held in escrow pending the outcome of the appeal, preventing either party from dissipating the assets during the litigation.", "ko": "법원은 소송 중에 어느 당사자도 자산을 탕진하지 못하도록, 항소 결과가 나올 때까지 분쟁 자금을 에스크로에 보관하도록 명령했다."},
        {"situation": "인수합병 조건부 지급", "en": "The acquisition included an escrow holdback provision under which a portion of the purchase price was retained pending resolution of indemnification claims arising from pre-closing liabilities.", "ko": "인수 계약에는 거래 전 부채에서 발생하는 면책 청구가 해결될 때까지 매매 대금의 일부를 보유하는 에스크로 보류 조항이 포함되었다."},
        {"situation": "국제 무역 결제 보안", "en": "International trade transactions increasingly use escrow services administered by neutral financial intermediaries to mitigate the risk that either the buyer will fail to pay or the seller will fail to deliver conforming goods.", "ko": "국제 무역 거래는 매수인이 대금을 지급하지 못하거나 매도인이 적합한 상품을 인도하지 못할 위험을 완화하기 위해 중립적 금융 중개자가 관리하는 에스크로 서비스를 점점 더 활용하고 있다."},
    ],
}

for word_id, new_exs in new_examples.items():
    if word_id in word_map:
        word_map[word_id]['examples'].extend(new_exs)

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Batch 2 done.")
with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    d2 = json.load(f)
wm2 = {w['id']: w for w in d2['words']}
for wid in sorted(new_examples.keys()):
    print(f"  id={wid} {wm2[wid]['word']}: {len(wm2[wid]['examples'])} examples")
