import json

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

words = data['words']
word_map = {w['id']: w for w in words}

new_examples = {
    107: [  # expropriation
        {"situation": "공익 수용 보상 기준", "en": "Constitutional guarantees against arbitrary expropriation require the state to demonstrate both a legitimate public purpose and payment of prompt, adequate, and effective compensation to the dispossessed owner.", "ko": "자의적 수용에 대한 헌법적 보장은 국가가 합법적인 공공 목적과 함께 수용된 소유자에 대한 신속하고, 충분하며, 효과적인 보상 지급을 모두 입증하도록 요구한다."},
        {"situation": "외국인 투자 보호 조약", "en": "Bilateral investment treaties typically prohibit indirect expropriation, covering regulatory measures that substantially deprive investors of the economic value of their investments even without formal transfer of title.", "ko": "양자 투자 조약은 일반적으로 간접 수용을 금지하는데, 이는 공식적인 소유권 이전 없이도 투자자들의 투자 경제적 가치를 실질적으로 박탈하는 규제 조치를 포함한다."},
        {"situation": "자원 국유화 분쟁", "en": "The nationalization of the multinational's oil concessions constituted a de facto expropriation that prompted international arbitration proceedings under the energy charter treaty's investor protection provisions.", "ko": "다국적 기업의 석유 개발권 국유화는 에너지 헌장 조약의 투자자 보호 조항에 따른 국제 중재 절차를 촉발한 사실상의 수용을 구성했다."},
        {"situation": "도시 재개발 이주 보상", "en": "Urban renewal programs that displace established communities must be distinguished from lawful expropriation through procedural safeguards that ensure genuine consultation and adequacy of relocation assistance.", "ko": "기성 공동체를 이주시키는 도시 재생 프로그램은 진정한 협의와 이주 지원의 적절성을 보장하는 절차적 보호 장치를 통해 합법적 수용과 구별되어야 한다."},
        {"situation": "지적재산권 강제 실시", "en": "Compulsory licensing of pharmaceutical patents in public health emergencies occupies a contested legal space between legitimate exercise of sovereign regulatory power and indirect expropriation of intellectual property rights.", "ko": "공중 보건 비상 상황에서 의약품 특허의 강제 실시는 주권적 규제 권한의 합법적 행사와 지식재산권의 간접 수용 사이의 논쟁적인 법적 공간에 위치한다."},
    ],
    108: [  # fiduciary
        {"situation": "연금 운용 수탁 책임", "en": "Pension fund trustees bear a strict fiduciary duty to manage plan assets exclusively in the interests of beneficiaries, a standard that precludes pursuing environmental or social goals at the expense of financial returns.", "ko": "연금 기금 수탁자들은 수익자의 이익만을 위해 계획 자산을 관리해야 할 엄격한 수탁 의무를 지며, 이 기준은 재정적 수익을 희생하면서 환경적 또는 사회적 목표를 추구하는 것을 배제한다."},
        {"situation": "이사 회사 이익 보호", "en": "Corporate directors occupy fiduciary positions requiring them to exercise the duties of care and loyalty, which together prohibit self-dealing transactions and demand active, informed engagement in governance decisions.", "ko": "기업 이사들은 주의 의무와 충성 의무를 행사해야 하는 수탁적 지위를 차지하며, 이 두 가지 의무는 함께 자기 거래를 금지하고 거버넌스 결정에 적극적이고 충분한 정보에 입각한 참여를 요구한다."},
        {"situation": "변호사 의뢰인 관계", "en": "The attorney-client relationship is paradigmatically fiduciary in character, requiring solicitors to subordinate their own interests to those of clients and to maintain absolute confidentiality regarding privileged communications.", "ko": "변호사-의뢰인 관계는 전형적으로 수탁적 성격을 가지며, 법무사들이 자신의 이익을 의뢰인의 이익에 종속시키고 특권적 통신에 관한 절대적 비밀 유지를 요구한다."},
        {"situation": "재산 관리인 책임", "en": "Estate administrators acting in a fiduciary capacity are personally liable for losses arising from self-interested transactions with the estate's assets, regardless of whether the beneficiaries suffer actual damage.", "ko": "수탁적 역할로 행동하는 유산 관리인들은 수익자들이 실제 손해를 입었는지와 관계없이, 유산 자산과의 자기 이익적 거래에서 발생하는 손실에 대해 개인적으로 책임을 진다."},
        {"situation": "정보 우위 이용 금지", "en": "The fiduciary's prohibition on using information obtained through the relationship for personal advantage extends beyond the formal termination of the relationship to protect the principal's competitive interests indefinitely.", "ko": "관계를 통해 얻은 정보를 개인적 이익을 위해 사용하는 것에 대한 수탁자의 금지는 피신탁인의 경쟁적 이익을 무기한으로 보호하기 위해 관계의 공식적 종료 이후까지 연장된다."},
    ],
    110: [  # forbearance
        {"situation": "부채 상환 유예 협상", "en": "The creditor's forbearance agreement gave the financially distressed borrower an eighteen-month moratorium on principal repayments in exchange for enhanced reporting obligations and a pledge of additional collateral.", "ko": "채권자의 상환 유예 협약은 재정적으로 어려움에 처한 차입자에게 향상된 보고 의무와 추가 담보 제공의 대가로 원금 상환에 대한 18개월 유예를 제공했다."},
        {"situation": "부동산 압류 방지 정책", "en": "Government-mandated forbearance programs during the pandemic prevented widespread mortgage foreclosures while simultaneously creating deferred liability that borrowers would eventually need to repay.", "ko": "팬데믹 중 정부가 의무화한 상환 유예 프로그램은 광범위한 모기지 압류를 방지하면서도 동시에 차입자들이 결국 상환해야 할 이연 부채를 만들어냈다."},
        {"situation": "학자금 대출 상환 조정", "en": "Federal student loan forbearance policies provided temporary relief to borrowers experiencing unemployment or financial hardship, though critics noted the accumulation of interest during forbearance periods eroded long-term repayment capacity.", "ko": "연방 학자금 대출 상환 유예 정책은 실업이나 재정적 어려움을 겪는 차입자들에게 임시적 구제를 제공했지만, 비평가들은 유예 기간 동안의 이자 누적이 장기 상환 능력을 약화시킨다고 지적했다."},
        {"situation": "철학적 인내 덕목", "en": "Stoic philosophy elevates forbearance as a foundational virtue, arguing that the capacity to endure adversity without complaint is essential to maintaining rational agency in a world of uncontrollable external circumstances.", "ko": "스토아 철학은 인내를 근본적인 덕목으로 높이 평가하며, 불평 없이 역경을 견디는 능력이 통제할 수 없는 외부 상황의 세계에서 합리적 행위 능력을 유지하는 데 필수적이라고 주장한다."},
        {"situation": "분쟁 조기 해결 전략", "en": "The creditor's strategic forbearance in declining to enforce its legal rights immediately created goodwill that proved instrumental in negotiating a consensual restructuring that maximized ultimate recovery.", "ko": "채권자의 법적 권리를 즉시 행사하지 않는 전략적 상환 유예는 최종 회수를 극대화하는 합의적 구조조정을 협상하는 데 중요한 역할을 한 신뢰를 만들었다."},
    ],
    112: [  # forfeiture
        {"situation": "범죄 수익 몰수 법제", "en": "Civil asset forfeiture laws permit law enforcement agencies to seize property suspected of being connected to criminal activity, a power that has generated significant controversy regarding due process protections.", "ko": "민사 자산 몰수법은 범죄 활동과 연관된 것으로 의심되는 재산을 압수할 수 있는 법 집행 기관의 권한을 허용하며, 이 권한은 적법 절차 보호에 관한 상당한 논쟁을 야기했다."},
        {"situation": "계약 위반 보증금 몰취", "en": "The court upheld the forfeiture of the performance bond after determining that the contractor's abandonment of the project constituted a fundamental breach that had caused substantial losses to the developer.", "ko": "법원은 시공사의 프로젝트 포기가 개발업자에게 상당한 손실을 야기한 근본적 위반을 구성한다고 판단한 후, 이행 보증금의 몰취를 인정했다."},
        {"situation": "주식 매입권 소멸", "en": "Under the vesting schedule, unvested stock options were subject to forfeiture upon resignation, creating powerful financial incentives for key employees to remain with the company through the full vesting period.", "ko": "베스팅 일정에 따라, 미베스팅 스톡옵션은 사직 시 몰수의 대상이 되어, 핵심 직원들이 전체 베스팅 기간 동안 회사에 남도록 강력한 재정적 인센티브를 만들었다."},
        {"situation": "국적 상실 법적 분석", "en": "Historical provisions for forfeiture of citizenship upon voluntary naturalization in a foreign country have been substantially modified in contemporary law to reflect evolving norms regarding multiple nationality.", "ko": "외국에서의 자발적 귀화 시 시민권 상실에 관한 역사적 조항들은 복수 국적에 관한 진화하는 규범을 반영하기 위해 현대 법에서 상당히 수정되었다."},
        {"situation": "선물 반납 의무 규정", "en": "Anti-corruption statutes in many jurisdictions require public officials to report gifts exceeding a specified value and may mandate their forfeiture to the state treasury where acceptance would constitute a conflict of interest.", "ko": "많은 관할권의 반부패 법령은 공무원들이 특정 가치를 초과하는 선물을 신고하도록 요구하며, 수용이 이해 충돌을 구성하는 경우 국가 재무부에 반납을 의무화할 수 있다."},
    ],
    114: [  # fraud
        {"situation": "금융 사기 탐지 기술", "en": "Machine learning algorithms trained on historical transaction patterns have substantially improved financial institutions' ability to detect fraud in real time while minimizing false positives that disrupt legitimate customers.", "ko": "역사적 거래 패턴으로 훈련된 기계 학습 알고리즘은 합법적인 고객을 방해하는 오탐을 최소화하면서 실시간으로 금융 사기를 탐지하는 금융 기관의 능력을 크게 향상시켰다."},
        {"situation": "과학 연구 데이터 조작", "en": "Research fraud involving the fabrication or falsification of experimental data constitutes one of the gravest violations of scientific integrity, undermining the entire evidentiary foundation upon which subsequent research builds.", "ko": "실험 데이터의 조작 또는 위조를 수반하는 연구 사기는 과학적 청렴성의 가장 심각한 위반 중 하나로, 후속 연구가 구축되는 전체 증거적 토대를 훼손한다."},
        {"situation": "선거 사기 주장 검증", "en": "Courts have established a high evidentiary standard for electoral fraud claims, requiring plaintiffs to present systematic, verifiable evidence of irregularities sufficient to have affected the outcome of the contested election.", "ko": "법원은 선거 사기 주장에 대해 높은 증거 기준을 확립했으며, 원고가 다투는 선거 결과에 영향을 미치기에 충분한 불규칙의 체계적이고 검증 가능한 증거를 제시하도록 요구한다."},
        {"situation": "신원 도용 피해 방지", "en": "Identity fraud has become increasingly sophisticated as criminals exploit data breaches to obtain sufficient personal information to impersonate victims in financial transactions and government benefit applications.", "ko": "범죄자들이 데이터 침해를 악용하여 금융 거래 및 정부 혜택 신청에서 피해자를 사칭하기에 충분한 개인 정보를 얻음에 따라 신원 사기가 점점 더 정교해지고 있다."},
        {"situation": "보험 사기 사회적 비용", "en": "The social costs of insurance fraud extend beyond the financial losses borne by insurers, as fraudulent claims ultimately drive premium increases that diminish coverage affordability for honest policyholders.", "ko": "보험 사기의 사회적 비용은 보험사가 부담하는 재정적 손실을 넘어서며, 사기성 청구는 결국 정직한 보험 가입자들의 보장 접근성을 감소시키는 보험료 인상을 유발한다."},
    ],
    115: [  # goodwill
        {"situation": "기업 인수 브랜드 가치", "en": "The acquisition premium paid above book value was attributable primarily to the target's substantial goodwill, comprising its recognized brand, established customer relationships, and proprietary distribution network.", "ko": "장부 가치를 초과하여 지불된 인수 프리미엄은 주로 피인수 기업의 상당한 영업권에 기인했으며, 이는 인정된 브랜드, 확립된 고객 관계, 독점적 유통 네트워크를 포함했다."},
        {"situation": "손상 검사 회계 처리", "en": "Under current accounting standards, goodwill is no longer systematically amortized but must be tested annually for impairment, with any write-down recognized immediately in the income statement.", "ko": "현행 회계 기준에 따르면, 영업권은 더 이상 체계적으로 상각되지 않지만 연간 손상 여부를 검사해야 하며, 모든 감액은 손익계산서에 즉시 인식된다."},
        {"situation": "외교 관계 신뢰 자본", "en": "The nation expended considerable diplomatic goodwill in securing allied support for the sanctions regime, drawing down a reservoir of mutual trust that had accumulated through decades of cooperative foreign policy.", "ko": "그 국가는 수십 년간의 협력적 외교 정책을 통해 축적된 상호 신뢰의 저수지를 소진하며, 제재 체제에 대한 동맹국의 지지를 확보하는 데 상당한 외교적 호의를 소비했다."},
        {"situation": "지역 사회 기업 관계", "en": "The pharmaceutical company's visible community investment program was designed to generate goodwill among local stakeholders whose opposition could create operational and regulatory obstacles for the proposed facility expansion.", "ko": "제약 회사의 가시적인 지역 사회 투자 프로그램은 그 반대가 제안된 시설 확장을 위한 운영적 및 규제적 장애물을 만들 수 있는 지역 이해관계자들 사이에서 호의를 만들기 위해 설계되었다."},
        {"situation": "협상 타결 전제 조건", "en": "The mediator emphasized that restoring goodwill between the estranged parties was a prerequisite for substantive negotiations, suggesting a series of confidence-building measures before addressing the core disputed issues.", "ko": "조정자는 소원해진 당사자들 사이의 호의 회복이 실질적 협상의 전제 조건이라고 강조하며, 핵심 분쟁 사안을 다루기 전에 일련의 신뢰 구축 조치를 제안했다."},
    ],
    119: [  # impairment
        {"situation": "영업권 손상 인식", "en": "The goodwill impairment charge recorded in the third quarter reflected the deteriorating performance of the acquired subsidiary, whose revenue had consistently fallen short of the projections made at the time of acquisition.", "ko": "3분기에 인식된 영업권 손상 차손은 인수 시 작성된 예측을 지속적으로 하회하는 수익을 기록한 피인수 자회사의 악화된 성과를 반영했다."},
        {"situation": "노동 능력 손상 보상", "en": "The personal injury award included compensation for permanent functional impairment to the claimant's dominant hand, taking account of the impact on both earning capacity and quality of life.", "ko": "인신 피해 판결에는 청구인의 우세한 손에 대한 영구적 기능 장애에 대한 보상이 포함되었으며, 여기에는 수익 능력과 삶의 질에 대한 영향이 고려되었다."},
        {"situation": "환경 규제 생태계 손상", "en": "Environmental legislation increasingly addresses cumulative ecological impairment, recognizing that the incremental effects of multiple individually tolerable stressors can combine to cause irreversible ecosystem damage.", "ko": "환경 법률은 점점 더 누적적 생태계 손상을 다루고 있으며, 개별적으로는 허용 가능한 여러 스트레스 요인의 점진적 효과가 결합하여 돌이킬 수 없는 생태계 손상을 야기할 수 있음을 인식한다."},
        {"situation": "인지 장애 의학 진단", "en": "Mild cognitive impairment is distinguished from normal age-related decline by standardized neuropsychological testing, with particular attention to episodic memory deficits that may precede Alzheimer's disease.", "ko": "경도 인지 장애는 알츠하이머병에 선행할 수 있는 일화적 기억 결손에 특히 주의를 기울이는 표준화된 신경심리학적 검사를 통해 정상적인 노화 관련 저하와 구별된다."},
        {"situation": "신용 등급 자본 충분성", "en": "Basel III capital adequacy frameworks require banks to hold sufficient capital against potential loan impairment losses, calibrating reserve requirements to the risk profiles of different asset classes in the lending portfolio.", "ko": "바젤 III 자본 적정성 체계는 은행들이 대출 손상 손실 가능성에 대비해 충분한 자본을 보유하도록 요구하며, 대출 포트폴리오의 다양한 자산 등급의 위험 프로파일에 따라 충당금 요건을 조정한다."},
    ],
    120: [  # impasse
        {"situation": "파리 기후 협상 교착", "en": "The negotiations reached an impasse when developing nations refused to accept legally binding emission targets without equivalent financial commitments from industrialized countries to fund their clean energy transitions.", "ko": "개발도상국들이 산업화 국가들의 청정 에너지 전환 자금 조달을 위한 동등한 재정적 약속 없이는 법적 구속력 있는 배출 목표를 수용하기를 거부하면서 협상은 교착 상태에 빠졌다."},
        {"situation": "노사 단체교섭 결렬", "en": "The collective bargaining impasse between the transit authority and the drivers' union threatened to paralyze the metropolitan transportation network ahead of a major international sporting event.", "ko": "교통 당국과 운전기사 노동조합 간의 단체 교섭 교착은 주요 국제 스포츠 행사를 앞두고 대도시 교통 네트워크를 마비시킬 위협이 되었다."},
        {"situation": "양당 입법 협상 막힘", "en": "Constitutional scholars argued that the persistent legislative impasse on fiscal policy reflected a deeper structural malfunction of the separation of powers system under conditions of ideological polarization.", "ko": "헌법 학자들은 재정 정책에 대한 지속적인 입법 교착이 이념적 극화 상황에서 권력 분립 체계의 더 깊은 구조적 오작동을 반영한다고 주장했다."},
        {"situation": "외교 회담 진전 없음", "en": "After seven rounds of talks, the diplomatic impasse over the disputed maritime boundary remained unresolved, prompting both parties to pursue parallel strategies of military posturing and international judicial proceedings.", "ko": "7차례의 회담 끝에도 분쟁 해양 경계를 둘러싼 외교적 교착 상태는 해결되지 않았으며, 이는 양측이 군사적 위세와 국제 사법 절차의 병행 전략을 추구하도록 촉구했다."},
        {"situation": "회사 합병 조건 협상", "en": "The merger negotiations hit an impasse over valuation methodology, with the target's board insisting on a discounted cash flow approach while the acquirer's advisers favored a comparable transactions analysis.", "ko": "합병 협상은 평가 방법론을 둘러싸고 교착 상태에 빠졌는데, 피인수 기업의 이사회는 할인된 현금 흐름 방식을 주장했고 인수 기업의 고문들은 비교 거래 분석을 선호했다."},
    ],
    124: [  # indemnification
        {"situation": "기업 이사 손실 보호", "en": "Corporate bylaws commonly provide for broad indemnification of directors and officers against third-party claims arising from their good-faith exercise of business judgment, subject to exceptions for willful misconduct.", "ko": "기업 정관은 일반적으로 고의적 위법행위에 대한 예외를 조건으로, 이사와 임원들이 선의로 경영 판단을 행사하는 데서 발생하는 제3자 청구에 대해 광범위한 손실 보상을 규정한다."},
        {"situation": "환경 오염 계약 책임", "en": "The acquisition agreement's environmental indemnification clause required the seller to bear all remediation costs associated with pre-closing contamination events for a period of ten years following completion.", "ko": "인수 계약의 환경 손실 보상 조항은 매도인이 거래 완료 후 10년 기간 동안 거래 전 오염 사건과 관련된 모든 정화 비용을 부담하도록 요구했다."},
        {"situation": "기술 라이선스 특허 보호", "en": "Software vendors routinely provide intellectual property indemnification to enterprise customers, committing to defend them against infringement claims arising from the licensed technology and to bear any resulting financial judgments.", "ko": "소프트웨어 공급업체들은 기업 고객에게 지식재산권 손실 보상을 일상적으로 제공하며, 라이선스된 기술에서 발생하는 침해 청구로부터 고객을 방어하고 이로 인한 모든 재정적 판결을 부담하기로 약속한다."},
        {"situation": "건설 계약 사고 배상", "en": "Standard construction contracts include mutual indemnification provisions under which each party assumes responsibility for claims arising from its own negligence, avoiding disputes about proportionate liability allocation in multi-party projects.", "ko": "표준 건설 계약에는 각 당사자가 자신의 과실에서 발생하는 청구에 대한 책임을 지는 상호 손실 보상 조항이 포함되어 있어, 다자간 프로젝트에서 비례적 책임 배분에 관한 분쟁을 피한다."},
        {"situation": "정치적 박해 피해자 보상", "en": "Transitional justice frameworks often include state indemnification programs to compensate victims of systematic human rights abuses, recognizing the state's moral and legal responsibility for institutionally sanctioned atrocities.", "ko": "전환기 정의 체계는 종종 국가가 제도적으로 인가한 잔혹 행위에 대한 도덕적, 법적 책임을 인정하며, 체계적인 인권 침해 피해자를 보상하기 위한 국가 손실 보상 프로그램을 포함한다."},
    ],
    127: [  # insolvency
        {"situation": "기업 파산 절차 개시", "en": "The company's insolvency was triggered by an unforeseen acceleration clause in its bond indenture that demanded immediate repayment of the entire outstanding principal upon a credit rating downgrade.", "ko": "회사의 지급 불능은 신용 등급 강등 시 미상환 원금 전액의 즉각적인 상환을 요구하는 사채 계약의 예상치 못한 기한 전 가속 조항에 의해 촉발되었다."},
        {"situation": "국가 채무 불이행 위기", "en": "State insolvency presents unique challenges for international law, as there is no supranational bankruptcy court to oversee an orderly restructuring of sovereign obligations comparable to domestic insolvency regimes.", "ko": "국가 지급 불능은 국내 파산 체계에 비견할 만한 국가 채무의 질서 있는 재조정을 감독하는 초국가적 파산 법원이 없기 때문에 국제법에 독특한 도전을 제기한다."},
        {"situation": "중소기업 경영 위기", "en": "Insolvency practitioners observed that the majority of small business failures were preceded by a recognizable pattern of delayed creditor payments, depletion of working capital, and progressive deterioration in cash flow.", "ko": "파산 실무자들은 중소기업 도산의 대부분이 채권자 지급 지연, 운전 자본 고갈, 현금 흐름의 점진적 악화라는 인식 가능한 패턴에 의해 선행되었다고 관찰했다."},
        {"situation": "은행 지급 불능 감독", "en": "Banking supervisors are empowered to initiate resolution proceedings for systemically important financial institutions before technical insolvency, precisely to prevent disorderly failure from transmitting systemic risk.", "ko": "금융 감독 당국은 무질서한 실패가 체계적 위험을 전파하는 것을 방지하기 위해, 기술적 지급 불능 이전에 시스템적으로 중요한 금융 기관에 대한 정리 절차를 개시할 권한을 부여받았다."},
        {"situation": "사기와 기업 파산 연관", "en": "Forensic accountants examining the insolvency uncovered a sophisticated scheme under which intercompany transactions had been used to siphon profits to related-party entities, deliberately concealing the deteriorating financial position.", "ko": "지급 불능을 조사하는 법의학 회계사들은 관련 당사자 법인에 이익을 빼돌리고 악화되는 재정 상황을 의도적으로 숨기기 위해 내부 거래가 사용된 정교한 계획을 발견했다."},
    ],
    131: [  # lien
        {"situation": "부동산 담보권 설정", "en": "The contractor filed a mechanics' lien against the property after the developer failed to remit payment for completed construction work, thereby securing a priority claim on the property's value.", "ko": "시공사는 개발업자가 완료된 공사에 대한 대금 지급을 하지 않자 부동산에 대해 공사 유치권을 제기하여, 부동산 가치에 대한 우선 청구권을 확보했다."},
        {"situation": "세금 체납 징수 수단", "en": "The revenue authority placed a tax lien on all of the delinquent taxpayer's real and personal property, effectively preventing any disposition of assets until the outstanding tax liability was fully satisfied.", "ko": "세무 당국은 미납 세금 부채가 완전히 충족될 때까지 자산의 어떠한 처분도 사실상 방지하기 위해 체납 납세자의 모든 부동산 및 동산에 세금 유치권을 설정했다."},
        {"situation": "선박 유치권 해사법", "en": "Under maritime law, maritime liens arise automatically by operation of law and attach directly to the vessel itself, giving service providers priority claims superior to most other security interests in the ship.", "ko": "해사법에 따르면, 해사 유치권은 법 작용에 의해 자동으로 발생하며 선박 자체에 직접 부착되어, 서비스 제공자들에게 선박의 대부분의 다른 담보권보다 우월한 우선 청구권을 부여한다."},
        {"situation": "변호사 수임료 보전 수단", "en": "Attorneys may assert a retaining lien over client documents and files until their professional fees are paid, though the exercise of this right must be balanced against the client's interest in continuing legal representation.", "ko": "변호사들은 전문적 수임료가 지급될 때까지 의뢰인의 문서와 파일에 대해 보유 유치권을 주장할 수 있지만, 이 권리의 행사는 계속적인 법적 대리에 대한 의뢰인의 이익과 균형을 이루어야 한다."},
        {"situation": "항공기 담보 금융", "en": "Aircraft financing typically involves a first priority security lien granted to the lending bank, with comprehensive insurance assignments and lease assignments as additional collateral protecting the lender's interest.", "ko": "항공기 금융은 일반적으로 대출 은행에 부여된 제1순위 담보 유치권과 함께 대주의 이익을 보호하는 추가 담보로서 포괄적인 보험 양도 및 임대 양도를 포함한다."},
    ],
    133: [  # litigation
        {"situation": "특허 분쟁 전략", "en": "Patent litigation has become a competitive tool in the technology sector, with well-resourced incumbents using the high cost of defense to deter smaller rivals from entering markets with competing innovations.", "ko": "특허 소송은 기술 분야에서 경쟁 도구가 되었으며, 자원이 풍부한 기존 기업들은 방어의 높은 비용을 이용하여 소규모 경쟁자들이 경쟁 혁신으로 시장에 진입하는 것을 억제한다."},
        {"situation": "집단 소송 사회적 기능", "en": "Class action litigation serves an important access-to-justice function by enabling individuals with small-value claims to aggregate their interests and pursue remedies that would be economically impractical on an individual basis.", "ko": "집단 소송은 소액 청구권을 가진 개인들이 이익을 집합하여 개인적으로는 경제적으로 비현실적인 구제책을 추구할 수 있게 함으로써 중요한 사법 접근 기능을 수행한다."},
        {"situation": "기업 법무 비용 관리", "en": "The general counsel's decision to pursue an early settlement rather than protracted litigation was driven by a calculation that the reputational costs of a public trial exceeded the financial exposure of the proposed settlement amount.", "ko": "장기간 소송보다 조기 합의를 추구하려는 법무 책임자의 결정은 공개 재판의 평판 비용이 제안된 합의 금액의 재정적 노출을 초과한다는 계산에 의해 이루어졌다."},
        {"situation": "환경 권리 소송 전략", "en": "Environmental litigation has emerged as a critical mechanism for holding corporations and governments accountable for climate change-related harms where legislative and regulatory processes have proven inadequate.", "ko": "환경 소송은 입법 및 규제 절차가 부적절한 것으로 판명된 곳에서 기후 변화 관련 피해에 대해 기업과 정부의 책임을 묻는 중요한 메커니즘으로 부상했다."},
        {"situation": "소송 금융 시장 성장", "en": "The growth of third-party litigation funding has enabled meritorious claims with limited immediate resources to proceed, though critics argue the practice creates problematic conflicts of interest in litigation decision-making.", "ko": "제3자 소송 자금 지원의 성장은 즉각적인 자원이 제한된 장점 있는 청구가 진행될 수 있게 했지만, 비평가들은 이 관행이 소송 의사결정에 문제적인 이해 충돌을 만든다고 주장한다."},
    ],
    136: [  # malfeasance
        {"situation": "공직자 부정 행위", "en": "The parliamentary inquiry found evidence of systematic malfeasance in the procurement division, where officials had steered contracts to companies in which they held undisclosed financial interests.", "ko": "의회 조사에서 구매 부서의 체계적인 부정 행위 증거가 발견되었는데, 공무원들이 미공개 재정적 이해관계를 가진 회사들로 계약을 유도했다."},
        {"situation": "금융 기관 내부 비위", "en": "The regulatory investigation into the bank's trading floor uncovered extensive malfeasance, including the systematic front-running of large institutional client orders for the proprietary account's benefit.", "ko": "은행의 트레이딩 플로어에 대한 규제 조사에서 광범위한 부정 행위가 밝혀졌는데, 이는 자기 계정의 이익을 위해 대형 기관 고객 주문을 체계적으로 앞질러 거래한 것을 포함했다."},
        {"situation": "의료 전문가 위법 행위", "en": "The medical board's investigation substantiated allegations of clinical malfeasance against the surgeon, finding that he had knowingly performed unnecessary procedures on vulnerable patients for financial gain.", "ko": "의료 위원회의 조사에서 외과 의사에 대한 임상적 부정 행위 의혹이 확인되었으며, 그가 재정적 이익을 위해 취약한 환자들에게 고의로 불필요한 시술을 시행했다는 것이 밝혀졌다."},
        {"situation": "선거 관리 부정 행위", "en": "International election observers documented widespread electoral malfeasance, including deliberate miscount of ballots, intimidation of opposition monitors, and unlawful exclusion of eligible voters from polling stations.", "ko": "국제 선거 참관인들은 투표용지의 의도적 오계산, 야당 참관인 위협, 적격 유권자의 투표소 불법 배제를 포함한 광범위한 선거 부정 행위를 기록했다."},
        {"situation": "학술 출판 비위", "en": "The retraction of the landmark paper was necessitated by the discovery of malfeasance in the data collection phase, with multiple research assistants having fabricated observations to meet the investigator's predetermined expectations.", "ko": "복수의 연구 보조원이 수석 연구원의 미리 정해진 기대를 충족시키기 위해 관찰을 조작했다는 데이터 수집 단계의 부정 행위가 발견됨에 따라 획기적인 논문의 철회가 필요하게 되었다."},
    ],
    140: [  # moratorium
        {"situation": "부채 상환 유예 선언", "en": "The government declared a sixty-day moratorium on debt repayments to international creditors, seeking to buy time for a comprehensive restructuring agreement to be negotiated before default became inevitable.", "ko": "정부는 디폴트가 불가피해지기 전에 포괄적인 구조조정 협약이 협상될 시간을 확보하기 위해 국제 채권자들에 대한 채무 상환에 60일 유예를 선언했다."},
        {"situation": "개발 사업 일시 중지", "en": "The municipal government imposed a development moratorium on the coastal zone pending completion of a comprehensive environmental carrying capacity assessment and public consultation process.", "ko": "지방 정부는 포괄적인 환경 수용 능력 평가와 공공 협의 절차가 완료될 때까지 해안 지역에 개발 유예를 부과했다."},
        {"situation": "핵 실험 국제 합의", "en": "The informal moratorium on nuclear testing adopted by the major powers since the 1990s lacks the binding legal force of a comprehensive test ban treaty but has nevertheless substantially constrained proliferation activities.", "ko": "1990년대부터 주요 강대국들이 채택한 핵 실험에 대한 비공식 유예는 포괄적 실험 금지 조약의 구속력 있는 법적 효력이 없지만, 그럼에도 확산 활동을 상당히 제한해왔다."},
        {"situation": "유전자 편집 연구 제한", "en": "The international scientific community called for a voluntary moratorium on heritable human genome editing until appropriate regulatory frameworks and ethical guidelines could be developed through broad societal deliberation.", "ko": "국제 과학계는 광범위한 사회적 숙의를 통해 적절한 규제 체계와 윤리 지침이 마련될 때까지 유전 가능한 인간 게놈 편집에 대한 자발적 유예를 촉구했다."},
        {"situation": "퇴거 금지 팬데믹 정책", "en": "The eviction moratorium imposed during the pandemic prevented mass homelessness among rent-deprived tenants, though it simultaneously created significant financial hardship for small landlords without institutional support mechanisms.", "ko": "팬데믹 동안 부과된 퇴거 유예는 임차료를 내지 못하는 임차인들 사이의 대규모 노숙을 방지했지만, 동시에 제도적 지원 메커니즘 없이 소규모 임대인들에게 상당한 재정적 어려움을 야기했다."},
    ],
    142: [  # nuance
        {"situation": "번역의 의미 세부 차이", "en": "The translator's challenge lay in rendering the nuanced emotional register of the original text, where the author had deployed subtle lexical distinctions to convey states of grief that resist easy classification.", "ko": "번역가의 과제는 저자가 쉽게 분류되지 않는 슬픔의 상태를 전달하기 위해 미묘한 어휘적 구별을 활용한 원본 텍스트의 미묘한 감정적 뉘앙스를 재현하는 데 있었다."},
        {"situation": "정책 해석 복잡성", "en": "The policy brief urged decision-makers to resist simplistic interpretations of the data and instead engage with the nuances of regional variation that the aggregate statistics necessarily obscure.", "ko": "정책 브리핑은 의사 결정자들이 데이터에 대한 단순화된 해석을 거부하고, 집계 통계가 필연적으로 가리는 지역적 차이의 뉘앙스에 대신 참여할 것을 촉구했다."},
        {"situation": "법적 판단의 미묘한 차이", "en": "The dissenting opinion argued that the majority had failed to appreciate the legal nuances distinguishing the present case from the precedents on which it purported to rely.", "ko": "반대 의견은 다수 의견이 인용하고자 하는 선례들과 현재 사건을 구별하는 법적 뉘앙스를 평가하지 못했다고 주장했다."},
        {"situation": "문화 간 커뮤니케이션", "en": "Intercultural communication training emphasizes sensitivity to pragmatic nuance, recognizing that the same linguistic forms may carry radically different illocutionary force across cultural contexts.", "ko": "문화 간 소통 교육은 화용론적 뉘앙스에 대한 민감성을 강조하며, 동일한 언어적 형식이 문화적 맥락에 따라 근본적으로 다른 발화 수반적 힘을 가질 수 있음을 인식한다."},
        {"situation": "AI 감정 분석 한계", "en": "Natural language processing systems still struggle to reliably detect irony, understatement, and other forms of pragmatic nuance that human readers process automatically through sophisticated contextual inference.", "ko": "자연어 처리 시스템은 인간 독자들이 정교한 맥락적 추론을 통해 자동으로 처리하는 아이러니, 절제 표현 및 다른 형태의 화용론적 뉘앙스를 아직도 신뢰할 수 있게 감지하는 데 어려움을 겪는다."},
    ],
    143: [  # obligor
        {"situation": "채무 발행자 의무", "en": "As the primary obligor under the bond indenture, the corporation bore unconditional responsibility for making all scheduled interest and principal payments regardless of its operational cash flow position.", "ko": "사채 계약서의 주요 채무자로서, 그 기업은 운영 현금 흐름 상태와 관계없이 예정된 모든 이자 및 원금 지급에 대한 무조건적인 책임을 졌다."},
        {"situation": "연금 의무 기업 부담", "en": "The acquiring company assumed the position of obligor for all pre-existing pension liabilities, a contingent obligation whose ultimate magnitude depended on actuarial assumptions about mortality and investment returns.", "ko": "인수 기업은 기존의 모든 연금 부채에 대한 채무자의 지위를 인수했으며, 이 우발적 의무의 궁극적 규모는 사망률과 투자 수익에 관한 보험계리적 가정에 달려 있었다."},
        {"situation": "보증 계약 법적 분석", "en": "In a guarantee transaction, the primary obligor remains liable for the underlying debt while the guarantor's obligation is secondary, triggered only upon the principal debtor's default and exhaustion of remedies against it.", "ko": "보증 거래에서 주요 채무자는 기초 채무에 대해 여전히 책임을 지는 반면, 보증인의 의무는 주채무자의 채무 불이행과 그에 대한 구제책 소진 시에만 촉발되는 부차적인 것이다."},
        {"situation": "부동산 임대 양도 책임", "en": "The original lessee remained a contingent obligor even after assigning the lease to a third party, as the landlord had not released the assignor from the obligations of the original tenancy agreement.", "ko": "집주인이 양도인을 원래 임대 계약의 의무에서 면제하지 않았기 때문에, 원래 임차인은 제3자에게 임대를 양도한 후에도 우발적 채무자로 남았다."},
        {"situation": "국제 조약 이행 의무국", "en": "The treaty designates each signatory state as a direct obligor to other states parties, creating reciprocal legal obligations that are enforceable through the dispute settlement mechanisms established by the treaty itself.", "ko": "조약은 각 서명 국가를 다른 당사국들에 대한 직접적인 채무국으로 지정하며, 조약 자체가 확립한 분쟁 해결 메커니즘을 통해 집행 가능한 상호적 법적 의무를 만들어낸다."},
    ],
    146: [  # ordinance
        {"situation": "지방 환경 규제", "en": "The city council enacted an ordinance prohibiting single-use plastic packaging in retail establishments, a local measure that went substantially further than the state's environmental regulations in addressing plastic pollution.", "ko": "시 의회는 소매 시설에서 일회용 플라스틱 포장을 금지하는 조례를 제정했는데, 이 지역 조치는 플라스틱 오염 해결에 있어 주의 환경 규정보다 훨씬 더 나아간 것이었다."},
        {"situation": "야간 소음 규제 집행", "en": "The noise ordinance established different permissible decibel thresholds for residential and commercial zones, with enforcement authority delegated to the municipal environmental health department.", "ko": "소음 조례는 주거 지역과 상업 지역에 대해 서로 다른 허용 가능한 데시벨 기준을 확립했으며, 집행 권한은 지방 환경 보건 부서에 위임되었다."},
        {"situation": "토지 이용 구역 지정", "en": "The zoning ordinance designated large portions of the waterfront as mixed-use development zones, a classification intended to activate underutilized industrial land while preserving public access to the shoreline.", "ko": "지역 구분 조례는 수변의 넓은 부분을 복합 용도 개발 구역으로 지정했는데, 이 분류는 해안선에 대한 공공 접근을 보전하면서 저활용 산업 용지를 활성화하기 위한 것이었다."},
        {"situation": "역사 보전 건물 규정", "en": "Under the historic preservation ordinance, property owners in designated conservation areas must obtain prior approval from the heritage committee before undertaking any modifications to exterior architectural features.", "ko": "역사 보전 조례에 따르면, 지정된 보존 지역의 재산 소유자들은 외부 건축 특징에 어떠한 수정을 가하기 전에 문화유산 위원회의 사전 승인을 받아야 한다."},
        {"situation": "공중 보건 비상 조치", "en": "Acting under emergency powers, the mayor issued an ordinance mandating the temporary closure of indoor dining establishments to contain the spread of the infectious disease through aerosol transmission pathways.", "ko": "비상 권한에 따라 행동하는 시장은 에어로졸 전파 경로를 통한 전염병 확산을 억제하기 위해 실내 식당 시설의 임시 폐쇄를 의무화하는 조례를 발령했다."},
    ],
    148: [  # paradigm
        {"situation": "과학 혁명 이론 변화", "en": "Kuhn's analysis of paradigm shifts demonstrates that scientific revolutions do not proceed through linear accumulation of evidence but through the replacement of entire conceptual frameworks that can no longer accommodate anomalous findings.", "ko": "쿤의 패러다임 전환 분석은 과학 혁명이 증거의 선형적 축적을 통해 진행되는 것이 아니라, 더 이상 이례적 발견을 수용할 수 없는 전체 개념적 체계의 대체를 통해 진행된다는 것을 보여준다."},
        {"situation": "경제 이론 패러다임 전환", "en": "The 2008 financial crisis precipitated a fundamental reassessment of the dominant neoliberal paradigm, exposing the inadequacy of efficient market assumptions in accounting for systemic financial instability.", "ko": "2008년 금융 위기는 체계적 금융 불안정성을 설명하는 데 있어 효율적 시장 가정의 부적절함을 드러내며, 지배적인 신자유주의 패러다임에 대한 근본적인 재평가를 촉발했다."},
        {"situation": "의학 연구 방법론 전환", "en": "The evidence-based medicine paradigm fundamentally transformed clinical practice by privileging randomized controlled trial data over clinical intuition and anecdotal experience in determining optimal treatment protocols.", "ko": "근거 중심 의학 패러다임은 최적의 치료 프로토콜 결정에 있어 임상적 직관과 일화적 경험보다 무작위 대조 시험 데이터를 우선시함으로써 임상 관행을 근본적으로 변화시켰다."},
        {"situation": "교육 제도 혁신", "en": "The shift from a transmission-based to a constructivist paradigm in education theory reflects a fundamental reconceptualization of the learner as an active agent who constructs meaning rather than a passive recipient of information.", "ko": "교육 이론에서 전달 기반에서 구성주의 패러다임으로의 전환은 학습자를 정보의 수동적 수용자가 아니라 의미를 구성하는 능동적 행위자로 근본적으로 재개념화한 것을 반영한다."},
        {"situation": "국제 관계 이론 비교", "en": "Realist and liberal paradigms of international relations offer fundamentally incompatible accounts of state behavior, generating persistent theoretical debates about the primacy of power versus institutions in explaining cooperative outcomes.", "ko": "국제 관계의 현실주의와 자유주의 패러다임은 국가 행동에 대해 근본적으로 양립 불가능한 설명을 제공하며, 협력적 결과를 설명하는 데 있어 권력 대 제도의 우위에 대한 지속적인 이론적 논쟁을 불러일으킨다."},
    ],
    150: [  # perpetuity
        {"situation": "영속 기금 설립", "en": "The foundation was established in perpetuity with an endowment structured to generate sufficient annual income to fund the scholarship program indefinitely through prudent investment management.", "ko": "재단은 신중한 투자 관리를 통해 무기한으로 장학금 프로그램에 자금을 지원하기에 충분한 연간 소득을 창출하도록 설계된 기금으로 영구히 설립되었다."},
        {"situation": "영구 토지 권리 문제", "en": "Fee simple absolute is the most complete form of property ownership, granting the holder the right to use, enjoy, and transfer the land in perpetuity without conditions attached by a prior grantor.", "ko": "절대적 단순 소유권은 재산 소유의 가장 완전한 형태로, 이전 양도인이 첨부한 조건 없이 토지를 영구히 사용, 향유, 양도할 권리를 소유자에게 부여한다."},
        {"situation": "재생 가능 에너지 철학", "en": "Environmental ethicists argue that sustainable development must be defined in terms of preserving natural capital in perpetuity for future generations, rather than merely optimizing consumption patterns for current populations.", "ko": "환경 윤리학자들은 지속 가능한 개발이 단순히 현재 인구를 위한 소비 패턴을 최적화하는 것이 아니라, 미래 세대를 위해 자연 자본을 영구히 보전하는 관점에서 정의되어야 한다고 주장한다."},
        {"situation": "영구 기억 디지털 아카이브", "en": "Digital preservation institutions grapple with the technical paradox of maintaining information in perpetuity across successive waves of technological obsolescence that threaten the long-term accessibility of born-digital cultural heritage.", "ko": "디지털 보존 기관들은 디지털 기반 문화 유산의 장기적 접근성을 위협하는 기술적 진부화의 연속적 파도를 거쳐 정보를 영구히 유지하는 기술적 역설과 씨름한다."},
        {"situation": "재산권 제한 법적 원칙", "en": "The rule against perpetuities is a fundamental common law principle that invalidates property interests contingent on events that may not occur within a reasonable timeframe, preventing the indefinite encumbering of land.", "ko": "영구 제한 금지 원칙은 합리적인 기간 내에 발생하지 않을 수 있는 사건에 의존하는 재산 이익을 무효화하여 토지의 무기한 부담을 방지하는 기본적인 보통법 원칙이다."},
    ],
    153: [  # prerequisite
        {"situation": "박사 과정 입학 요건", "en": "Successful completion of a master's thesis demonstrating original research capacity was established as a prerequisite for admission to the doctoral program in the department's revised admissions policy.", "ko": "독창적 연구 능력을 입증하는 석사 논문의 성공적 완성이 학과의 개정된 입학 정책에서 박사 과정 입학의 전제 조건으로 확립되었다."},
        {"situation": "경제 발전 조건 분석", "en": "Development economists debate whether strong institutional frameworks are a prerequisite for sustained economic growth or whether, conversely, economic growth itself tends to generate institutional improvement over time.", "ko": "개발 경제학자들은 강력한 제도적 체계가 지속적인 경제 성장의 전제 조건인지, 아니면 반대로 경제 성장 자체가 시간이 지남에 따라 제도적 개선을 만들어내는 경향이 있는지를 논의한다."},
        {"situation": "민주주의 안정 조건", "en": "Political theorists debate whether a robust civil society is a prerequisite for stable democratic governance or whether formal democratic institutions can themselves create the social conditions for civic participation.", "ko": "정치 이론가들은 강력한 시민 사회가 안정적인 민주적 거버넌스의 전제 조건인지, 아니면 공식적인 민주적 제도 자체가 시민 참여를 위한 사회적 조건을 만들 수 있는지를 논의한다."},
        {"situation": "기후 협약 이행 전제", "en": "Developing nations have articulated historical accountability and technology transfer as prerequisites for their acceptance of quantitative emissions reduction obligations under a future binding climate agreement.", "ko": "개발도상국들은 역사적 책임과 기술 이전을 미래의 구속력 있는 기후 협약에 따른 정량적 배출 감소 의무 수용의 전제 조건으로 표명해왔다."},
        {"situation": "의료 윤리 동의 절차", "en": "Mental competence is a fundamental prerequisite for valid informed consent in medical procedures, requiring clinicians to assess patients' decision-making capacity before proceeding with any significant therapeutic intervention.", "ko": "정신적 능력은 의료 시술에서의 유효한 충분한 정보에 기반한 동의를 위한 근본적인 전제 조건으로, 임상의들이 중요한 치료적 개입을 진행하기 전에 환자의 의사결정 능력을 평가하도록 요구한다."},
    ],
    155: [  # precedent
        {"situation": "헌법 해석 선례 구속력", "en": "The doctrine of stare decisis requires lower courts to follow binding precedent established by superior courts, ensuring the predictability and consistency of the legal system's application across similar fact patterns.", "ko": "선례 구속 원칙은 하급 법원이 상급 법원이 확립한 구속력 있는 선례를 따르도록 요구하며, 유사한 사실 패턴에 걸쳐 법체계 적용의 예측 가능성과 일관성을 보장한다."},
        {"situation": "국제법 관습 형성", "en": "The tribunal's decision, while not formally binding as precedent, carries considerable persuasive authority and will inevitably shape how future arbitrators approach analogous disputes between investor-states.", "ko": "법정의 결정은 공식적으로 구속력 있는 선례로서는 아니지만, 상당한 설득력 있는 권위를 가지며 미래의 중재자들이 투자자-국가 간의 유사한 분쟁에 접근하는 방식을 불가피하게 형성할 것이다."},
        {"situation": "외교적 선례 설정", "en": "Diplomatic historians warn that unilateral recognition of secessionist regions sets a dangerous precedent that could destabilize established international norms of territorial integrity and state sovereignty.", "ko": "외교 역사학자들은 분리주의 지역에 대한 일방적 승인이 영토 보전과 국가 주권의 확립된 국제 규범을 불안정하게 만들 수 있는 위험한 선례를 설정한다고 경고한다."},
        {"situation": "기업 거버넌스 규범 형성", "en": "The landmark settlement in the shareholder derivative suit established an important precedent for the standard of board oversight expected in cases involving complex financial products and systemic risk management.", "ko": "주주 대표 소송의 획기적인 합의는 복잡한 금융 상품과 체계적 위험 관리와 관련된 사건에서 기대되는 이사회 감독 기준에 대한 중요한 선례를 확립했다."},
        {"situation": "규제 혁신 법적 불확실성", "en": "The absence of clear regulatory precedent for novel fintech products creates substantial legal uncertainty for market participants and may inadvertently deter innovation by increasing compliance risk without corresponding consumer benefit.", "ko": "새로운 핀테크 상품에 대한 명확한 규제 선례의 부재는 시장 참여자들에게 상당한 법적 불확실성을 만들며, 해당하는 소비자 이익 없이 준수 위험을 높임으로써 의도치 않게 혁신을 억제할 수 있다."},
    ],
    156: [  # proponent
        {"situation": "원자력 에너지 지지자", "en": "Proponents of nuclear energy argue that its high energy density and low lifecycle carbon emissions make it an indispensable component of any credible strategy for decarbonizing industrial economies at scale.", "ko": "원자력 에너지 지지자들은 높은 에너지 밀도와 낮은 수명 주기 탄소 배출이 산업 경제를 대규모로 탈탄소화하는 모든 신뢰할 수 있는 전략의 불가결한 구성 요소로 만든다고 주장한다."},
        {"situation": "기본 소득 옹호론", "en": "Proponents of universal basic income contend that unconditional cash transfers would reduce bureaucratic welfare administration costs while providing a foundation upon which individuals could make economically rational choices about work and education.", "ko": "기본 소득 지지자들은 무조건적 현금 이전이 관료적 복지 행정 비용을 줄이면서 개인들이 일과 교육에 대해 경제적으로 합리적인 선택을 내릴 수 있는 기반을 제공할 것이라고 주장한다."},
        {"situation": "교육 개혁 추진 세력", "en": "The strongest proponents of comprehensive education reform were found not among established pedagogical institutions but among technology entrepreneurs who stood to benefit from a more adaptable and digitally literate workforce.", "ko": "포괄적인 교육 개혁의 가장 강력한 지지자들은 확립된 교육학적 기관들이 아니라, 더 적응력 있고 디지털 능력을 갖춘 노동력으로부터 이익을 얻을 수 있는 기술 기업가들 사이에서 발견되었다."},
        {"situation": "글로벌 거버넌스 지지", "en": "Proponents of supranational governance structures argue that many of the most pressing collective action problems, from pandemic preparedness to climate change, cannot be adequately addressed within the framework of nation-state sovereignty.", "ko": "초국가적 거버넌스 구조의 지지자들은 전염병 준비에서 기후 변화에 이르기까지 가장 긴박한 집단 행동 문제들 중 많은 것이 국민국가 주권의 체계 내에서 충분히 다루어질 수 없다고 주장한다."},
        {"situation": "학술 이론 주창자", "en": "The sociologist emerged as the leading proponent of a relational approach to poverty that situated material deprivation within broader networks of social exclusion and diminished civic participation.", "ko": "그 사회학자는 물질적 박탈을 더 광범위한 사회적 배제와 감소된 시민 참여의 네트워크 내에 위치시키는 빈곤에 대한 관계적 접근 방식의 주도적 지지자로 부상했다."},
    ],
    158: [  # procurement
        {"situation": "공공 조달 투명성", "en": "Public procurement frameworks must balance the competing imperatives of value for money, supplier diversity, and administrative efficiency while maintaining sufficient transparency to prevent corruption.", "ko": "공공 조달 체계는 부패 방지를 위해 충분한 투명성을 유지하면서 비용 대비 효용, 공급업체 다양성, 행정 효율성이라는 경쟁적 필요 사항들 사이의 균형을 맞추어야 한다."},
        {"situation": "국방 조달 비효율성", "en": "Defense procurement programs frequently suffer from cost overruns and schedule delays attributable to the inherent difficulty of specifying requirements for complex technological systems at the outset of long development cycles.", "ko": "국방 조달 프로그램은 긴 개발 주기 시작 시 복잡한 기술 시스템에 대한 요건을 명세화하는 내재적 어려움에 기인한 비용 초과와 일정 지연으로 자주 어려움을 겪는다."},
        {"situation": "지속 가능 공급망 관리", "en": "Sustainable procurement policies require organizations to integrate environmental and social criteria into their supplier selection processes, moving beyond purely price-based evaluation to encompass lifecycle impact assessments.", "ko": "지속 가능한 조달 정책은 조직들이 공급업체 선정 과정에 환경적 및 사회적 기준을 통합하도록 요구하며, 순수하게 가격 기반의 평가를 넘어 수명 주기 영향 평가를 포함한다."},
        {"situation": "의약품 국제 입찰", "en": "Centralized pharmaceutical procurement through international pooled purchasing has enabled low-income countries to negotiate substantially lower prices for essential medicines than would be achievable through individual country negotiations.", "ko": "국제 공동 구매를 통한 중앙화된 의약품 조달은 저소득 국가들이 개별 국가 협상을 통해 달성할 수 있는 것보다 필수 의약품에 대해 상당히 낮은 가격을 협상할 수 있게 해주었다."},
        {"situation": "디지털 정부 서비스 구매", "en": "Government digital service procurement has been criticized for favoring established technology incumbents over innovative smaller suppliers, creating barriers that slow the adoption of more efficient and cost-effective solutions.", "ko": "정부 디지털 서비스 조달은 혁신적인 소규모 공급업체보다 확립된 기술 기업을 선호한다는 비판을 받아왔으며, 더 효율적이고 비용 효과적인 솔루션의 채택을 늦추는 장벽을 만들었다."},
    ],
    161: [  # proxy
        {"situation": "주주총회 의결권 위임", "en": "Institutional investors increasingly exercise proxy voting rights as a mechanism for engaging with portfolio companies on governance deficiencies, executive compensation, and long-term sustainability strategy.", "ko": "기관 투자자들은 거버넌스 결함, 임원 보수, 장기 지속 가능성 전략에 관해 포트폴리오 기업들과 관여하는 메커니즘으로 의결권 대리 행사를 점점 더 활용하고 있다."},
        {"situation": "사이버 공격 익명성", "en": "Geopolitical analysts noted that the attack had been conducted through a network of proxy servers designed to obfuscate the true origin and prevent attribution to the suspected state-sponsored threat actor.", "ko": "지정학적 분석가들은 공격이 진정한 출처를 불분명하게 하고 의심되는 국가 지원 위협 행위자에 대한 귀인을 방지하도록 설계된 프록시 서버 네트워크를 통해 수행되었다고 지적했다."},
        {"situation": "간접 지표로서의 데이터", "en": "In the absence of direct measurements of subjective wellbeing, researchers used life expectancy and infant mortality as proxy indicators, acknowledging that these metrics capture only partial dimensions of human flourishing.", "ko": "주관적 행복의 직접적인 측정값이 없는 상황에서, 연구자들은 기대 수명과 영아 사망률을 대리 지표로 사용했으며, 이 지표들이 인간 번영의 부분적인 차원만을 포착한다는 것을 인정했다."},
        {"situation": "위임 전쟁 분석", "en": "Cold War history is replete with examples of proxy conflicts in which the superpowers pursued their strategic objectives through support for local belligerents, thereby avoiding direct military confrontation.", "ko": "냉전 역사는 초강대국들이 직접적인 군사적 대결을 피하면서 지역 교전국들에 대한 지원을 통해 전략적 목표를 추구한 대리 분쟁의 사례들로 가득하다."},
        {"situation": "환경 측정 대리 변수", "en": "Climate researchers employed tree ring width as a proxy for historical temperature variations, recognizing that while the measure has well-established limitations, it provides otherwise inaccessible data extending over millennia.", "ko": "기후 연구자들은 역사적 기온 변동의 대리 지표로 나무 나이테 너비를 사용했으며, 이 측정값에 잘 알려진 한계가 있음을 인식하면서도 그것이 수천 년에 걸쳐 다른 방법으로는 접근할 수 없는 데이터를 제공한다는 것을 인정했다."},
    ],
    163: [  # quantum
        {"situation": "손해배상 금액 산정", "en": "The tribunal's determination of the quantum of damages required a complex assessment of future lost profits discounted to present value using a risk-adjusted cost of capital specific to the industry sector.", "ko": "법원의 손해배상 금액 결정은 해당 산업 부문에 특정한 위험 조정된 자본 비용을 사용하여 현재 가치로 할인된 미래 손실 이익에 대한 복잡한 평가를 필요로 했다."},
        {"situation": "양자역학 물리학 혁명", "en": "The quantum theory of radiation proposed by Planck fundamentally challenged the classical assumption of energy continuity, demonstrating instead that energy is exchanged in discrete quanta whose size is proportional to frequency.", "ko": "플랑크가 제안한 복사의 양자 이론은 에너지가 빈도에 비례하는 크기의 불연속적인 양자로 교환된다는 것을 입증하며, 에너지 연속성에 대한 고전적 가정에 근본적으로 도전했다."},
        {"situation": "법적 구제 수단 범위", "en": "The court's equitable jurisdiction enables it to award a quantum of relief calibrated to the precise extent of the unjust enrichment, rather than being constrained to the all-or-nothing outcomes of common law remedies.", "ko": "법원의 형평법적 관할권은 보통법 구제수단의 전부 또는 전무 결과에 제한되지 않고, 부당 이득의 정확한 범위에 맞게 조정된 구제 금액을 판결할 수 있게 한다."},
        {"situation": "정보 이론 단위 분석", "en": "In quantum computing, the qubit represents the fundamental quantum of information, exploiting superposition and entanglement to achieve computational capabilities exponentially superior to classical binary systems.", "ko": "양자 컴퓨팅에서 큐비트는 정보의 기본 양자 단위를 나타내며, 고전적 이진 시스템보다 기하급수적으로 우월한 계산 능력을 달성하기 위해 중첩과 얽힘을 활용한다."},
        {"situation": "형사 선고 비례성", "en": "Sentencing theory grapples with determining the appropriate quantum of punishment that is both proportionate to the gravity of the offence and sufficient to deter future criminal conduct.", "ko": "양형 이론은 범죄의 중대성에 비례하고 미래의 범죄 행위를 억제하기에 충분한 적절한 처벌 수준을 결정하는 문제와 씨름한다."},
    ],
    164: [  # rationale
        {"situation": "정책 근거 공개 의무", "en": "Administrative law requires agencies to articulate a clear and reasoned rationale for their regulatory decisions, enabling judicial review to assess whether the action was arbitrary or capricious.", "ko": "행정법은 기관들이 규제 결정에 대해 명확하고 합리적인 근거를 표명하도록 요구하며, 사법 심사가 그 행위가 자의적이거나 변덕스러운 것인지를 평가할 수 있게 한다."},
        {"situation": "학술 연구 방법론 선택", "en": "The methodology section must provide a coherent rationale for the research design choices made, demonstrating that the selected methods are adequate to the theoretical claims being advanced.", "ko": "방법론 섹션은 이루어진 연구 설계 선택에 대한 일관된 근거를 제공해야 하며, 선택된 방법들이 제시되는 이론적 주장에 충분하다는 것을 입증해야 한다."},
        {"situation": "기업 전략 근거 제시", "en": "The board required management to present a compelling strategic rationale for the proposed divestiture that went beyond short-term financial metrics to address the long-term competitive positioning of the remaining business.", "ko": "이사회는 경영진이 남은 사업의 장기적 경쟁 포지셔닝을 다루기 위해 단기적 재무 지표를 넘어서는 제안된 매각에 대한 설득력 있는 전략적 근거를 제시할 것을 요구했다."},
        {"situation": "형사 처벌 이론적 근거", "en": "Retributive theories of punishment provide a rationale grounded in desert and proportionality, while consequentialist approaches justify penal sanctions by reference to their deterrent and rehabilitative effects.", "ko": "응보적 처벌 이론은 응보와 비례성에 근거한 근거를 제공하는 반면, 결과주의적 접근법은 억제 및 재활 효과를 근거로 형사 제재를 정당화한다."},
        {"situation": "의학 치료 지침 기반", "en": "The clinical guidelines committee provided a detailed rationale for departing from previous recommendations, citing the strength of evidence from three independent systematic reviews that reversed earlier findings.", "ko": "임상 지침 위원회는 이전 발견들을 뒤집은 세 가지 독립적인 체계적 검토의 증거 강도를 인용하며, 이전 권고사항에서 벗어나는 것에 대한 상세한 근거를 제시했다."},
    ],
    165: [  # recapitalization
        {"situation": "은행 위기 구제 수단", "en": "The emergency recapitalization of the failing bank was structured as a bail-in rather than a bailout, requiring subordinated bondholders to absorb losses before any public funds were deployed.", "ko": "파산 직전 은행의 긴급 자본 재조정은 어떠한 공공 자금이 투입되기 전에 후순위 채권 보유자들이 손실을 흡수하도록 요구하는 구제금융이 아닌 내부 구제금융으로 구조화되었다."},
        {"situation": "레버리지 바이아웃 구조", "en": "The private equity firm executed a leveraged recapitalization, extracting a substantial dividend by loading the target with additional debt while retaining operational control of the business.", "ko": "사모펀드 기업은 사업 운영 통제권을 유지하면서 피인수 기업에 추가적인 부채를 부담시켜 상당한 배당금을 추출하는 레버리지 자본 재조정을 실행했다."},
        {"situation": "기업 부채 구조 최적화", "en": "Management pursued a recapitalization strategy that replaced expensive high-yield debt with cheaper investment-grade bonds, significantly reducing the company's interest burden and improving its creditworthiness.", "ko": "경영진은 값비싼 고수익 채권을 더 저렴한 투자 등급 채권으로 대체하여 회사의 이자 부담을 크게 줄이고 신용도를 향상시키는 자본 재조정 전략을 추구했다."},
        {"situation": "국영기업 민영화 준비", "en": "As a precursor to privatization, the government undertook a comprehensive recapitalization of the state-owned utility, writing off accumulated losses and injecting equity to establish a commercially viable balance sheet.", "ko": "민영화의 전구체로서, 정부는 상업적으로 실행 가능한 대차대조표를 확립하기 위해 누적 손실을 상각하고 지분을 투입하는 국영 공익 기업의 포괄적인 자본 재조정을 수행했다."},
        {"situation": "스타트업 성장 단계 전환", "en": "The series C recapitalization restructured the company's equity, retiring early convertible notes and establishing a clean cap table that would be more attractive to institutional investors in a potential future public offering.", "ko": "시리즈 C 자본 재조정은 초기 전환 사채를 상환하고 잠재적 미래 공개 상장에서 기관 투자자들에게 더 매력적일 깔끔한 주주 구성표를 확립하여 회사의 지분을 재구조화했다."},
    ],
    167: [  # recourse
        {"situation": "비소구 금융 구조", "en": "Non-recourse project financing limits the lender's claim to the project's assets and cash flows, insulating the sponsoring companies from direct liability in the event the project fails to generate sufficient revenue.", "ko": "비소구 프로젝트 금융은 대주의 청구를 프로젝트의 자산과 현금 흐름으로 제한하여, 프로젝트가 충분한 수익을 창출하지 못하는 경우 스폰서 기업들이 직접적인 책임에서 보호받도록 한다."},
        {"situation": "법적 구제 수단 소진", "en": "International human rights law typically requires petitioners to exhaust all available domestic recourse before invoking the jurisdiction of international treaty bodies, ensuring that national systems have the first opportunity to remedy violations.", "ko": "국제 인권법은 일반적으로 청원자들이 국제 조약 기구의 관할권을 발동하기 전에 이용 가능한 모든 국내 구제 수단을 소진하도록 요구하여, 국가 체계가 위반을 구제할 첫 번째 기회를 갖도록 보장한다."},
        {"situation": "소비자 불만 처리 채널", "en": "Effective consumer protection regimes must provide accessible and affordable recourse mechanisms that allow individuals to seek remedies for commercial grievances without disproportionate transaction costs.", "ko": "효과적인 소비자 보호 체계는 개인들이 불균형적인 거래 비용 없이 상업적 불만에 대한 구제를 구할 수 있게 하는 접근 가능하고 저렴한 구제 메커니즘을 제공해야 한다."},
        {"situation": "어음 소구권 행사", "en": "The holder of a dishonored bill of exchange may exercise recourse against prior endorsers in the order of their endorsement, proceeding up the chain of liability until the face value is recovered.", "ko": "부도난 환어음의 소지인은 액면가가 회수될 때까지 배서 순서에 따라 이전 배서인들에 대해 소구권을 행사하며 책임 사슬을 거슬러 올라갈 수 있다."},
        {"situation": "외교적 해결 방법 모색", "en": "When direct bilateral negotiations fail, states have recourse to a range of peaceful dispute settlement mechanisms under international law, from mediation and conciliation to binding adjudication before international courts.", "ko": "직접적인 양자 협상이 실패할 때, 국가들은 국제법에 따라 조정과 화해에서 국제 법원 앞에서의 구속력 있는 재판까지 다양한 평화적 분쟁 해결 메커니즘에 호소할 수 있다."},
    ],
    172: [  # remuneration
        {"situation": "임원 보수 지배구조", "en": "Shareholder activism has increasingly targeted excessive executive remuneration packages, demanding stronger linkage between pay and long-term performance metrics rather than short-term earnings management.", "ko": "주주 행동주의는 단기적 수익 관리보다 보수와 장기적 성과 지표 간의 더 강한 연계를 요구하며, 과도한 임원 보수 패키지를 점점 더 표적으로 삼고 있다."},
        {"situation": "공정 임금 국제 기준", "en": "The ILO's conventions on equitable remuneration establish that workers performing work of equal value should receive equal pay, regardless of gender, ethnicity, or other characteristics protected under international human rights law.", "ko": "공정한 보수에 관한 국제노동기구(ILO) 협약은 동등한 가치의 업무를 수행하는 근로자가 국제 인권법에 의해 보호되는 성별, 민족성 또는 기타 특성에 관계없이 동등한 임금을 받아야 한다고 확립한다."},
        {"situation": "금융업 성과 보수 규제", "en": "Post-crisis banking regulations introduced mandatory deferral and clawback provisions for variable remuneration components, aligning bankers' financial incentives more closely with the long-term risk profile of their trading activities.", "ko": "위기 후 은행 규정은 변동 보수 구성 요소에 대한 의무적 이연 및 환수 조항을 도입하여, 은행원들의 재정적 인센티브를 자신들의 거래 활동의 장기적 위험 프로파일에 더 긴밀하게 연계시켰다."},
        {"situation": "자원봉사 활동 비금전 보상", "en": "While volunteers receive no monetary remuneration, the non-financial benefits of meaningful work, social connection, and skill development represent a form of psychic income that sustains long-term participation in civic organizations.", "ko": "자원봉사자들은 금전적 보수를 받지 않지만, 의미 있는 업무, 사회적 연결, 기술 개발의 비재정적 혜택들은 시민 단체에서의 장기적 참여를 지속시키는 일종의 정신적 소득을 나타낸다."},
        {"situation": "지식재산 창작자 보상 체계", "en": "Copyright law establishes a remuneration framework that attempts to balance creators' legitimate claims to financial reward against society's interest in maintaining access to and building upon the accumulated stock of human knowledge.", "ko": "저작권법은 창작자의 재정적 보상에 대한 정당한 청구권과 인간 지식의 축적된 자산에 대한 접근성을 유지하고 그 위에 구축할 수 있는 사회의 이익 사이의 균형을 도모하는 보수 체계를 확립한다."},
    ],
    173: [  # repercussion
        {"situation": "정책 의도치 않은 결과", "en": "The repercussions of the hasty welfare reform extended far beyond the intended beneficiary group, disrupting labor market dynamics, straining municipal social service systems, and exacerbating regional economic inequalities.", "ko": "성급한 복지 개혁의 파급 효과는 의도된 수혜자 집단을 훨씬 넘어, 노동 시장 역학을 혼란시키고, 지방 사회 서비스 시스템에 부담을 주며, 지역 경제 불평등을 악화시켰다."},
        {"situation": "금융 위기 전염 효과", "en": "The repercussions of the banking collapse rapidly propagated through the real economy, as credit contraction forced corporate investment cutbacks, accelerated unemployment, and suppressed household consumption.", "ko": "은행 붕괴의 파급 효과는 신용 축소가 기업 투자 삭감을 강요하고, 실업을 가속화하며, 가계 소비를 억제함에 따라 실물 경제 전반으로 빠르게 전파되었다."},
        {"situation": "외교 분쟁 경제적 영향", "en": "Analysts warned that the diplomatic rupture would have significant repercussions for bilateral trade flows, investment confidence, and the stability of the regional economic integration framework that both countries had spent decades building.", "ko": "분석가들은 외교적 단절이 양국이 수십 년에 걸쳐 구축해온 양자 무역 흐름, 투자 신뢰도, 그리고 지역 경제 통합 체계의 안정성에 상당한 파급 효과를 미칠 것이라고 경고했다."},
        {"situation": "기술 혁신 사회 변화", "en": "The repercussions of widespread automation extend across multiple dimensions of social organization, affecting not only employment patterns but also the distribution of political power, the structure of families, and the nature of community.", "ko": "광범위한 자동화의 파급 효과는 사회 조직의 여러 차원에 걸쳐 있으며, 고용 패턴뿐만 아니라 정치 권력의 분배, 가족 구조, 공동체의 성격에도 영향을 미친다."},
        {"situation": "판결이 법체계에 미치는 영향", "en": "Constitutional scholars debated the long-term repercussions of the ruling, arguing that its expansive interpretation of executive emergency powers could fundamentally alter the balance of institutional authority under the separation of powers doctrine.", "ko": "헌법 학자들은 판결의 장기적 파급 효과를 논의하며, 행정부 비상 권한에 대한 광범위한 해석이 권력 분립 원칙에 따른 제도적 권한의 균형을 근본적으로 변화시킬 수 있다고 주장했다."},
    ],
    175: [  # rescission
        {"situation": "사기 계약 취소 청구", "en": "The court granted rescission of the contract on the grounds that the vendor had made a fraudulent misrepresentation regarding the property's planning permission status that had induced the purchaser to enter into the transaction.", "ko": "법원은 매도인이 매수인을 거래에 유인한 부동산의 건축 허가 상태에 관해 사기적 허위 표시를 했다는 이유로 계약의 취소를 인정했다."},
        {"situation": "소비자 철회권 행사", "en": "Consumer protection legislation in many jurisdictions provides a statutory right of rescission within a cooling-off period for contracts concluded at a distance or away from commercial premises.", "ko": "많은 관할권의 소비자 보호 법률은 원거리에서 또는 상업적 시설 외부에서 체결된 계약에 대해 냉각 기간 내에 법정 취소권을 제공한다."},
        {"situation": "상호 동의 계약 해지", "en": "Rather than pursuing litigation, both parties agreed to a rescission by mutual consent that would restore each to its pre-contractual position and extinguish all outstanding obligations under the agreement.", "ko": "소송을 추구하는 대신, 양 당사자는 각자를 계약 전 지위로 회복시키고 계약에 따른 모든 미결제 의무를 소멸시키는 상호 동의에 의한 계약 취소에 합의했다."},
        {"situation": "중요 사실 변경 계약 무효", "en": "The arbitrators concluded that the fundamental change in market conditions since the agreement was signed, while not constituting force majeure, provided equitable grounds for rescission of the long-term supply contract.", "ko": "중재인들은 계약 서명 이후 시장 상황의 근본적 변화가 불가항력을 구성하지는 않지만, 장기 공급 계약의 취소에 대한 형평적 근거를 제공한다는 결론을 내렸다."},
        {"situation": "정부 규제 변경 소급 취소", "en": "Legal scholars debated whether the retroactive rescission of licenses previously granted by a prior administration was consistent with principles of legitimate expectations and the rule of law.", "ko": "법학자들은 이전 행정부가 부여한 허가의 소급적 취소가 정당한 기대의 원칙 및 법치주의와 일치하는지를 논의했다."},
    ],
    178: [  # retainer
        {"situation": "법률 자문 선임 계약", "en": "The corporation placed its external counsel on retainer, providing predictable monthly billing in exchange for priority availability and agreed discounts on the firm's standard hourly rates.", "ko": "기업은 외부 법률 고문을 선임 계약으로 두어, 우선 이용 가능성과 사무소의 표준 시간당 요율에 대한 합의된 할인의 대가로 예측 가능한 월 청구를 제공했다."},
        {"situation": "전략 컨설턴트 자문 계약", "en": "The government retained a specialist retainer with the consulting firm to provide ongoing strategic advice during the critical six-month privatization process, ensuring continuity of expert support throughout the transaction.", "ko": "정부는 중요한 6개월 민영화 과정 동안 지속적인 전략적 조언을 제공하고 거래 전반에 걸쳐 전문가 지원의 연속성을 보장하기 위해 컨설팅 회사와 전문 선임 계약을 체결했다."},
        {"situation": "로비스트 고용 방식", "en": "The pharmaceutical industry's retainer arrangements with former government officials raise significant concerns about the revolving door phenomenon and the disproportionate access to regulatory decision-making that such relationships confer.", "ko": "전직 정부 관리들과의 제약 산업의 선임 계약은 회전문 현상과 그러한 관계가 부여하는 규제 의사결정에 대한 불균형적인 접근에 관한 상당한 우려를 제기한다."},
        {"situation": "연구 자문 장기 계약", "en": "The university hospital placed the specialist research consultancy on a long-term retainer to provide independent methodological oversight across all major clinical trials undertaken by the institution.", "ko": "대학 병원은 기관이 수행하는 모든 주요 임상 시험에 걸쳐 독립적인 방법론적 감독을 제공하기 위해 전문 연구 컨설팅 회사를 장기 선임 계약으로 두었다."},
        {"situation": "언론 홍보 지속 계약", "en": "The corporation's public relations retainer arrangement with the communications agency ensured rapid crisis response capacity and continuous media monitoring without the need to negotiate scope and fees during time-sensitive situations.", "ko": "커뮤니케이션 에이전시와의 기업의 홍보 선임 계약은 시간에 민감한 상황에서 범위와 수수료를 협상할 필요 없이 신속한 위기 대응 역량과 지속적인 미디어 모니터링을 보장했다."},
    ],
    183: [  # sanction
        {"situation": "국제 경제 제재 효과", "en": "Economic sanctions targeting Russia's financial sector following the invasion of Ukraine aimed to impose sufficient macroeconomic costs to alter strategic calculations without triggering a direct military confrontation between nuclear powers.", "ko": "우크라이나 침공에 따른 러시아 금융 부문을 표적으로 한 경제 제재는 핵 강대국 간의 직접적인 군사적 대결을 촉발하지 않고 전략적 계산을 변경하기에 충분한 거시경제적 비용을 부과하는 것을 목표로 했다."},
        {"situation": "스포츠 징계 처분", "en": "The anti-doping authority imposed a four-year sanction on the athlete following multiple failed tests, effectively ending the competitive career of one of the sport's most decorated champions.", "ko": "도핑 방지 당국은 복수의 검사 실패에 따라 그 선수에게 4년간의 제재를 부과했으며, 이는 사실상 그 스포츠의 가장 훈장이 많은 챔피언 중 한 명의 경쟁 경력을 종료시켰다."},
        {"situation": "법원 명령 사법 승인", "en": "The settlement required formal judicial sanction before taking effect, a procedural safeguard designed to ensure that the agreed terms were fair and adequate to protect the interests of all affected class members.", "ko": "합의가 발효되기 전에 공식적인 사법 승인이 필요했는데, 이는 합의된 조건이 모든 영향을 받는 구성원의 이익을 보호하기에 공정하고 충분한지를 보장하기 위해 설계된 절차적 안전장치였다."},
        {"situation": "직업 면허 징계 조치", "en": "The professional regulatory body's range of available sanctions extended from private reprimand and conditions on practice to temporary suspension and, in the most serious cases, permanent revocation of the practitioner's license.", "ko": "전문 규제 기관이 이용할 수 있는 제재의 범위는 비공개 견책과 실무 조건에서 일시적 정직까지, 그리고 가장 심각한 경우에는 실무자 면허의 영구적 취소까지 확대되었다."},
        {"situation": "윤리 위원회 행동 승인", "en": "The research ethics board's sanction for the proposed human subjects study was conditional upon the investigators implementing specified modifications to the consent procedures and data anonymization protocols.", "ko": "제안된 인간 피험자 연구에 대한 연구 윤리 위원회의 승인은 연구자들이 동의 절차 및 데이터 익명화 프로토콜에 대한 특정 수정 사항을 시행하는 것을 조건으로 했다."},
    ],
    185: [  # securitization
        {"situation": "주택 모기지 증권화", "en": "The securitization of residential mortgage loans into mortgage-backed securities transformed local banking from a hold-to-maturity model into an originate-to-distribute model with profound implications for credit risk allocation.", "ko": "주거용 모기지 대출의 모기지 담보 증권으로의 증권화는 지역 은행업을 만기 보유 모델에서 신용 위험 배분에 심오한 함의를 가진 발행 후 매각 모델로 변환했다."},
        {"situation": "자동차 할부금융 자산 유동화", "en": "Auto loan securitization enables lenders to recycle capital by selling pools of consumer receivables to special purpose vehicles, which fund the purchase by issuing tranched securities to capital market investors.", "ko": "자동차 대출 증권화는 대출자들이 소비자 매출 채권 풀을 특수 목적 법인에 매각하여 자본을 재활용할 수 있게 하며, 이 법인은 자본 시장 투자자들에게 트랜치 증권을 발행하여 구매 자금을 조달한다."},
        {"situation": "지식재산권 수익 유동화", "en": "Intellectual property securitization allows rights holders to monetize future royalty streams immediately by selling them to a special purpose entity that issues asset-backed notes to institutional investors.", "ko": "지식재산권 증권화는 권리 보유자들이 미래 로열티 흐름을 기관 투자자들에게 자산 담보 채권을 발행하는 특수 목적 법인에 매각함으로써 즉시 현금화할 수 있게 한다."},
        {"situation": "국가 자산 유동화 정책", "en": "Sovereign wealth funds have increasingly explored securitization as a mechanism for monetizing infrastructure assets while retaining operational control, using the proceeds to fund diversified investment portfolios.", "ko": "국부 펀드들은 운영 통제권을 유지하면서 인프라 자산을 현금화하고, 수익금을 사용하여 다각화된 투자 포트폴리오에 자금을 조달하기 위한 메커니즘으로 증권화를 점점 더 탐색하고 있다."},
        {"situation": "신용 위험 전이 분석", "en": "The structural complexity of synthetic securitization instruments, which transfer credit risk through credit default swaps rather than physical asset sales, proved particularly opaque during the 2008 financial crisis.", "ko": "물리적 자산 매각이 아닌 신용 부도 스왑을 통해 신용 위험을 이전하는 합성 증권화 상품의 구조적 복잡성은 2008년 금융 위기 동안 특히 불투명한 것으로 드러났다."},
    ],
    194: [  # subpoena
        {"situation": "의회 청문회 증거 제출", "en": "The congressional committee issued a subpoena duces tecum compelling the technology company to produce internal communications regarding its algorithmic content moderation policies for the previous three years.", "ko": "의회 위원회는 기술 회사가 지난 3년간의 알고리즘 콘텐츠 조정 정책에 관한 내부 통신을 제출하도록 강제하는 증거 제출 명령 소환장을 발부했다."},
        {"situation": "형사 재판 증인 소환", "en": "The prosecutor's office secured a subpoena requiring the reluctant witness to appear and testify at trial, after the witness had refused informal requests to cooperate with the investigation.", "ko": "검찰청은 증인이 수사 협조에 대한 비공식적 요청을 거부한 후, 마지못해 하는 증인이 재판에 출석하여 증언하도록 요구하는 소환장을 확보했다."},
        {"situation": "민사 소송 문서 제출 명령", "en": "The subpoena addressed to the accounting firm required the production of all audit workpapers, internal memoranda, and client communications relating to the defendant corporation's tax compliance for the relevant fiscal years.", "ko": "회계 법인을 대상으로 한 소환장은 해당 회계 연도 피고 기업의 세금 준수와 관련된 모든 감사 업무 문서, 내부 메모, 고객 통신의 제출을 요구했다."},
        {"situation": "언론 기자 취재원 보호", "en": "The journalist challenged the subpoena seeking to compel disclosure of confidential sources, arguing that a reporter's privilege rooted in First Amendment protections should shield newsgathering activities from prosecutorial compulsion.", "ko": "그 언론인은 기밀 취재원 공개를 강제하려는 소환장에 이의를 제기하며, 수정헌법 제1조 보호에 근거한 기자의 특권이 취재 활동을 검찰의 강제로부터 보호해야 한다고 주장했다."},
        {"situation": "외국 증거 수집 국제 협력", "en": "When seeking evidence located in foreign jurisdictions, prosecutors often resort to mutual legal assistance treaties rather than attempting to enforce domestic subpoenas extraterritorially, which may violate the foreign state's sovereignty.", "ko": "외국 관할권에 위치한 증거를 구할 때, 검사들은 외국 국가의 주권을 침해할 수 있는 국내 소환장을 역외 집행하려는 시도 대신 종종 사법 공조 조약에 의존한다."},
    ],
}

for word_id, new_exs in new_examples.items():
    if word_id in word_map:
        word_map[word_id]['examples'].extend(new_exs)

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Batch 3 done.")
with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    d2 = json.load(f)
wm2 = {w['id']: w for w in d2['words']}
for wid in sorted(new_examples.keys()):
    print(f"  id={wid} {wm2[wid]['word']}: {len(wm2[wid]['examples'])} examples")
