import json

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

words = data['words']
word_map = {w['id']: w for w in words}

new_examples = {
    197: [  # synergy
        {"situation": "기업 합병 가치 창출 분석", "en": "Investment bankers justified the premium acquisition price by projecting significant cost synergies from eliminating overlapping back-office functions and revenue synergies from cross-selling complementary product lines.", "ko": "투자 은행가들은 중복 후선 업무 기능 제거에서 발생하는 상당한 비용 시너지와 보완적 제품 라인의 교차 판매에서 발생하는 수익 시너지를 예측하며 프리미엄 인수 가격을 정당화했다."},
        {"situation": "학제간 연구 협력", "en": "The interdisciplinary research center was founded on the conviction that the synergy between computational modeling and empirical fieldwork would generate insights unavailable to either approach in isolation.", "ko": "학제간 연구 센터는 계산 모델링과 경험적 현장 연구 간의 시너지가 어느 접근법을 단독으로 사용해서는 얻을 수 없는 통찰을 만들어낼 것이라는 확신에 근거하여 설립되었다."},
        {"situation": "공공-민간 파트너십 효과", "en": "Public-private partnerships in infrastructure development can generate significant synergy when government regulatory capacity and private sector efficiency are combined to deliver outcomes neither could achieve independently.", "ko": "인프라 개발에서의 공공-민간 파트너십은 정부의 규제 역량과 민간 부문의 효율성이 결합되어 어느 쪽도 독자적으로 달성할 수 없는 결과를 제공할 때 상당한 시너지를 창출할 수 있다."},
        {"situation": "생태계 상호의존 관계", "en": "Ecologists emphasize the synergy between pollinators and flowering plants as a paradigmatic example of mutualism, where the interaction creates value for both species that neither could generate through independent strategies.", "ko": "생태학자들은 꽃가루 매개자와 꽃피는 식물 간의 시너지를 상호주의의 전형적인 예로 강조하며, 이 상호작용은 어느 종도 독자적인 전략으로 창출할 수 없는 가치를 양쪽 모두에게 만들어낸다."},
        {"situation": "도시 클러스터 혁신 효과", "en": "Silicon Valley's competitive advantage derives substantially from geographic synergy, as the concentration of talent, venture capital, and established technology firms creates knowledge spillovers that accelerate the region's innovation ecosystem.", "ko": "실리콘 밸리의 경쟁 우위는 지리적 시너지에서 상당 부분 파생되는데, 인재, 벤처 자본, 확립된 기술 회사들의 집중이 지역의 혁신 생태계를 가속화하는 지식 파급 효과를 만들어낸다."},
    ],
    199: [  # taxonomy
        {"situation": "학문 분류 체계 구축", "en": "The development of a comprehensive taxonomy of machine learning algorithms has proven challenging because the boundaries between categories are often contested and the field itself evolves too rapidly for stable classification.", "ko": "기계 학습 알고리즘의 포괄적인 분류 체계 개발은 범주 간의 경계가 종종 논쟁의 대상이 되고 분야 자체가 안정적인 분류를 위해 너무 빠르게 진화하기 때문에 어려운 것으로 입증되었다."},
        {"situation": "EU 녹색 금융 분류 기준", "en": "The EU's sustainable finance taxonomy establishes standardized criteria for classifying economic activities as environmentally sustainable, enabling investors to make informed decisions and preventing greenwashing.", "ko": "EU의 지속 가능한 금융 분류 체계는 경제 활동을 환경적으로 지속 가능하다고 분류하기 위한 표준화된 기준을 확립하여, 투자자들이 정보에 입각한 결정을 내릴 수 있게 하고 그린워싱을 방지한다."},
        {"situation": "형사 범죄 유형 분류", "en": "The proposed taxonomy of cybercrime offences sought to provide a principled conceptual framework that could serve as the basis for harmonized legislation across jurisdictions with divergent legal traditions.", "ko": "제안된 사이버 범죄 유형의 분류 체계는 서로 다른 법적 전통을 가진 관할권에 걸쳐 조화된 법률의 기반으로 작용할 수 있는 원칙적인 개념적 체계를 제공하고자 했다."},
        {"situation": "의료 질환 국제 분류", "en": "The WHO's International Classification of Diseases provides a global taxonomy for diagnostic coding that enables international comparability of health statistics and supports evidence-based resource allocation decisions.", "ko": "세계보건기구의 국제 질병 분류는 국제 건강 통계의 비교 가능성을 가능하게 하고 근거 기반 자원 배분 결정을 지원하는 진단 코딩을 위한 글로벌 분류 체계를 제공한다."},
        {"situation": "정치 이데올로기 유형화", "en": "Political scientists have proposed numerous competing taxonomies for classifying contemporary populist movements, reflecting fundamental disagreements about whether populism is better understood as an ideology, a strategy, or a discursive style.", "ko": "정치학자들은 현대 포퓰리즘 운동을 분류하기 위한 경쟁적인 다수의 분류 체계를 제안했는데, 이는 포퓰리즘이 이데올로기, 전략, 또는 담론적 스타일로 더 잘 이해되는지에 대한 근본적인 불일치를 반영한다."},
    ],
    201: [  # transparency
        {"situation": "정부 공공 정보 공개", "en": "Freedom of information legislation operationalizes the principle of governmental transparency by establishing a presumptive right of public access to official documents, subject to specified exemptions for national security and personal privacy.", "ko": "정보 공개 법률은 국가 안보 및 개인 정보 보호에 관한 특정 예외를 조건으로, 공식 문서에 대한 공공의 추정적 접근권을 확립함으로써 정부 투명성의 원칙을 구체화한다."},
        {"situation": "알고리즘 의사결정 설명 가능성", "en": "Regulatory frameworks for artificial intelligence increasingly mandate transparency requirements for high-stakes automated decision systems, requiring developers to explain how algorithms affect individuals' access to credit, employment, and public services.", "ko": "인공지능에 대한 규제 체계는 신용, 고용 및 공공 서비스에 대한 개인의 접근에 알고리즘이 어떻게 영향을 미치는지를 개발자들이 설명하도록 요구하며, 고위험 자동화 의사결정 시스템에 대한 투명성 요건을 점점 더 의무화하고 있다."},
        {"situation": "공급망 인권 실사", "en": "Corporate transparency legislation now requires large companies to disclose supply chain due diligence processes, enabling consumers, investors, and regulators to assess exposure to forced labor and other human rights risks.", "ko": "기업 투명성 법률은 이제 대기업들이 공급망 실사 과정을 공개하도록 요구하여, 소비자, 투자자, 규제 당국이 강제 노동 및 기타 인권 위험에 대한 노출을 평가할 수 있게 한다."},
        {"situation": "중앙은행 통화 정책 소통", "en": "Central bank transparency—achieved through forward guidance, published minutes, and economic projections—is designed to anchor market expectations, reduce uncertainty, and enhance the effectiveness of monetary policy transmission.", "ko": "선행 지침, 공개된 의사록, 경제 전망을 통해 달성된 중앙은행의 투명성은 시장 기대를 고정하고, 불확실성을 줄이며, 통화 정책 전달의 효과성을 향상시키기 위해 설계되었다."},
        {"situation": "선거 자금 공개 의무", "en": "Campaign finance transparency laws require the timely disclosure of donor identities and contribution amounts, enabling voters to assess potential conflicts of interest and hold elected officials accountable for their financial relationships.", "ko": "선거 운동 자금 투명성 법률은 기부자 신원과 기부 금액의 적시 공개를 요구하여, 유권자들이 잠재적 이해 충돌을 평가하고 선출된 공직자들이 재정적 관계에 대해 책임을 지도록 한다."},
    ],
    202: [  # tranche
        {"situation": "구조화 금융 위험 분리", "en": "The collateralized debt obligation was structured in tranches ranging from AAA-rated senior notes to unrated equity certificates, with credit enhancement mechanisms differentiating the risk-return profiles across the capital structure.", "ko": "부채 담보부 증권은 AAA 등급 선순위 채권에서 무등급 주식 증서에 이르는 트랜치로 구조화되었으며, 신용 보강 메커니즘이 자본 구조 전반에 걸쳐 위험-수익 프로파일을 차별화했다."},
        {"situation": "국제 구제금융 분할 지급", "en": "The IMF's standby arrangement disbursed financial assistance in quarterly tranches conditional upon the borrowing government's demonstrated compliance with agreed macroeconomic adjustment targets.", "ko": "IMF의 대기 협약은 합의된 거시경제 조정 목표에 대한 차입 정부의 입증된 준수를 조건으로 분기별 트랜치로 금융 지원을 지급했다."},
        {"situation": "인프라 채권 단계별 발행", "en": "The infrastructure project's financing was structured across multiple tranches, with the subordinated first-loss tranche absorbed by development finance institutions to crowd in private sector capital at more senior levels of the structure.", "ko": "인프라 프로젝트의 자금 조달은 여러 트랜치에 걸쳐 구조화되었으며, 후순위 최초 손실 트랜치는 구조의 더 선순위 수준에서 민간 부문 자본을 유치하기 위해 개발 금융 기관들이 흡수했다."},
        {"situation": "인수합병 조건부 대금 지급", "en": "Rather than a single closing payment, the acquisition price was allocated across three tranches, with subsequent instalments contingent upon the acquired company meeting specified revenue milestones in each of the following years.", "ko": "단일 종결 지급 대신, 인수 가격은 세 개의 트랜치에 걸쳐 배분되었으며, 이후 분할금은 인수한 회사가 이후 각 연도에서 특정 수익 마일스톤을 달성하는 것을 조건으로 했다."},
        {"situation": "국채 발행 시장 관리", "en": "The debt management office issued long-dated government bonds in tranches across multiple auction dates to manage market absorption capacity and avoid the price impact of a single large issuance.", "ko": "채무 관리 사무소는 시장 흡수 능력을 관리하고 단일 대규모 발행의 가격 영향을 피하기 위해 여러 경매 일정에 걸쳐 트랜치로 장기 국채를 발행했다."},
    ],
    204: [  # underwriting
        {"situation": "기업 공개 주식 인수", "en": "The investment bank's underwriting commitment provided the issuing company with certainty of proceeds, accepting the residual risk that market conditions might deteriorate between pricing and settlement of the initial public offering.", "ko": "투자 은행의 인수 약정은 발행 회사에 조달금에 대한 확실성을 제공했으며, 기업공개의 가격 결정과 결제 사이에 시장 상황이 악화될 수 있다는 잔여 위험을 수용했다."},
        {"situation": "보험 상품 위험 평가", "en": "Actuarial underwriting standards for life insurance products require rigorous assessment of applicants' health histories, occupational hazards, and lifestyle factors to ensure that premium pricing accurately reflects individual risk profiles.", "ko": "생명보험 상품에 대한 계리적 인수 기준은 보험료 가격이 개인 위험 프로파일을 정확하게 반영하도록 보장하기 위해 신청자의 건강 이력, 직업적 위험, 생활 방식 요인에 대한 엄격한 평가를 요구한다."},
        {"situation": "부동산 모기지 심사", "en": "Mortgage underwriting standards tightened significantly following the 2008 crisis, with lenders imposing more stringent documentation requirements and income verification procedures to reduce credit risk in new loan originations.", "ko": "모기지 인수 기준은 2008년 위기 이후 크게 강화되어, 대출자들이 신규 대출 실행에서 신용 위험을 줄이기 위해 더 엄격한 문서화 요건과 소득 검증 절차를 부과했다."},
        {"situation": "신디케이트 채권 인수단 구성", "en": "The lead underwriter assembled a syndicate of regional and international banks to distribute the sovereign bond offering across diverse investor bases, reducing concentration risk while ensuring broad market liquidity.", "ko": "주간 인수자는 집중 위험을 줄이면서 광범위한 시장 유동성을 보장하기 위해 지역 및 국제 은행들로 구성된 인수단을 구성하여 국채 발행을 다양한 투자자 기반에 걸쳐 배분했다."},
        {"situation": "재해 위험 보험 인수", "en": "Catastrophe underwriting in coastal regions has become increasingly challenging as climate-related risk models predict rising frequency and severity of extreme weather events, leading some insurers to withdraw coverage from the most exposed markets.", "ko": "기후 관련 위험 모델이 극단적 기상 현상의 빈도와 심각도 증가를 예측함에 따라 해안 지역의 재해 인수는 점점 더 어려워지고 있으며, 일부 보험사들이 가장 노출된 시장에서 보장을 철회하게 만들었다."},
    ],
    207: [  # usury
        {"situation": "고금리 대출 법적 규제", "en": "State usury laws cap interest rates on consumer loans to protect borrowers from exploitative lending, though critics argue that overly restrictive caps drive credit provision underground or entirely out of reach for high-risk borrowers.", "ko": "주 고리대금 법률은 차입자를 착취적 대출로부터 보호하기 위해 소비자 대출의 이자율 상한을 설정하지만, 비평가들은 과도하게 제한적인 상한이 신용 제공을 지하로 몰거나 고위험 차입자들의 완전한 접근 불가로 만든다고 주장한다."},
        {"situation": "역사적 종교 금융 윤리", "en": "Medieval Christian theology's prohibition of usury reflected Aristotle's view that money is barren and cannot naturally reproduce itself, a position gradually abandoned as commercial capitalism developed more sophisticated theories of capital and interest.", "ko": "중세 기독교 신학의 고리대금 금지는 돈은 불임이며 자연적으로 자신을 재생산할 수 없다는 아리스토텔레스의 견해를 반영했으며, 이 입장은 상업 자본주의가 자본과 이자에 대한 더 정교한 이론을 발전시킴에 따라 점차 포기되었다."},
        {"situation": "이슬람 금융 이자 금지", "en": "Islamic finance prohibits riba, the Arabic concept corresponding broadly to usury, requiring financial products to be structured around asset ownership, profit-sharing, and risk participation rather than fixed interest obligations.", "ko": "이슬람 금융은 고리대금과 대체로 일치하는 아랍어 개념인 리바를 금지하며, 금융 상품이 고정 이자 의무 대신 자산 소유권, 이익 공유, 위험 참여를 중심으로 구조화되도록 요구한다."},
        {"situation": "마이크로파이낸스 윤리 논쟁", "en": "Development economists debate whether microfinance interest rates charged to poor borrowers in developing countries constitute modern usury, arguing that even rates below legal ceilings may be exploitative given the borrowers' lack of alternatives.", "ko": "개발 경제학자들은 개발도상국의 빈곤 차입자들에게 부과되는 마이크로파이낸스 이자율이 현대적 고리대금을 구성하는지를 논의하며, 법적 상한선 이하의 비율도 차입자들의 대안 부재를 고려할 때 착취적일 수 있다고 주장한다."},
        {"situation": "비공식 금융 시장 착취", "en": "Empirical research on informal moneylending in rural economies consistently documents usury rates that bear no relationship to formal lending costs, reflecting the monopoly power of lenders over borrowers with no access to institutional credit.", "ko": "농촌 경제에서의 비공식 사금융에 관한 경험적 연구는 기관 신용에 접근할 수 없는 차입자들에 대한 대출자들의 독점적 권력을 반영하는, 공식 대출 비용과 전혀 무관한 고리대금 비율을 일관되게 기록한다."},
    ],
    209: [  # waiver
        {"situation": "계약 조건 포기 협의", "en": "The lender's formal waiver of the covenant breach gave the borrower six months to remedy the underlying financial ratios without triggering an event of default under the facility agreement.", "ko": "대출자의 약정 위반에 대한 공식적인 권리 포기는 차입자에게 시설 계약에 따른 채무 불이행 사유를 촉발하지 않고 기초 재무 비율을 개선하기 위한 6개월을 부여했다."},
        {"situation": "소송 권리 포기 합의", "en": "The settlement agreement included a comprehensive waiver of all present and future claims arising from the disputed transaction, preventing either party from subsequently relitigating the resolved issues.", "ko": "합의 계약에는 분쟁이 된 거래에서 발생하는 현재 및 미래의 모든 청구권의 포괄적 권리 포기가 포함되어, 어느 당사자도 이후에 해결된 사안들을 다시 소송에서 다툴 수 없도록 했다."},
        {"situation": "국가 주권 면제 포기", "en": "By agreeing to arbitration clauses in commercial contracts, sovereign states effectively execute a waiver of their customary immunity from judicial proceedings, exposing themselves to binding awards enforced through international conventions.", "ko": "상업 계약의 중재 조항에 동의함으로써, 주권 국가들은 사실상 사법 절차로부터의 관습적 면제를 포기하여, 국제 협약을 통해 집행되는 구속력 있는 판정에 노출된다."},
        {"situation": "의료 동의 면제 요청", "en": "Institutional review boards may grant a waiver of informed consent requirements for minimal-risk research where obtaining consent is impracticable and the waiver will not adversely affect participants' rights and welfare.", "ko": "기관 심사 위원회는 동의를 얻는 것이 실행 불가능하고 권리 포기가 참여자의 권리와 복지에 부정적인 영향을 미치지 않는 최소 위험 연구에 대해 충분한 정보에 기반한 동의 요건의 면제를 허용할 수 있다."},
        {"situation": "비자 입국 허가 예외", "en": "The visa waiver program permits nationals of designated countries to enter for tourism or business without obtaining prior authorization, subject to enhanced security screening and strict limitations on the duration of permitted stay.", "ko": "비자 면제 프로그램은 지정된 국가의 국민이 강화된 보안 심사와 허용 체류 기간에 대한 엄격한 제한을 조건으로, 사전 허가를 받지 않고 관광 또는 사업 목적으로 입국하는 것을 허가한다."},
    ],
    210: [  # volatility
        {"situation": "금융 시장 위험 측정", "en": "Implied volatility, derived from options pricing, serves as a forward-looking measure of market uncertainty that often provides earlier warning signals of financial stress than backward-looking historical volatility metrics.", "ko": "옵션 가격에서 도출된 내재 변동성은 후향적 역사적 변동성 지표보다 종종 더 이른 금융 스트레스 경보 신호를 제공하는 시장 불확실성의 미래 지향적 측정값으로 기능한다."},
        {"situation": "기후 변화 날씨 불안정성", "en": "Climate scientists project that global warming will substantially increase atmospheric volatility, amplifying the frequency and intensity of extreme precipitation events while simultaneously prolonging drought conditions in arid regions.", "ko": "기후 과학자들은 지구 온난화가 대기 변동성을 상당히 증가시켜, 건조 지역의 가뭄 조건을 연장하는 동시에 극단적 강수 현상의 빈도와 강도를 증폭시킬 것이라고 예측한다."},
        {"situation": "정치적 불안정성 측정", "en": "Political scientists have developed composite indices to measure regime volatility, identifying constitutional changes, government turnover rates, and civil conflict intensity as key indicators of institutional instability.", "ko": "정치학자들은 체제 변동성을 측정하기 위한 복합 지수를 개발했으며, 헌법 변경, 정부 교체율, 내전 강도를 제도적 불안정성의 핵심 지표로 파악했다."},
        {"situation": "원자재 가격 공급망 영향", "en": "The extreme volatility of rare earth mineral prices has incentivized manufacturers of electric vehicles and renewable energy equipment to invest in supply chain diversification and domestic refining capacity.", "ko": "희토류 광물 가격의 극단적인 변동성은 전기 자동차 및 재생 가능 에너지 장비 제조업체들이 공급망 다각화와 국내 정제 능력에 투자하도록 인센티브를 제공했다."},
        {"situation": "포트폴리오 위험 관리 전략", "en": "Institutional investors seeking to manage portfolio volatility through diversification must account for the tendency of asset class correlations to increase dramatically during market stress events, reducing the protective effect of nominal diversification.", "ko": "다각화를 통해 포트폴리오 변동성을 관리하려는 기관 투자자들은 시장 스트레스 사건 동안 자산 등급 간 상관관계가 극적으로 증가하는 경향을 고려해야 하며, 이는 명목상 다각화의 보호 효과를 줄인다."},
    ],
    211: [  # warranty
        {"situation": "소비자 제품 품질 보증", "en": "The statutory implied warranty of satisfactory quality cannot be excluded in consumer contracts, providing a baseline protection for purchasers that exists independently of any express warranty offered by the manufacturer.", "ko": "만족스러운 품질의 법정 묵시적 품질 보증은 소비자 계약에서 배제될 수 없으며, 제조업체가 제공하는 명시적 품질 보증과 독립적으로 존재하는 구매자를 위한 기본 보호를 제공한다."},
        {"situation": "부동산 거래 권리 보증", "en": "The vendor's warranty of title confirmed that she possessed good and marketable title, free from undisclosed encumbrances, and that the buyer would enjoy quiet possession following completion of the conveyance.", "ko": "매도인의 소유권 보증은 그녀가 미공개 부담이 없는 유효하고 시장성 있는 소유권을 보유하고 있으며, 양도 완료 이후 매수인이 방해받지 않는 점유를 누릴 것임을 확인했다."},
        {"situation": "인수합병 진술 보증 조항", "en": "The acquisition agreement's representations and warranties regarding the target company's financial statements, material contracts, and regulatory compliance formed the basis for the indemnification obligations triggered by post-closing breaches.", "ko": "피인수 기업의 재무제표, 중요 계약, 규제 준수에 관한 인수 계약의 진술 및 보증은 거래 후 위반에 의해 촉발되는 면책 의무의 근거를 형성했다."},
        {"situation": "소프트웨어 기능 보증 한계", "en": "Enterprise software vendors typically disclaim all implied warranties of merchantability and fitness for purpose, insisting instead on express warranties limited to documented specifications and subject to strict exclusions for consequential damages.", "ko": "기업용 소프트웨어 공급업체들은 일반적으로 상업성 및 목적 적합성에 관한 모든 묵시적 품질 보증을 면책하며, 대신 문서화된 사양에 제한되고 결과적 손해에 대한 엄격한 제외를 조건으로 하는 명시적 품질 보증을 주장한다."},
        {"situation": "환경 보증 기업 책임", "en": "The seller's environmental warranties, which guaranteed that the property had no unresolved contamination issues, were among the most heavily negotiated provisions given the potential magnitude of remediation liabilities.", "ko": "부동산에 미해결된 오염 문제가 없음을 보증한 매도인의 환경 보증은 정화 부채의 잠재적 규모를 고려할 때 가장 치열하게 협상된 조항 중 하나였다."},
    ],
    212: [  # whistleblower
        {"situation": "기업 내부 비위 폭로", "en": "The whistleblower's disclosure of systematic accounting irregularities triggered a regulatory investigation that ultimately resulted in the prosecution of seven senior executives and the company's financial restatement.", "ko": "체계적인 회계 불규칙에 대한 내부 고발자의 폭로는 결국 7명의 고위 임원 기소와 회사의 재무 수정을 초래한 규제 조사를 촉발했다."},
        {"situation": "국가 안보 기밀 폭로 딜레마", "en": "The legal status of national security whistleblowers remains deeply contested, as the public interest in democratic accountability for covert surveillance programs conflicts with governments' legitimate interests in protecting classified intelligence methods.", "ko": "비밀 감시 프로그램에 대한 민주적 책임에 관한 공익이 분류된 정보 방법을 보호하는 정부의 정당한 이익과 충돌하기 때문에, 국가 안보 내부 고발자의 법적 지위는 여전히 깊이 논쟁의 대상이다."},
        {"situation": "환경 오염 기업 고발", "en": "Corporate whistleblowers who report environmental violations in good faith are entitled to statutory protection from retaliation, including reinstatement with back pay and compensation for harm to their professional reputations.", "ko": "선의로 환경 위반을 신고하는 기업 내부 고발자들은 소급 임금과 함께 복직 및 직업적 명성 피해에 대한 보상을 포함하는 보복으로부터의 법정 보호를 받을 자격이 있다."},
        {"situation": "의료 안전 불량 보고", "en": "Healthcare whistleblowers who report patient safety violations face a particularly acute dilemma, as professional loyalty norms within medical institutions can create powerful informal pressures to suppress concerns through internal channels.", "ko": "환자 안전 위반을 보고하는 의료 내부 고발자들은 특히 심각한 딜레마에 직면하는데, 의료 기관 내의 직업적 충성 규범이 내부 채널을 통해 우려를 억압하는 강력한 비공식적 압력을 만들 수 있기 때문이다."},
        {"situation": "금융 사기 적발 인센티브", "en": "The SEC's whistleblower reward program, which provides financial awards of up to thirty percent of sanctions exceeding one million dollars, has proven remarkably effective at generating tips that lead to major enforcement actions.", "ko": "100만 달러를 초과하는 제재의 최대 30%까지 재정적 보상을 제공하는 SEC의 내부 고발자 보상 프로그램은 주요 집행 조치로 이어지는 제보를 창출하는 데 매우 효과적인 것으로 입증되었다."},
    ],
    213: [  # withdrawal
        {"situation": "국제 조약 탈퇴 절차", "en": "The Paris Agreement's withdrawal provisions require a three-year notification period, a procedural safeguard that prevents impulsive political decisions from immediately disrupting the collective decarbonization framework.", "ko": "파리 협정의 탈퇴 조항은 3년의 통보 기간을 요구하는데, 이는 충동적인 정치적 결정이 즉각적으로 집단적 탈탄소화 체계를 방해하지 못하도록 하는 절차적 안전장치이다."},
        {"situation": "은행 뱅크런 위기", "en": "Mass depositor withdrawal triggered by loss of confidence in a bank's solvency can precipitate the very insolvency feared, creating a self-fulfilling prophecy that deposit insurance schemes are designed to prevent.", "ko": "은행의 지급 능력에 대한 신뢰 상실로 촉발된 대규모 예금자 인출은 우려되던 지급 불능을 촉발할 수 있어, 예금 보험 제도가 방지하도록 설계된 자기 충족적 예언을 만들어낸다."},
        {"situation": "군사력 철수 외교 협상", "en": "The phased withdrawal of foreign military forces was conditioned upon the host government demonstrating sufficient security capacity to prevent the resurgence of insurgent activity in previously stabilized regions.", "ko": "외국 군사력의 단계적 철수는 접수국 정부가 이전에 안정화된 지역에서의 반란 활동 재발을 방지하기에 충분한 안보 역량을 보여주는 것을 조건으로 했다."},
        {"situation": "투자 펀드 자금 회수", "en": "Open-ended fund managers face significant liquidity risk when stressed market conditions drive simultaneous withdrawal requests from multiple investors, potentially forcing the sale of illiquid assets at distressed prices.", "ko": "개방형 펀드 매니저들은 스트레스를 받은 시장 상황이 복수 투자자들의 동시 자금 회수 요청을 유발할 때 상당한 유동성 위험에 직면하며, 이는 잠재적으로 비유동 자산을 곤경 가격에 매각하도록 강제한다."},
        {"situation": "연구 참여 동의 철회", "en": "Research ethics requires that participants retain the unqualified right of withdrawal from a study at any time without penalty, and investigators must ensure that this right is not undermined by the design of incentive structures.", "ko": "연구 윤리는 참여자들이 불이익 없이 언제든지 연구로부터 조건 없이 탈퇴할 권리를 유지해야 하며, 연구자들은 인센티브 구조 설계로 이 권리가 훼손되지 않도록 보장해야 한다."},
    ],
}

for word_id, new_exs in new_examples.items():
    if word_id in word_map:
        word_map[word_id]['examples'].extend(new_exs)

with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Batch 4 done.")
with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'r', encoding='utf-8') as f:
    d2 = json.load(f)
wm2 = {w['id']: w for w in d2['words']}
for wid in sorted(new_examples.keys()):
    print(f"  id={wid} {wm2[wid]['word']}: {len(wm2[wid]['examples'])} examples")
