import json
with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', encoding='utf-8') as f:
    data7 = json.load(f)
R = {}

R["lucrative"] = [
    {"situation": "비즈니스 기회 및 수익성 평가", "en": "The company identified a lucrative niche in premium organic food products targeting health-conscious consumers.", "ko": "회사는 건강을 의식하는 소비자들을 대상으로 한 프리미엄 유기농 식품 제품에서 수익성 있는 틈새 시장을 발견했다."},
    {"situation": "국제 무역 및 시장 진출", "en": "Emerging markets in Southeast Asia offered lucrative opportunities for European pharmaceutical companies.", "ko": "동남아시아의 신흥 시장은 유럽 제약 회사들에 수익성 있는 기회를 제공했다."},
    {"situation": "직업 선택 및 취업 시장", "en": "A career in investment banking is considered lucrative but demands long hours and high performance.", "ko": "투자 은행 분야의 커리어는 수익성 있는 것으로 여겨지지만 장시간 근무와 높은 성과를 요구한다."},
    {"situation": "범죄 경제학 및 불법 시장", "en": "Traffickers are attracted by the lucrative profits generated by the illegal trade in endangered species.", "ko": "밀수업자들은 멸종 위기종의 불법 거래에서 발생하는 수익성 높은 이윤에 매력을 느낀다."},
    {"situation": "기술 스타트업 및 투자 유치", "en": "Venture capitalists poured funding into the lucrative artificial intelligence sector in the early 2020s.", "ko": "벤처 캐피털리스트들은 2020년대 초반 수익성 있는 인공지능 분야에 자금을 쏟아부었다."},
    {"situation": "스포츠 산업 및 중계권", "en": "Broadcasters competed fiercely for the lucrative rights to air the international football tournament.", "ko": "방송사들은 국제 축구 대회를 방영할 수익성 있는 권리를 위해 치열하게 경쟁했다."},
    {"situation": "부동산 투자 및 임대 수익", "en": "Short-term holiday lettings in coastal areas can be lucrative during peak tourist seasons.", "ko": "해안 지역의 단기 휴가 임대는 성수기 관광 시즌 동안 수익성이 높을 수 있다."},
    {"situation": "제약 산업 및 신약 개발", "en": "Developing a blockbuster drug can be extraordinarily lucrative for pharmaceutical firms willing to bear the research costs.", "ko": "블록버스터 신약 개발은 연구 비용을 부담할 의향이 있는 제약 회사에 엄청나게 수익성이 높을 수 있다."},
    {"situation": "정부 계약 및 공공 조달", "en": "Defence contracts are among the most lucrative in the public procurement sector due to their scale and duration.", "ko": "국방 계약은 규모와 기간으로 인해 공공 조달 부문에서 가장 수익성이 높은 계약 중 하나이다."},
    {"situation": "디지털 경제 및 플랫폼 비즈니스", "en": "Online advertising remains an extraordinarily lucrative revenue model for major digital platform companies.", "ko": "온라인 광고는 주요 디지털 플랫폼 회사들에게 여전히 엄청나게 수익성 있는 수익 모델로 남아 있다."}
]

R["macroeconomic"] = [
    {"situation": "경제 정책 및 거시 경제 안정화", "en": "The government's macroeconomic framework prioritised low inflation and fiscal discipline over short-term growth.", "ko": "정부의 거시경제 틀은 단기 성장보다 낮은 인플레이션과 재정 규율을 우선시했다."},
    {"situation": "국제 통화 기금 및 경제 조건", "en": "The IMF required the country to implement macroeconomic reforms as a condition for receiving emergency loans.", "ko": "IMF는 긴급 대출을 받는 조건으로 해당 국가가 거시경제 개혁을 시행할 것을 요구했다."},
    {"situation": "기업 전략 및 외부 환경 분석", "en": "Senior executives must remain alert to macroeconomic shifts that could affect demand for their products.", "ko": "고위 임원들은 제품에 대한 수요에 영향을 미칠 수 있는 거시경제적 변화에 주의를 기울여야 한다."},
    {"situation": "금리 정책 및 중앙은행 역할", "en": "Central banks adjust interest rates in response to macroeconomic indicators such as inflation and unemployment.", "ko": "중앙은행은 인플레이션 및 실업률과 같은 거시경제 지표에 대응하여 금리를 조정한다."},
    {"situation": "무역 수지 및 환율 영향", "en": "A persistent trade deficit is one of several macroeconomic imbalances that policymakers sought to address.", "ko": "지속적인 무역 적자는 정책 입안자들이 해결하려 했던 여러 거시경제적 불균형 중 하나이다."},
    {"situation": "코로나19 경제 충격 및 회복", "en": "The pandemic caused the most severe macroeconomic contraction since the Second World War in many developed economies.", "ko": "팬데믹은 많은 선진국 경제에서 제2차 세계대전 이후 가장 심각한 거시경제 침체를 초래했다."},
    {"situation": "개발 경제학 및 빈곤 감소", "en": "Macroeconomic stability is considered a necessary but insufficient condition for sustainable poverty reduction.", "ko": "거시경제적 안정성은 지속 가능한 빈곤 감소를 위한 필요 조건이지만 충분한 조건은 아닌 것으로 여겨진다."},
    {"situation": "주식 시장 및 투자자 심리", "en": "Equity markets reacted sharply to deteriorating macroeconomic data, with indices falling across multiple exchanges.", "ko": "주식 시장은 악화되는 거시경제 데이터에 날카롭게 반응하여 여러 거래소에서 지수가 하락했다."},
    {"situation": "고용 시장 및 노동 정책", "en": "Structural unemployment often persists even when the macroeconomic cycle is in a phase of expansion.", "ko": "구조적 실업은 거시경제 주기가 팽창 단계에 있을 때도 종종 지속된다."},
    {"situation": "기후 정책 및 녹색 경제 전환", "en": "The transition to a low-carbon economy will require significant macroeconomic adjustments across multiple sectors.", "ko": "저탄소 경제로의 전환은 여러 분야에 걸쳐 상당한 거시경제적 조정을 요구할 것이다."}
]

R["meticulous"] = [
    {"situation": "법률 문서 작성 및 계약 검토", "en": "The legal team conducted a meticulous review of every clause before the merger agreement was signed.", "ko": "법무팀은 합병 계약서에 서명하기 전에 모든 조항을 꼼꼼하게 검토했다."},
    {"situation": "과학 실험 및 실험실 프로토콜", "en": "Meticulous laboratory records are essential to ensure the reproducibility of experimental results.", "ko": "꼼꼼한 실험실 기록은 실험 결과의 재현성을 보장하는 데 필수적이다."},
    {"situation": "건축 설계 및 공학 계획", "en": "The architect was known for her meticulous attention to structural detail, which prevented costly errors.", "ko": "건축가는 구조적 세부 사항에 대한 꼼꼼한 주의로 유명했으며, 이는 비용이 많이 드는 오류를 방지했다."},
    {"situation": "역사 연구 및 문서 조사", "en": "The historian spent years in meticulous archival research before publishing his account of the conflict.", "ko": "역사학자는 분쟁에 관한 설명을 발표하기 전에 수년간 꼼꼼한 기록 보관 연구에 시간을 보냈다."},
    {"situation": "회계 감사 및 재정 감사", "en": "The auditor's meticulous analysis of the company's ledgers uncovered a pattern of systematic fraud.", "ko": "감사인의 회사 원장에 대한 꼼꼼한 분석은 체계적인 사기 패턴을 밝혀냈다."},
    {"situation": "의료 수술 및 임상 정밀도", "en": "Meticulous surgical technique is especially critical in microsurgery, where margins for error are minimal.", "ko": "꼼꼼한 외과적 기술은 오류 허용 한계가 최소인 미세 수술에서 특히 중요하다."},
    {"situation": "편집 및 출판 품질 관리", "en": "The editor was praised for her meticulous proofreading, which eliminated every factual and grammatical error.", "ko": "편집자는 모든 사실적·문법적 오류를 제거하는 꼼꼼한 교정으로 칭찬을 받았다."},
    {"situation": "형사 수사 및 증거 관리", "en": "Meticulous documentation of evidence collection is vital to ensure its admissibility in court.", "ko": "꼼꼼한 증거 수집 문서화는 법정에서의 허용 가능성을 보장하는 데 필수적이다."},
    {"situation": "패션 및 수공예 제품 생산", "en": "The luxury watchmaker was celebrated for the meticulous craftsmanship applied to every component of each timepiece.", "ko": "럭셔리 시계 제조업체는 각 시계의 모든 부품에 적용된 꼼꼼한 장인 정신으로 유명했다."},
    {"situation": "세금 신고 및 재무 기록 관리", "en": "Taxpayers engaged in complex business activities must maintain meticulous records to support their filings.", "ko": "복잡한 사업 활동에 종사하는 납세자들은 신고를 뒷받침하기 위해 꼼꼼한 기록을 유지해야 한다."}
]

R["microeconomic"] = [
    {"situation": "가격 설정 및 시장 행동 분석", "en": "A microeconomic analysis of the housing market reveals how zoning regulations distort price signals.", "ko": "주택 시장에 대한 미시경제적 분석은 용도 지역 규정이 어떻게 가격 신호를 왜곡하는지 보여준다."},
    {"situation": "기업 의사결정 및 비용 편익 분석", "en": "Managers apply microeconomic principles when deciding whether to produce in-house or outsource a service.", "ko": "관리자들은 서비스를 자체 생산할지 외주로 맡길지 결정할 때 미시경제학 원칙을 적용한다."},
    {"situation": "경쟁 정책 및 시장 구조", "en": "Regulators used microeconomic modelling to assess the likely impact of the proposed merger on consumer prices.", "ko": "규제 당국은 제안된 합병이 소비자 가격에 미칠 영향을 평가하기 위해 미시경제 모델링을 사용했다."},
    {"situation": "노동 시장 및 임금 결정", "en": "Microeconomic theory predicts that minimum wages above equilibrium will lead to a reduction in employment.", "ko": "미시경제 이론은 균형 임금을 초과하는 최저 임금이 고용 감소로 이어질 것이라고 예측한다."},
    {"situation": "농업 경제학 및 공급 반응", "en": "Farmers' decisions about crop selection are driven by microeconomic incentives such as price expectations and input costs.", "ko": "농부들의 작물 선택에 관한 결정은 가격 기대치와 투입 비용과 같은 미시경제적 인센티브에 의해 이루어진다."},
    {"situation": "교육 경제학 및 인적 자본 투자", "en": "A microeconomic perspective on education focuses on the individual returns to schooling and skill acquisition.", "ko": "교육에 대한 미시경제적 관점은 교육과 기술 습득에 대한 개인의 수익에 초점을 맞춘다."},
    {"situation": "의료 경제학 및 환자 선택", "en": "Microeconomic analysis of healthcare markets highlights the role of information asymmetry in doctor-patient relationships.", "ko": "의료 시장에 대한 미시경제 분석은 의사-환자 관계에서 정보 비대칭의 역할을 강조한다."},
    {"situation": "환경 경제학 및 외부 효과", "en": "Microeconomic tools such as carbon pricing aim to internalise the external costs of pollution.", "ko": "탄소 가격제와 같은 미시경제적 도구는 오염의 외부 비용을 내재화하는 것을 목표로 한다."},
    {"situation": "국제 무역 이론 및 비교 우위", "en": "At the microeconomic level, trade liberalisation creates winners and losers within individual industries.", "ko": "미시경제 수준에서 무역 자유화는 개별 산업 내에서 승자와 패자를 만들어낸다."},
    {"situation": "소비자 이론 및 선호 분석", "en": "Microeconomic consumer theory assumes that individuals make rational choices based on preferences and budget constraints.", "ko": "미시경제 소비자 이론은 개인이 선호도와 예산 제약을 기반으로 합리적인 선택을 한다고 가정한다."}
]

R["nascent"] = [
    {"situation": "기술 혁신 및 신흥 산업", "en": "The nascent electric vehicle industry required substantial government subsidies to achieve commercial viability.", "ko": "초기 단계의 전기차 산업은 상업적 실행 가능성을 달성하기 위해 상당한 정부 보조금이 필요했다."},
    {"situation": "정치 민주화 및 국가 건설", "en": "International observers were cautious about destabilising the nascent democratic institutions in the post-conflict state.", "ko": "국제 옵저버들은 분쟁 후 국가의 초기 단계 민주주의 제도를 불안정하게 만드는 것에 신중했다."},
    {"situation": "의학 연구 및 신치료법 개발", "en": "Gene therapy remains a nascent field with considerable potential but also significant unresolved safety concerns.", "ko": "유전자 치료는 상당한 잠재력을 가지고 있지만 미해결된 심각한 안전 우려가 있는 초기 분야로 남아 있다."},
    {"situation": "경제 발전 및 개발도상국 성장", "en": "Foreign investment played a crucial role in supporting the nascent manufacturing sector in the developing economy.", "ko": "외국인 투자는 개발도상국 경제에서 초기 단계의 제조업 부문을 지원하는 데 중요한 역할을 했다."},
    {"situation": "사회 운동 및 시민 활동", "en": "The nascent environmental movement of the 1960s laid the groundwork for today's global climate activism.", "ko": "1960년대의 초기 환경 운동은 오늘날 세계적인 기후 행동주의의 토대를 마련했다."},
    {"situation": "스타트업 생태계 및 벤처 투자", "en": "Silicon Valley developed a culture of mentorship that helped nascent companies navigate their early growth stages.", "ko": "실리콘 밸리는 초기 단계 기업들이 초기 성장 단계를 헤쳐나가는 데 도움이 되는 멘토링 문화를 발전시켰다."},
    {"situation": "국제법 및 규범 형성", "en": "Scholars debate whether norms governing cyber warfare remain nascent or have already crystallised into binding rules.", "ko": "학자들은 사이버 전쟁을 규율하는 규범이 아직 초기 단계인지, 아니면 이미 구속력 있는 규칙으로 결정화되었는지를 논쟁한다."},
    {"situation": "언어학 및 언어 변화", "en": "Linguists documented a nascent shift in pronoun usage among younger urban speakers.", "ko": "언어학자들은 젊은 도시 화자들 사이에서 대명사 사용의 초기 단계 변화를 기록했다."},
    {"situation": "금융 시장 및 신흥 자산 클래스", "en": "Cryptocurrency represents a nascent asset class whose regulatory status remains contested across jurisdictions.", "ko": "암호화폐는 관할권에 걸쳐 규제 상태가 여전히 논쟁 중인 초기 단계의 자산 클래스를 나타낸다."},
    {"situation": "교육 정책 및 혁신 교수법", "en": "Competency-based education remains nascent in many countries but is gaining traction as a reform model.", "ko": "역량 기반 교육은 많은 나라에서 아직 초기 단계이지만 개혁 모델로서 지지를 얻고 있다."}
]

R["obsolete"] = [
    {"situation": "기술 발전 및 구형 시스템", "en": "Legacy software systems that have become obsolete pose significant security vulnerabilities for organisations.", "ko": "구식이 된 레거시 소프트웨어 시스템은 조직에 상당한 보안 취약점을 야기한다."},
    {"situation": "노동 시장 및 자동화 충격", "en": "Many factory jobs became obsolete as industrial robots capable of greater precision and speed were introduced.", "ko": "더 높은 정밀도와 속도를 가진 산업용 로봇이 도입되면서 많은 공장 일자리가 구식이 되었다."},
    {"situation": "법률 및 시대에 뒤떨어진 규정", "en": "Legal scholars called for the repeal of several obsolete statutes that had not been enforced in decades.", "ko": "법학자들은 수십 년간 집행되지 않은 여러 구식 법령의 폐지를 촉구했다."},
    {"situation": "언어 변화 및 어휘 소멸", "en": "Many words in classical literature are now obsolete, requiring readers to consult specialised glossaries.", "ko": "고전 문학의 많은 단어들은 이제 구식이 되어 독자들이 전문 용어 해설서를 참고해야 한다."},
    {"situation": "군사 기술 및 무기 체계", "en": "Traditional tank warfare tactics became increasingly obsolete in the face of precision drone technology.", "ko": "전통적인 탱크 전투 전술은 정밀 드론 기술에 직면하여 점점 더 구식이 되었다."},
    {"situation": "교육 과정 및 교수 방법 개혁", "en": "Critics argue that rote memorisation has become obsolete in an age where information is instantly accessible online.", "ko": "비평가들은 정보가 온라인에서 즉시 접근 가능한 시대에 암기식 학습이 구식이 되었다고 주장한다."},
    {"situation": "의학 치료법 및 임상 지침", "en": "Several surgical procedures considered standard in the 1990s are now regarded as obsolete in light of newer evidence.", "ko": "1990년대에 표준으로 여겨졌던 몇 가지 외과 시술이 이제 최신 증거에 비추어 구식으로 간주된다."},
    {"situation": "인쇄 미디어 및 디지털 전환", "en": "The printed newspaper format has not become entirely obsolete, but its circulation has fallen dramatically.", "ko": "인쇄 신문 형식이 완전히 구식이 된 것은 아니지만 그 발행 부수는 급격히 감소했다."},
    {"situation": "지리 교육 및 지도 제작", "en": "Paper road maps became largely obsolete once satellite navigation systems became widely available in vehicles.", "ko": "위성 항법 시스템이 차량에 광범위하게 보급되면서 종이 도로 지도는 대체로 구식이 되었다."},
    {"situation": "경제 이론 및 패러다임 전환", "en": "Some economists argue that the traditional Phillips curve has become obsolete given the structural changes in labour markets.", "ko": "일부 경제학자들은 노동 시장의 구조적 변화를 감안할 때 전통적인 필립스 곡선이 구식이 되었다고 주장한다."}
]

R["omnibus"] = [
    {"situation": "의회 입법 및 복합 법안", "en": "The government introduced an omnibus bill combining tax reforms, welfare changes, and environmental regulations.", "ko": "정부는 세금 개혁, 복지 변화, 환경 규정을 통합한 포괄적 법안을 도입했다."},
    {"situation": "미디어 및 TV 프로그램 편성", "en": "The broadcaster aired an omnibus edition of the drama series on Sunday afternoons for viewers who had missed episodes.", "ko": "방송사는 에피소드를 놓친 시청자들을 위해 일요일 오후에 드라마 시리즈의 종합 편을 방영했다."},
    {"situation": "법원 절차 및 사건 관리", "en": "The judge issued an omnibus order addressing all pending procedural motions in the complex litigation.", "ko": "판사는 복잡한 소송에서 모든 계류 중인 절차적 신청들을 다루는 포괄적 명령을 내렸다."},
    {"situation": "출판 및 선집 편찬", "en": "The publisher released an omnibus volume collecting the author's entire trilogy in a single edition.", "ko": "출판사는 저자의 전체 삼부작을 단일 판본에 수록한 포괄적 선집을 출간했다."},
    {"situation": "계약 및 마스터 서비스 협약", "en": "The parties signed an omnibus agreement that governed all future transactions between the two companies.", "ko": "양측은 두 회사 간의 모든 미래 거래를 규율하는 포괄적 계약을 체결했다."},
    {"situation": "정부 지출 법안 및 예산 절차", "en": "Congress passed an omnibus spending bill to fund the government after failing to agree individual appropriations.", "ko": "의회는 개별 세출 예산안 합의에 실패한 후 정부에 자금을 지원하기 위한 포괄적 지출 법안을 통과시켰다."},
    {"situation": "법률 개혁 및 법전 편찬", "en": "An omnibus reform act was passed to consolidate dozens of separate regulatory frameworks into a single statute.", "ko": "수십 개의 개별 규제 틀을 단일 법령으로 통합하기 위해 포괄적 개혁법이 통과되었다."},
    {"situation": "학술 논문 및 문헌 검토", "en": "The review article served as an omnibus resource, synthesising findings from over two hundred separate studies.", "ko": "그 리뷰 논문은 200개 이상의 개별 연구에서 나온 결과물을 종합하는 포괄적 자료로 활용되었다."},
    {"situation": "기업 구조조정 및 포트폴리오 관리", "en": "The conglomerate sold its omnibus portfolio of non-core assets to raise capital for debt reduction.", "ko": "복합 기업은 부채 감소를 위한 자본 조달을 위해 비핵심 자산의 포괄적 포트폴리오를 매각했다."},
    {"situation": "소비자 보호 및 통합 입법", "en": "An omnibus consumer protection bill was proposed to replace the patchwork of existing regulations across different sectors.", "ko": "여러 부문에 걸친 기존 규정의 혼합을 대체하기 위한 포괄적 소비자 보호 법안이 제안되었다."}
]

R["pecuniary"] = [
    {"situation": "손해배상 및 민사 소송", "en": "The plaintiff sought pecuniary damages to compensate for lost earnings and business opportunities.", "ko": "원고는 손실된 수입과 사업 기회에 대한 보상으로 금전적 손해배상을 청구했다."},
    {"situation": "이사 의무 및 이해 충돌", "en": "A director must declare any pecuniary interest in a transaction before the board votes on it.", "ko": "이사는 이사회가 거래에 투표하기 전에 해당 거래에 대한 금전적 이해관계를 신고해야 한다."},
    {"situation": "공직자 윤리 및 청렴 의무", "en": "Public officials are prohibited from using their position to obtain pecuniary advantage for themselves or their families.", "ko": "공직자들은 자신이나 가족을 위한 금전적 이익을 얻기 위해 자신의 직위를 이용하는 것이 금지되어 있다."},
    {"situation": "세법 및 과세 혜택 판단", "en": "The tax authority assessed whether the arrangement had conferred a pecuniary benefit on the affiliated company.", "ko": "세무 당국은 해당 약정이 계열사에 금전적 이익을 부여했는지를 평가했다."},
    {"situation": "자선 단체 및 비영리 운영", "en": "Trustees must ensure that no pecuniary gain is derived by individuals from the charity's resources or operations.", "ko": "수탁자들은 자선단체의 자원이나 운영에서 개인이 금전적 이득을 얻지 않도록 보장해야 한다."},
    {"situation": "형사법 및 사기 범죄", "en": "The defendant was charged with obtaining a pecuniary advantage by deception, contrary to the Theft Act.", "ko": "피고는 절도법에 위반하여 기만을 통해 금전적 이익을 취한 혐의로 기소되었다."},
    {"situation": "노동법 및 직원 보상", "en": "Redundancy payments are intended to provide a pecuniary cushion while employees seek alternative employment.", "ko": "정리해고 수당은 직원들이 대안적인 취업 기회를 찾는 동안 금전적 완충을 제공하기 위한 것이다."},
    {"situation": "계약법 및 이행 불능 구제", "en": "Where specific performance is unavailable, courts award pecuniary remedies to place the claimant in their original position.", "ko": "특정 이행이 불가능한 경우, 법원은 청구인을 원래의 위치에 두기 위한 금전적 구제를 판결한다."},
    {"situation": "정치 자금 및 선거 기부", "en": "Electoral law requires candidates to disclose all pecuniary contributions received during the campaign period.", "ko": "선거법은 후보자들이 선거 운동 기간 중 받은 모든 금전적 기부금을 공개할 것을 요구한다."},
    {"situation": "학술 연구 윤리 및 이해관계 공개", "en": "Authors must declare any pecuniary relationships with commercial entities that may have influenced their findings.", "ko": "저자들은 연구 결과에 영향을 미쳤을 수 있는 상업 단체와의 금전적 관계를 신고해야 한다."}
]

count = 0
for w in data7['words']:
    if w['word'] in R:
        w['examples'] = R[w['word']]
        count += 1
print(f"Updated {count} words")
with open('D:/MakingApps/Youtube/Hellowords/data/IELTS/ielts_7.json', 'w', encoding='utf-8') as f:
    json.dump(data7, f, ensure_ascii=False, indent=2)
print("Saved ielts_7.json batch 5")
